### ISSUE TITLE
Building developer community

### ISSUE THREAD

**Issue by IharBury** [WowUp/WowUp#100]
Building such a project singlehandedly may become too huge an endeavor. It may require an active community of contributors to succeed. To create such a community the entrance barrier must be lowered however. It should be clear which tasks are up-for-grabs, which standards and design decisions the code must follow, etc.

**Comment by jliddev** [comment]
I am currently working on organizing things a bit more since the app has exploded lately. We've had a few community PRs already but things are moving in that direction :)

**Comment by staguer** [comment]
It's great to see the community expand, both in usage and with contributions. 

Adding a tag for up-for-grabs issues might be the easiest next step to get more help with the project.

**Comment by jliddev** [comment]
seems to be going well :)
