### ISSUE TITLE
Postal on curse not detected properly

### ISSUE THREAD

**Issue by SoLoR1** [WowUp/WowUp#1001]
**Describe the bug**
When you search for postal in wowup it gives you latest version from 12 years ago (3.1.2), considering both wowup and postal got upgraded in last ~24h im not sure if its fault of wowup or curse have an issue

**To Reproduce**
1. Go to search
2. look for postal
3. you see 3.1.2 as latest version (that is obviously broken in current retail)
4. issue why im not sure its wowups fault is, because if you go on curse page of the postal you see Game Version: 1.13.7 (and yes TOC of the addon is set correctly to 90100), so might be curse packaging issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/3218757/130459296-af93d942-baa6-4f2e-9b38-213586ddb006.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome 92. something
 - Version: 2.4.4

**Comment by SoLoR1** [comment]
i guess i got my answer:

View Zimzarina's Profile
Zimzarina 
Posted 9 hours ago
#2211
People are seeing a bunch of errors when updating this addon with addon update tools.  The problem is that Curseforge appears to be telling them for retail that v3.1.2 is the latest update as eric_draven pointed out below rather then 3.7.1 and is installing Postal v3.1.2 rather then the latest.  Please manually install version 3.7.1 for now until Curseforge fixes there issue.

 

Also, for those experiencing issues with opening mail not working in Postal version 3.7.0 the issue is I used a fairly generic frame name for the new Forward button and it collided with this same variable named used in the Addon Instance Achievement Tracker and possibly others.  I have fixed this issue by using a more unique Forward button frame name. Please install version 3.7.1 to fix this problem.  Thanks to immortalmotion for the detailed bug report on this issue it made finding the problem much easier.

Last edited by Zimzarina: 41 mins ago


so im will close this bug report, should read comments first and not only issues page before posting bug report.... :/

**Comment by jliddev** [comment]
Just to add some data to this. CurseForge is currently serving these as the latest files.
![image](https://user-images.githubusercontent.com/20467484/130461612-da5041e9-cf98-47cc-b5d2-c706993700ae.png)
