### ISSUE TITLE
Latest update locks up interface until accepted, downloaded and completed

### ISSUE THREAD

**Issue by alexpdr** [WowUp/WowUp#1006]
**Describe the bug**
Latest update locks up interface until accepted, downloaded and completed resulting in there being no way to skip, delay or cancel.

**To Reproduce**
N/A

**Expected behavior**
That the application is not locked up by the update pop-up when a new version is pulled.

**Screenshots**
Cannot provide as the whole application interface locked up the second the update was pulled.

**Desktop (please complete the following information):**
Pop_OS! 21.04

**Additional context**
Update did complete successfully, but not every network or connection is the right one for downloading updates.

**Comment by jliddev** [comment]
The update is downloaded in the background and should not lock up the app. 
Once the update is downloaded it will force you to install it, this is done to lower our support issues from people not updating.
