### ISSUE TITLE
More info about Backup folder, how to recover etc ?

### ISSUE THREAD

**Issue by emanueol** [WowUp/WowUp#1007]
Sorry to open issue here in github, but couldnt find by gogling information about:
- folder where wowup backup things ?
- does wowup keeps multiple backups or just keeps the latest snapshot ?
- how can we restore a backup ?
- is each backup global containing all addons and settings or just keep delta in whats changed per addon ?

But again most important for me now, would be to understand what is backup folder, thanks so much.
Maybe i was too noob finding above answers, let me know if theres a proper webpage with this insight, thanks.

~ Budha ~

**Comment by linaori** [comment]
During the update process WowUp moves (renames) the current addon(s) to a `-bak` directory in the addons directory. When the update fails, the backup is restored. When the update is finished, the backup is removed. 

Example when you update ElvUI:
 1. ElvUI and ElvUI_Options are moved to ElvUI-bak and ElvUI_Options-bak
 2. Update starts
 3.1 update fails: ElvUI-bak and ElvUI_Options-bak are moved back to ElvUI and ElvUI_Options
 3.2 update succeeds: the downloaded versions are moved to the addons directory
 4. ElvUI-bak and ElvUI_Options-bak are removed

All of this is done automatically and requires no manual interaction unless restoring the backup fails.

This has nothing to do with WTF data backups, this is something that is in the works and will be in a future update (not sure when).

**Comment by emanueol** [comment]
Thanks for the insight.


Thanks and Kind regards,
Emanuel Oliveira
Senior Data Engineer
