### ISSUE TITLE
Classic Addons not found

### ISSUE THREAD

**Issue by DavidBabel** [WowUp/WowUp#1018]
**Describe the bug**
Admit you want to search for this addon : https://www.curseforge.com/wow/addons/mychatalert/files

**To Reproduce**
![image](https://user-images.githubusercontent.com/5599375/133896876-23334fe1-2b01-4d3b-bd55-3cd78c04677a.png)

**Expected behavior**
the addons appear in the list since it has a "classic" version (classic = tbc now)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by linaori** [comment]
When I download the addon from CurseForge, the version inside the toc is incorrect:
```
## Interface: 11305
## Title: My Chat Alert
## Version: v2.5.4
```
It states that this is for Classic Era, not Burning Crusade Classic. My guess is that this is why WowUp won't let you install it.

To verify this, I get 2.5.4 for Classic Era in WowUp:
![image](https://user-images.githubusercontent.com/1754678/133897472-d2874fb7-69d5-4d29-9ab1-0ed6f675eac0.png)

**Comment by DavidBabel** [comment]
Thx for the info, i contacted the addon maker
