### ISSUE TITLE
Issue with extraction and installation of Altoholic update today

### ISSUE THREAD

**Issue by dblanch369** [WowUp/WowUp#1019]
**Describe the bug**
This morning, attempting to install an update for Retail version of Altoholic, WowUp instead prompts for a save location instead of automatically doing so.  program then hangs, but not fatally.  Other addons install/update just fine.

**To Reproduce**
*note* this only an error on Alcoholic retail. I did not have any other issues.
1. Go to Check Updates, then 
2. Either click Update where the add-on is listed, or selecting Update All from menu
3. WowUp is prompting for a save location, defaulting to my default Downloads folder, in my Home folder.
4. See error: Program "hangs", button displays "Downloading" and only shows partial completion, but file did download and save to Downloads folder.

**Expected behavior**
Expected behavior is for update to install normally, and without prompting for filename/save location

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2 (Big Sur)
 - Browser Safari / Firefox
 - Version 14.1.2 / 92.0

**Additional context**
None.  One other user (Medok) also experienced same thing, same add-on, same update. Except he is on Windows
<img width="1269" alt="Screen Shot 2021-09-19 at 8 15 47 AM" src="https://user-images.githubusercontent.com/23128709/133929977-035b4c13-802c-4df9-8988-f9926d258c81.png">
<img width="793" alt="Screen Shot 2021-09-19 at 9 24 35 AM" src="https://user-images.githubusercontent.com/23128709/133929987-bdf410cc-b96d-4fbb-8c2e-e1c79ba2a0be.png">
<img width="985" alt="Screen Shot 2021-09-19 at 9 25 35 AM" src="https://user-images.githubusercontent.com/23128709/133929988-598b41ce-c23e-4b0e-8f50-6edf17fe13f8.png">
.

**Comment by adde88** [comment]
Same issue here, as well as my wife experiencing the same issue.
Even after installing the update manually, it tries to download the same version again.

**Comment by DutchDerpo** [comment]
Same here. When updating the Altoholic addon from version 9.1.005 to 9.1.006 (alpha channel) in WowUp, it opens up the "Save To File" dialog.
My first thought is the "+" in the filename, but I am not sure.

Windows 10 (dutch)
WowUp client 2.5.0.Beta15
Firefox 92.0 default browser (dutch)
World Of Warcraft 9.1.0 Retail

<img width="1920" alt="WowUp io (2021-09-19-20u14m57s-701ms) (3840x2100)" src="https://user-images.githubusercontent.com/91028487/133938940-778fbfe0-421b-467f-9781-3a653acdccaf.png">
[WowUp Log - Error downloading update Altoholic addon.txt](https://github.com/WowUp/WowUp/files/7192717/WowUp.Log.-.Error.downloading.update.Altoholic.addon.txt)

**Comment by RedAntisocial** [comment]
Same issue here. Restarting WowUp doesn't fix it.
Manually updated from Curse, but I backed up the old version in case I need to test more.

**Comment by mdavidson37** [comment]
I can confirm I'm also experiencing this issue with the Beta client.

**Comment by jliddev** [comment]
This should now be resolved in beta 16

**Comment by DutchDerpo** [comment]
Confirmed, resolved in beta 16.

**Comment by dblanch369** [comment]
Yes, fixed in beta 16.  Thanks all!
