### ISSUE TITLE
Re-installing an addon when having a filter on the "My Addons" page removes the filter and shows all addons again

### ISSUE THREAD

**Issue by Feirlane** [WowUp/WowUp#1022]
**Describe the bug**
When in the "My Addons" view, after typing something in the "filter" box, the addons shown in the list will be only the ones matching the filter. If you then re-install any of the shown addons, the list will default back to all your addons, while the filter text is still in the "filter" input.

**To Reproduce**
1. Go to `My Addons`
1. Filter your installed addons by some text, ie `dbm`
1. Re-install one of the shown addons
1. After the addon is re-installed, the list of addons will go back to all addons, while `dbm` is still shown in the `filter` input

**Expected behavior**
After re-installing the addon the list should be the same as before re-installing, that is, only the addons matching the `filter`

**Screenshots**
![](https://i.imgur.com/7NsFFzC.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version `2.4.5`

**Comment by jliddev** [comment]
Can you try this in the beta client? I think we closed a ticket about this.

**Comment by Feirlane** [comment]
Yep, fixed in `2.5.0-beta.17`, nevermind! 👍
