### ISSUE TITLE
addon LootReserve version Sep 20, 2021 exists but wowup not able to get this last version from courseforge

### ISSUE THREAD

**Issue by emanueol** [WowUp/WowUp#1047]
**Describe the bug**
Wowup not able to pick latest addon version Sep 20, 2021 from https://www.curseforge.com/wow/addons/lootreserve/files

But WoWup only updates to version:
2021-Augst-31

**To Reproduce**
1. wow tcb ingame popup informs there's a new version Sep 20, 2021.
2. I verified its true and there's new addon Sep 20, 2021 in https://www.curseforge.com/wow/addons/lootreserve/files

**Expected behavior**
wowup able to install latest addon "LootReserve" version which is Sep 20, 2021

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jliddev** [comment]
This is an issue with the CurseForge API. It is giving an incorrect result. the website shows that this is tagged for TBC and Classic, but the API says its only tagged for Classic

```
"sortableGameVersion": [
                {
                    "gameVersionPadded": "0000000001.0000000014.0000000000",
                    "gameVersion": "1.14.0",
                    "gameVersionReleaseDate": "2021-09-02T00:00:00Z",
                    "gameVersionName": "1.14.0",
                    "gameVersionTypeId": 67408
                }
            ],
```

**Comment by emanueol** [comment]
Ok thanks for the feedback, I got addon installed via wowup, so i will just wait till courseforge fixes on their side and wowup will then push it.
