### ISSUE TITLE
PopOS 21.04 Error loading /app.asar/dist/index.html on startup

### ISSUE THREAD

**Issue by CHSchuepfer** [WowUp/WowUp#1049]
Hey everyone im getting an Error on Startup.
The exact Error Msg reads like: 

Error: ERR_FAILED (-2) loading 'file:///tmp/.mount_WowUp-pYQcyO/resources/app.asar/dist/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.stopLoadingListener (node:electron/js2c/browser_init:165:7861)
    at Object.emit (node:events:394:28)

I've tested the Version 2.4.3, 2.5.0 and 2.5.1.beta1
All versions i've tested experience the same output:

Stdout:

./WowUp-2.5.0.AppImage                                                                             
17:15:17.366 › Main starting
17:15:17.368 › Electron: 15.3.0
17:15:17.368 › BinaryPath: /tmp/.mount_WowUp-4QtcQ0/wowup
17:15:17.368 › ExecPath /tmp/.mount_WowUp-4QtcQ0/wowup
17:15:17.369 › Args [ '/tmp/.mount_WowUp-4QtcQ0/wowup' ]
17:15:17.370 › Log path: /home/zeto/.config/WowUp/logs
17:15:17.370 › ARGV { _: [], serve: false, hidden: false }
17:15:17.371 › USER_AGENT WowUp-Client/2.5.0 (Linux; 5.13.0-7620-generic; x64;  +https://wowup.io)
17:15:17.379 › Hardware acceleration enabled
17:15:17.625 › App ready: 255ms
17:15:17.625 › found window state: {
  width: 1280,
  height: 720,
  centered: false,
  x: 640,
  y: 334,
  isMaximized: false,
  isFullScreen: false
}
17:15:17.626 › {
  width: 1280,
  height: 720,
  centered: false,
  x: 640,
  y: 334,
  isMaximized: false,
  isFullScreen: false
}
17:15:17.626 › isVisibleOnAnyScreen { x: 32, y: 59, width: 2496, height: 1271 } true
17:15:17.752 › process.versions {
  node: '16.5.0',
  v8: '9.4.146.21-electron.0',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '98',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1',
  icu: '69.1',
  unicode: '13.0',
  electron: '15.3.0',
  chrome: '94.0.4606.81'
}
17:15:17.752 › Loading app URL: 382ms
17:15:17.787 › Error: ERR_FAILED (-2) loading 'file:///tmp/.mount_WowUp-4QtcQ0/resources/app.asar/dist/index.html'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.stopLoadingListener (node:electron/js2c/browser_init:165:7861)
    at Object.emit (node:events:394:28)

There isnt really anything special about this machine, nevertheless here's my systeminformation:

OS: Pop!_OS 21.04 x86_64 
Kernel: 5.13.0-7620-generic 
Uptime: 17 hours, 33 mins 
Packages: 2169 (dpkg), 6 (flatpak) 
Shell: bash 5.1.4 
Resolution: 2560x1440 
DE: GNOME 3.38.4 
WM: Mutter 
Theme: Pop 
Theme: Pop-dark [GTK2/3]Icons: Pop [GTK2/3] 
Terminal: gnomCPU: AMD Ryzen 7 3700X (16) @ 3.600GHz 
GPU: NVIDIA GeForce RTX 2070 Rev. A 
Memory: 11684MiB / 64221MiB 

Does anyone have an idea on whats the specific problem is or how i can Debug this situation better?

Thanks in advance

**Comment by linaori** [comment]
Can you try the [2.5.1-beta1](https://github.com/WowUp/WowUp/releases/tag/v2.5.1-beta.1) to see if that solves your problem?

**Comment by CHSchuepfer** [comment]
Hey @linaori ,

thanks for the reply. Sadly as i mentioned in the beginning no luck with the new version.
Was at first getting this error on 2.5.0 then i tried a downgrade to 2.4.3 (also no luck) and then went to 2.5.1 Beta 1.


Thanks and so long

**Comment by linaori** [comment]
Ah my bad, I missed the beta part. Has WowUp worked for you in the past or is this the first time you're trying it?

**Comment by CHSchuepfer** [comment]
All good, on this machine since reinstallation it was the first time i tried it.
Have run Wowup on Ubuntu based Distributions and Manajro on this HW before though.
Was also 5.13 Kernel.

Next step for me would be to switch out on Ubuntu vanilla 5.13 Kernel to test it out.
Gotta keep you updated, should take me about 30 mins.

Thanks :)

**Comment by CHSchuepfer** [comment]
Hey,

short update. Fresh Install of Ubuntu 21.10 but sadly no luck with stable 2.5.0.
Funny thing though.... 2.5.1 beta 1 works now.

As in terms of what has changed im not entirely sure but i can say that on vanilla Ubuntu 21.10 with WowUp 2.5.0 stable i dont get an Error over stdout it just freezes up when the changelog tries to get loaded.

I recorded and uploaded the whole preocedure and can be seen here: https://youtu.be/92qwmFn0e04

Heres the Stacktrace i was able to get from stable and as shown in the Screengrab:

./WowUp-2.5.0.AppImage 
19:31:14.118 › Main starting
19:31:14.120 › Electron: 15.3.0
19:31:14.121 › BinaryPath: /tmp/.mount_WowUp-QT9KBy/wowup
19:31:14.121 › ExecPath /tmp/.mount_WowUp-QT9KBy/wowup
19:31:14.121 › Args [ '/tmp/.mount_WowUp-QT9KBy/wowup' ]
19:31:14.122 › Log path: /home/zeto/.config/WowUp/logs
19:31:14.123 › ARGV { _: [], serve: false, hidden: false }
19:31:14.123 › USER_AGENT WowUp-Client/2.5.0 (Linux; 5.13.0-20-generic; x64;  +https://wowup.io)
19:31:14.132 › Hardware acceleration enabled
19:31:14.309 › App ready: 187ms
19:31:14.309 › found window state: {
  width: 1280,
  height: 720,
  centered: false,
  x: 640,
  y: 335,
  isMaximized: false,
  isFullScreen: false
}
19:31:14.310 › {
  width: 1280,
  height: 720,
  centered: false,
  x: 640,
  y: 335,
  isMaximized: false,
  isFullScreen: false
}
19:31:14.310 › isVisibleOnAnyScreen { x: 32, y: 59, width: 2496, height: 1273 } true
19:31:14.434 › process.versions {
  node: '16.5.0',
  v8: '9.4.146.21-electron.0',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '98',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '6.0.2',
  openssl: '1.1.1',
  icu: '69.1',
  unicode: '13.0',
  electron: '15.3.0',
  chrome: '94.0.4606.81'
}
19:31:14.434 › Loading app URL: 312ms
19:31:14.893 › Checking for update
19:31:14.894 › autoUpdater checking-for-update
19:31:15.151 › [CreateDirectory] '/home/zeto/.config/WowUp/downloads'
Creating tray
19:31:15.334 › Update for version 2.5.0 is not available (latest version: 2.5.0, downgrade is disallowed).
19:31:15.334 › autoUpdater update-not-available
19:31:15.334 › checkForUpdates {
  versionInfo: {
    version: '2.5.0',
    files: [ '[object]' ],
    path: 'WowUp-2.5.0.AppImage',
    sha512: 'TInGzARhogLj3emKfv/pS749GTBtsHrrHWc4gp/Grlx97gMyjeBsX5surHNQ6DxA9BXPDDfyxYAsaYFLQO7YzQ==',
    releaseDate: '2021-11-04T18:43:13.844Z',
    releaseName: '2.5.0',
    releaseNotes: '<h3>New Features</h3>\n' +
      '<ul>\n' +
      '<li>Added the ability to turn off system notifications for individual addons (tellier-dev)</li>\n' +
      '<li>Added the ability to remove addons from the details dialog on Get Addons tab (tellier-dev)</li>\n' +
      '<li>Added the ability to import/export a list of addons for a WoW client. The first step in backing up your list of addons or sharing them with your friends!</li>\n' +
      '<li>Added the ability to create and restore backups, this is a work in progress.</li>\n' +
      '<li>Added a button to open the client folder for a WoW install</li>\n' +
      '<li>Added WowUpHub category support</li>\n' +
      '<li>Added WowUpHub preview support</li>\n' +
      '<li>Added Mac M1 builds</li>\n' +
      '<li>Added support for more multi-toc suffixes</li>\n' +
      '<li>Added support for Classic Era PTR client</li>\n' +
      '<li>Added some badges to indicate number of updates and which client needs them</li>\n' +
      '</ul>\n' +
      '<h3>Fixes</h3>\n' +
      '<ul>\n' +
      '<li>Fix an issue with addons being ignored by TukUI too early during a scan</li>\n' +
      '<li>Fix an issue with certain addons not being able to be re-scanned</li>\n' +
      '<li>Fix an issue with updating the same addon in multiple WoW clients at the same time</li>\n' +
      '</ul>\n' +
      '<h3>Changes</h3>\n' +
      '<ul>\n' +
      '<li>Spanish locale updates (SkollVargr)</li>\n' +
      '<li>Chinese locale updates (CyanoHao)</li>\n' +
      '<li>Russian locale updates (Medok)</li>\n' +
      '<li>German locale updates (Glow)</li>\n' +
      '<li>Tweak the tabs some more</li>\n' +
      '<li>Performance improvements for My Addons page</li>\n' +
      '<li>Images details tab is now Previews</li>\n' +
      '<li>Use a different lightbox library for previews</li>\n' +
      '<li>Expanded system proxy support</li>\n' +
      '</ul>'
  },
  updateInfo: {
    version: '2.5.0',
    files: [ '[object]' ],
    path: 'WowUp-2.5.0.AppImage',
    sha512: 'TInGzARhogLj3emKfv/pS749GTBtsHrrHWc4gp/Grlx97gMyjeBsX5surHNQ6DxA9BXPDDfyxYAsaYFLQO7YzQ==',
    releaseDate: '2021-11-04T18:43:13.844Z',
    releaseName: '2.5.0',
    releaseNotes: '<h3>New Features</h3>\n' +
      '<ul>\n' +
      '<li>Added the ability to turn off system notifications for individual addons (tellier-dev)</li>\n' +
      '<li>Added the ability to remove addons from the details dialog on Get Addons tab (tellier-dev)</li>\n' +
      '<li>Added the ability to import/export a list of addons for a WoW client. The first step in backing up your list of addons or sharing them with your friends!</li>\n' +
      '<li>Added the ability to create and restore backups, this is a work in progress.</li>\n' +
      '<li>Added a button to open the client folder for a WoW install</li>\n' +
      '<li>Added WowUpHub category support</li>\n' +
      '<li>Added WowUpHub preview support</li>\n' +
      '<li>Added Mac M1 builds</li>\n' +
      '<li>Added support for more multi-toc suffixes</li>\n' +
      '<li>Added support for Classic Era PTR client</li>\n' +
      '<li>Added some badges to indicate number of updates and which client needs them</li>\n' +
      '</ul>\n' +
      '<h3>Fixes</h3>\n' +
      '<ul>\n' +
      '<li>Fix an issue with addons being ignored by TukUI too early during a scan</li>\n' +
      '<li>Fix an issue with certain addons not being able to be re-scanned</li>\n' +
      '<li>Fix an issue with updating the same addon in multiple WoW clients at the same time</li>\n' +
      '</ul>\n' +
      '<h3>Changes</h3>\n' +
      '<ul>\n' +
      '<li>Spanish locale updates (SkollVargr)</li>\n' +
      '<li>Chinese locale updates (CyanoHao)</li>\n' +
      '<li>Russian locale updates (Medok)</li>\n' +
      '<li>German locale updates (Glow)</li>\n' +
      '<li>Tweak the tabs some more</li>\n' +
      '<li>Performance improvements for My Addons page</li>\n' +
      '<li>Images details tab is now Previews</li>\n' +
      '<li>Use a different lightbox library for previews</li>\n' +
      '<li>Expanded system proxy support</li>\n' +
      '</ul>'
  }
}




So this issue can be closed alteast from me, but may be worth keeping an eye on it for ppl who are running 21.04 derivates like pop os. Or atleast the Kernel Build 5.13.0-20-generic


So long and thanks @linaori
