### ISSUE TITLE
Don't force auto updates on WowUp

### ISSUE THREAD

**Issue by LinuxWOW** [WowUp/WowUp#1050]
**Is your feature request related to a problem? Please describe.**
YES

**Describe the solution you'd like**
Don't force updates. let user update so if there is an issue it doesn't force updates

**Describe alternatives you've considered**
have tired older version 2.4.7 it works but auto force update happens

**Additional context**
 Using KDE Neon Ubuntu based 20.04

**Comment by jliddev** [comment]
Due to the limited amount of support we can provide with such a small team, it is necessary to keep user's up to date. If there are issues, its on us to fix them asap.

**Comment by Debuggernaut** [comment]
Man, @jliddev, that is a seriously screwed up attitude.  You're on a slippery slope, and at the bottom of it you'll be cramming in ads just like Curse/Overwolf/WarcraftLogs, mining our privacy, and getting up to who-knows-what else.

Just give updates a toggle switch, then put in a version field to your API and reject requests from older clients when you make a breaking change.

**Comment by Debuggernaut** [comment]
"Oh, small team, workin' in our spare time, gotta force updates soz its ez to maintain the server"

"Oh, small team spare time, gotta put in ads to pay for the server"

"Oh small team spare time forced telemetry to focus our limited time"

"small team spare time closed source going forward so thieves cant steal our app and redistrib sans ads"

"Great news!  We'll be partnering with Overwolf going forward to help ensure that addon authors get paid for their hard work!"

**Comment by jliddev** [comment]
Would you like a refund?

**Comment by MrUzagi** [comment]
> 
> 
> "Oh, small team, workin' in our spare time, gotta force updates soz its ez to maintain the server"
> 
> "Oh, small team spare time, gotta put in ads to pay for the server"
> 
> "Oh small team spare time forced telemetry to focus our limited time"
> 
> "small team spare time closed source going forward so thieves cant steal our app and redistrib sans ads"
> 
> "Great news! We'll be partnering with Overwolf going forward to help ensure that addon authors get paid for their hard work!"

I'm also not too keen on forced updates. But dude, chill. 
Btw; Forced updates is a thing even for not-so-small-teams. You can't play WoW without the latest updates either for example.

**Comment by Debuggernaut** [comment]
Ah, sorry guys, I don't mean to disrespect your hard work

Especially since this is an open source project, and it was easy enough to just fork it and strip out the part I didn't like

**Comment by jliddev** [comment]
Lol sure you did. And that's ok.

**Comment by Jovzin** [comment]
> Ah, sorry guys, I don't mean to disrespect your hard work
> 
> Especially since this is an open source project, and it was easy enough to just fork it and strip out the part I didn't like

How did you do it ?  
I would like to have this auto force update of WOWUP removed too.  Only option I think is to somehow block the traffic  that is not going to curse,elvui, etc for addon , via some software firewall. Or check where wowUP is trying to connect for updates of itself and block the IP via hosts file.
