### ISSUE TITLE
No addon on scan with retail

### ISSUE THREAD

**Issue by Ymerin** [WowUp/WowUp#1052]
I don't understand, i try to scan my retail addon with wowup (live and beta on linux) everytime it can see no addon in retail wow but in burning crusade addons, it has no issue. I use your addon on windows too, on the same folder i have no issue at all. I think i have found the issue by installing a new addon, it creates a new folders AddOns but with caps on the O. I try to change my original folder with a Caps O , it works again. That change causes no issue to wow. it's a fix for me

**Comment by linaori** [comment]
The directory is case sensitive on Linux. Renaming is indeed the fix.
