### ISSUE TITLE
Misidentified addon ever since I tried this program out when Overwolf announced it was taking over CurseForge

### ISSUE THREAD

**Issue by JeremyMorton** [WowUp/WowUp#1056]
**Describe the bug**
WowUp, through every version, has identified the addon "Accountant" as "ImpliedTarget"

**To Reproduce**
1. Install the latest version of the addon "Accountant": https://www.curseforge.com/wow/addons/accountant
2. Install the latest version of the addon "ImpliedTarget": https://www.wowinterface.com/downloads/info17648
3. Look at the versions offered in WowUp for those two addons, as well as which folder it says the addons are installed to.

**Expected behavior**
I expect both addons to be correctly identified in WowUp

**Screenshots**
![image](https://user-images.githubusercontent.com/10471528/141834540-b3224ac3-2847-4f80-88a0-4c875467bc01.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 2.5.1

**Additional context**
I occasionally fire up the program to see if it can identify these correctly, but it never has across many versions.

**Comment by jliddev** [comment]
Are you using this with Retail?

**Comment by JeremyMorton** [comment]
Yes

**Comment by JeremyMorton** [comment]
[renderer.zip](https://github.com/WowUp/WowUp/files/7540934/renderer.zip)

**Comment by jliddev** [comment]
Hmm, its working fine for me. Can you go to options > debug > click dump debug data . wait for it to finish then attach the renderer log

**Comment by JeremyMorton** [comment]
Does that give any leads?

**Comment by jliddev** [comment]
I dont see anything new attached.

**Comment by JeremyMorton** [comment]
I attached it 3 minutes before you asked.

**Comment by jliddev** [comment]
My bad.
Also, reproduced, which is good! 
![image](https://user-images.githubusercontent.com/20467484/142951150-1a73e878-a523-4c4b-8116-6fd1bf41aa46.png)

**Comment by jliddev** [comment]
This should be fixed as of 2.6.0-beta.3

**Comment by JeremyMorton** [comment]
Thank you, this is working for me now.
