### ISSUE TITLE
Addons showing as ignored

### ISSUE THREAD

**Issue by zhavier042** [WowUp/WowUp#1057]
**Describe the bug**
When re-scanning my addons folder, several addons moved from getting normal updates to being ignored.  I can still see the addons by browsing to them on curse.

**To Reproduce**
1. Re-scan addons
2. View list of addons, and see several ignored addons at the bottom.

**Expected behavior**
I expect the addons to not be listed as ignored, because they are still available through one of the listed providers.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 2.5.2

**Additional context**
I have 103 folders and 45 addons installed.  2 addons specifically showing ignored are Arkinventory and Consequence Flightmaster.  The addons dont change regardless of how many times I click re-scan.

**Comment by jliddev** [comment]
What wow client are these addons installed in? 
what provider did you install them with?

**Comment by zhavier042** [comment]
1) Wow Burning Crusade Classic
2) Curse

**Comment by jliddev** [comment]
So upon further investigation it appears to be an addon/CF issue. Currently the fingerprints for BCC Arkinventory return version 3.09.63 for retail. As is confirmed in CF's own app.

![image](https://user-images.githubusercontent.com/20467484/150065706-03159353-c1ae-4828-93c2-addf8cc9543d.png)

Consequence Flightmaster appears to work fine for me.
