### ISSUE TITLE
Won't open on macOS 10.14

### ISSUE THREAD

**Issue by derrickb** [WowUp/WowUp#1059]
**Describe the bug**
Installed WowUp 2.5.2
When attempting to open it I get the message `You can't use this version of the application "WowUp.app" with this version of macOS. You have macOS 10.14.16. The application requires macOS 10.11 or later.`

**Expected behavior**
Application should open on macOS 10.14 as it is greater than the stated minimum version, 10.11

**Screenshots**
![image](https://user-images.githubusercontent.com/1793769/142671756-3fb53994-84e5-489a-9872-85059f7cd92e.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6

**Comment by linaori** [comment]
Has WowUp worked in the past, or is this your first time installing? Can you also share which of the `.dmg` files you've downloaded and your mac specs (the one showing CPU/RAM etc)?

**Comment by derrickb** [comment]
This is my first time installing on my Macbook, have been using WowUp for a few months on my PC.

I downloaded this file from the WowUp homepage: `WowUp-2.5.2-arm64.dmg`.
I just tried installing `WowUp-2.5.2.dmg` and it **worked**.

Here are the specs you requested:
```
Processor: 1.6 GHz Intel Core i5
Memory: 8 GB 1600 MHz DDR3
Graphics: Intel HD Graphics 6000 1536 MB
```

**Comment by linaori** [comment]
Yes, the problem with arm64 is that it's designed for the M1 chips, you have an x86/x64 bit
