### ISSUE TITLE
[Feature Request] Custom source for github-hosted addons

### ISSUE THREAD

**Issue by alphabitnz** [WowUp/WowUp#1062]
Lately quite a few addons, especially forks of abandoned ones, are being hosted on github.

It would be great if WowUp could support tracking those github projects, even if it means the user manually specifies the URL.
e.g. <https://github.com/frozn/TipTac/> where frozn is doing a wonderful job of maintaining this addon which hasn't been updated by the original dev on curseforge for over a year.

Thanks and keep up the great work!

**Comment by linaori** [comment]
We have an indexing service called "wowup hub", which you can see here: https://wowup.io/addons

Currently the only way to get an addon on here, is it a manual script that has to be executed. If the author can join Discord and poke zakrn#1196 (@jliddev) there, he can add the addon to the hub.

**Comment by Sekkyo** [comment]
@linaori Is this why the WoWUp macOS client won't accept https://github.com/lindseyburnett/AutoCage as a source for Install from URL? It seems to me it should just be able to take any GitHub repo URL without issue.

**Comment by linaori** [comment]
@Sekkyo that repository has no releases. A release containing the final addon inside a directory (same name as toc minus the extension) inside a zip is required.

**Comment by Sekkyo** [comment]
Gotcha. I managed to grab it myself as a ZIP, I'll ask the author to make a release. Thanks!

**Comment by psykzz** [comment]
We could add a workflow, where when a github url is detected but doesn't have a release to allow creating a release from the current commit / HEAD.

For updates you could then check the repo again and validate if the commit has changed.
If changed, init an update.

**Comment by Raina1007** [comment]
> @linaori Are those requirements documented? I've tried everything I can think of in naming a release at https://github.com/Sekkyo/AutoCage and none of it seems to work.

Hey, follow the instructions here on how to get the addon setup correctly, so it can be added to WowUp Hub - https://wowup.io/guide/wowup/hub

**Comment by clery** [comment]
Here's a proposal : how about if an already installed addon isn't found through any provider, we use the informations in the .toc file to see if the author exists on github, and if we find a match for the addon's name ? (Or close match)

For example, that way we could very easily find the MythicDungeonTools addons, from Nnoggie (https://github.com/Nnoggie/MythicDungeonTools).

I suppose it would be possible to try and ensure the repository is an addon, checking for the .toc presence, and for the addon's name within it.
Also, I suppose we could offer a popup for the user to validate, making sure the github repository found is the addon he's looking for ?

What do you guys think ?

**Comment by linaori** [comment]
> Here's a proposal : how about if an already installed addon isn't found through any provider, we use the informations in the .toc file to see if the author exists on github, and if we find a match for the addon's name ? (Or close match)

There's too much guessing here. This process could mark Illegitimate forks as source and that's not desired. If an author wants to expose their releases on github, they can do so with Big Wigs Packager, their own tools, or manually. 

Allowing "install from url" to accept repositories that aren't compatible will just bring more support to us because people won't read the popup and try to install it anyway.

**Comment by clery** [comment]
Sounds fair, thanks for the input
