### ISSUE TITLE
Enabling telemetry on beta clients by default and alternatives

### ISSUE THREAD

**Issue by Plarpoon** [WowUp/WowUp#1063]
I have just switch to the beta-client and realized that the option to enable/disable telemetry is still present.

I think exclusively for the beta client (not release) it would be of essential value to have as much telemetry as possible, therefore adding a popup that will strongly incentivize the users to keep telemetry on should be a great idea.

 As alternative I think simply making it enabled by default should be easier but in that case I would like for the users to be informed about the change to not betray their right to privacy.

Thank you for your time, I hope this idea won't give you peeps too many headaches!

**Comment by jliddev** [comment]
We dont actually collect all that much data via the telemetry, mostly just an overview of what features are used the most so we can see if anyone uses them. In this instance I dont think too much would be gained by forcing it on.
