### ISSUE TITLE
ads

### ISSUE THREAD

**Issue by baka44** [WowUp/WowUp#1089]
we need more ads, cmon

**Comment by linaori** [comment]
Any suggestions how and where? Which ad provider, and what to do with the money? I'm sure @jliddev can use a second yacht

**Comment by jliddev** [comment]
░█████╗░██████╗░░██████╗
██╔══██╗██╔══██╗██╔════╝
███████║██║░░██║╚█████╗░
██╔══██║██║░░██║░╚═══██╗
██║░░██║██████╔╝██████╔╝
╚═╝░░╚═╝╚═════╝░╚═════╝░
