### ISSUE TITLE
DBM install from wago results in broken detection after rescan

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#1095]
**Describe the bug**
When you install the latest DBM from wago, 9.1.27, and then rescan, it ends up breaking the addon in 2, one part from curse, and another from Wago. Possibly a fingerprint issue

**To Reproduce**
1. Install the latest DBM
2. Rescan
3. Witness

**Expected behavior**
The match to take place with 9.1.27 from Wago.

**Screenshots**
![image](https://user-images.githubusercontent.com/1754678/152161414-a83c48d4-ecbb-4329-9785-43f4ba4948a6.png)
![image](https://user-images.githubusercontent.com/1754678/152161581-fed58da2-0ecb-42ab-95be-e19dc878151d.png)
![image](https://user-images.githubusercontent.com/1754678/152161592-b3b3fa1a-b08e-41a2-ab4b-40e0d557127e.png)

**Comment by jliddev** [comment]
Looks like an issue Wago side, DBM-9.1.27 is returning DBM-9.1.26-51-g760f430 for some reason which does not include all the folder that should be in that release.

I have reached out to them to see if they can figure it out.

**Comment by jliddev** [comment]
This should be resolved.
