### ISSUE TITLE
WoW retail addons not found on Linux

### ISSUE THREAD

**Issue by AI-ien** [WowUp/WowUp#1102]
**Describe the bug**
WoW retail addons not found using Linux client. Using Windows client it works just fine. Classic addons are found on both clients.

**To Reproduce**
Add game. Re-scan folders.

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Wayland
 - Gnome 41
 - Version 2.6.1

**Additional context**
Logs does not show anything interesting, just the same, addons not found.

![image](https://user-images.githubusercontent.com/33252703/152702558-5f5cb0c8-f876-4109-a03a-0e5ab3378e70.png)

**Comment by linaori** [comment]
Make sure your addons directory is called `AddOns`, because Linux is case sensitive for directory names

**Comment by AI-ien** [comment]
> Make sure your addons directory is called `AddOns`, because Linux is case sensitive for directory names

That was the case, it was named `addons`, but in anyway, that shouldn't cause a problem. Using case sensitive path in code is not a good practice.

**Comment by linaori** [comment]
`AddOns` is what WoW makes of it, and on Windows and mac this isn't a problem. We could probably patch it in for linux though, PRs are welcome

**Comment by jliddev** [comment]
> > Make sure your addons directory is called `AddOns`, because Linux is case sensitive for directory names
> 
> That was the case, it was named `addons`, but in anyway, that shouldn't cause a problem. Using case sensitive path in code is not a good practice.

Tell that to Linux :D

**Comment by ilu33** [comment]
Case sensitivity is the norm on Linux. Linux users rely on that feature. This should not get patched. Just rename your addon directory correctly.
