### ISSUE TITLE
Cannot switch addon Provider to Wago, when the addon is supported there.

### ISSUE THREAD

**Issue by gheldean** [WowUp/WowUp#1104]
**Describe the bug**
Cannot switch addon Provider to Wago, when the addon is supported there.

**To Reproduce**
1. Go to an addon that is installed that is supported by both Curse and Wago (e.g. Vuhdo)
2. Right click on the addon row
3. Select 'Providers'
4. Confirm that wago is not available.

**Expected behavior**
If an addon is available for a provider (confirmable by searching for it in the Get Addons section), it should be able to be swapped to on the 'My Addons' sections.

**Screenshots**
![image](https://user-images.githubusercontent.com/41842737/153065411-5919b0a6-6974-4a27-b6d3-06acc4a94a0e.png)
![image](https://user-images.githubusercontent.com/41842737/153065478-3543c6f8-fdaa-4521-a108-9f6976b6efd8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - WowUp.io version 2.6.1

**Comment by linaori** [comment]
I can confirm this bug is fixed in #1104
