### ISSUE TITLE
Github pulling should include -bcc.zip file names as well as just -bc.zip filenames

### ISSUE THREAD

**Issue by mikec83** [WowUp/WowUp#1107]
Hello,

I noticed quite a few addons under their tagged releases are using the -bcc.zip suffix inatead of just -bc.zip which wowup seems to be requiring.  It would be nice if -bcc.zip files were included for a bit more flexibility given the new curseforge news.

**Comment by linaori** [comment]
Is this currently broken somewhere? `-bcc.zip` is supported:
https://github.com/WowUp/WowUp/blob/0b66ddb814bfd174f804003e1c3cedf8906853a7/wowup-electron/src/app/addon-providers/github-addon-provider.ts#L382-L384
