### ISSUE TITLE
A master list of github enabled addons would enable browsing of addons distributed through github

### ISSUE THREAD

**Issue by mspk7305** [WowUp/WowUp#1109]
It could be as simple as a list of github urls that the app can scan for version and release info. This would go a long way towards getting people off curse and ease the install process for github sourced addons.

**Comment by torkus** [comment]
@layday of [instawow](https://github.com/layday/instawow) maintains a [github catalogue](https://github.com/layday/github-wow-addon-catalogue). It's also incorporated into [strongbox](https://github.com/ogri-la/strongbox).

**Comment by jliddev** [comment]
In addition to that we have a channel dedicated to this on Discord.
