### ISSUE TITLE
Github pulling should include _tbc.zip file names as well as just -tbc.zip filenames

### ISSUE THREAD

**Issue by Anonomit** [WowUp/WowUp#1110]
Similar to #1107, it would be nice if WowUp would match filenames with underscores as well as hyphens.

This would match the current recommended format found here: https://github.com/Stanzilla/WoWUIBugs/issues/68#issuecomment-889431675

```
- Retail
  1. AddOnName_Mainline.toc
  2. AddOnName-Mainline.toc
  3. AddOnName.toc

- BCC
  1. AddOnName_TBC.toc
  2. AddOnName_BCC.toc
  3. AddOnName-TBC.toc
  4. AddOnName-BCC.toc
  5. AddOnName.toc

- Classic Era
  1. AddOnName_Vanilla.toc
  2. AddOnName_Classic.toc
  3. AddOnName-Vanilla.toc
  4. AddOnName-Classic.toc
  5. AddOnName.toc
  ```

**Comment by linaori** [comment]
I think underscores were already support. In https://github.com/WowUp/WowUp/commit/24032f7eab335eedf60eb5f9341a3a7120635f0e support was added to the zip names though. The toc in here: `WowUp_TBC.toc`

![image](https://user-images.githubusercontent.com/1754678/154802159-3e702de8-9f47-48cb-9e4d-36c0db7edec2.png)

**Comment by Anonomit** [comment]
Perfect, thank you, that change causes the Github pulling to match releases with the formats I would expect.

**Comment by linaori** [comment]
If you want to already use this feature, go to the application options, scroll down, and set the app to beta channel. You can then check for new updates (right bottom) and it will update the app to beta with this fix.
