### ISSUE TITLE
Unable to Install SexyMap via "Install via URL" Button

### ISSUE THREAD

**Issue by crespire** [WowUp/WowUp#1113]
**Describe the bug**
Trying to install TBC Classic SexyMap via URL from: https://github.com/funkydude/SexyMap/releases

**To Reproduce**
Try to add the addon through the URL button. Wowup detects the 9.1.1 version, but does not match for TBC Classic.

**Expected behavior**
Either the button should detect the various packages and select the right one for the version of the game I am managing, or there should be an option for me to specify a package link directly.

**Screenshots**
![image](https://user-images.githubusercontent.com/36272822/154178219-e0c83b4a-558e-4503-af32-f72a8d86ef95.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 97.0

**Comment by jliddev** [comment]
This item is more complex than it seems, due to the release flow that this author uses. Will require some thought.

**Comment by jliddev** [comment]
This should be working as expected in 2.7 beta
