### ISSUE TITLE
Unable to install Loot Resever via Install from URL link

### ISSUE THREAD

**Issue by Raina1007** [WowUp/WowUp#1124]
**Describe the bug**
Unable to install Loot Reserve addon w/ root folder via Install from URL  - 

**To Reproduce**
1. went to https://github.com/Anonomit/LootReserve
2. copy/pasted the above link into the install from url for the version of wow i wanted it for. Clicked on import then install. Wowup shows that it installed. It is in my addons correctly
3. went to interface/addons folder for that specific wow version - sub folders are showing, no root or parent folder - as such WoW isn't aware the addon exists so it doesn't show up in addon window in wow
4.  Can get the parent folder but have to manually download it from within the releases page then move it to the correct interface/addons folder subdirectory for wow

**Expected behavior**
To install the addon with the root or parent folder

**Screenshots**
<img width="563" alt="Screen Shot 2022-02-21 at 6 31 20 PM" src="https://user-images.githubusercontent.com/72997449/155038326-82f864b4-9de3-49cc-9a96-954a7f148887.png">
<img width="944" alt="Screen Shot 2022-02-21 at 6 31 28 PM" src="https://user-images.githubusercontent.com/72997449/155038336-d51c64ba-5c07-4115-bc09-6acea8cd30f2.png">
<img width="613" alt="Screen Shot 2022-02-21 at 6 31 47 PM" src="https://user-images.githubusercontent.com/72997449/155038347-eadc9629-6815-47ad-8636-5e88fe151ca6.png">

**Desktop (please complete the following information):**
 - OS: Mac, Windows
 - Browser - Safari, Chrome, Firefox, 
 - Version - v2.7.0-beta 2 (me), 

**Additional context**
everything is discussed in suggestions channel on discord

**Comment by jliddev** [comment]
This happens because the addon zip is flat packed, which is not currently supported.
