### ISSUE TITLE
Closing the main window does not terminate the application on Linux

### ISSUE THREAD

**Issue by ilu33** [WowUp/WowUp#1126]
**Describe the bug**
There seems to be no regular way to terminate the application and all its children on Linux. All processes are left behind. Tested with v. 2.6.1 and 2.7.0 b2.

**To Reproduce**
Closing the main window by clicking on the "x".

**Expected behavior**
App should close completely and terminate all related processes.

**Screenshot after clicking the "x"**
![WowUp_2022-02-22_05-25-42](https://user-images.githubusercontent.com/12608744/155063665-c3845570-fe8f-4aec-a12a-d7200c789d91.png)

**Desktop (please complete the following information):**
Debian Linux, XFCE

**Possible Fix?**
"A simple solution would be to put process.exit(0) in the win.on('close') event." as suggested here https://github.com/standardnotes/desktop/issues/14#issuecomment-273609119.

**Comment by linaori** [comment]
Do you have any of these options selected?


![image](https://user-images.githubusercontent.com/1754678/155727727-dc08ce02-b9df-4768-b9f6-f2ba0430c6c8.png)

**Comment by ilu33** [comment]
I thought I checked that but - actually yes, I missed one of them. Thanks.
