### ISSUE TITLE
No asset on github error (2.7.0-beta.2)

### ISSUE THREAD

**Issue by ilu33** [WowUp/WowUp#1131]
If the developer doesn't use the expected asset format, the install via URL fails. I'm not sure about the exact reason.

Examples: 
https://github.com/Stanzilla/ClassTimer/releases/tag/2.4.90001.1
https://github.com/Jaliborc/PetTracker/releases/tag/9.0.8
https://github.com/Jaliborc/Blitz/releases/tag/9.1.1
(probably all his addons)
https://github.com/wow-addon/Broker_CurrencyFlow/releases/tag/v1.8.6
https://github.com/xod-wow/LiteMount/releases/tag/9.2.1
https://github.com/TorelTwiddler/CanIMogIt/releases/tag/9.1.5v1.32
https://github.com/alarofrunetotem/GarrisonCommander/releases/tag/3.3.10-beta1

The asset is there but named "Source code" on the release page. This seems to be some default on github. The downloaded file is suitably named though (LiteMount-9.2.1.zip). Maybe take any zip file linked with "Source code" from the release page?

**Comment by jliddev** [comment]
These are not real assets and are not exposed via the GitHub API. You will have to ask the author to create proper releases. 
![image](https://user-images.githubusercontent.com/20467484/155667010-fbaa60e6-42d4-4261-9e1d-c11ac2db4be9.png)

**Comment by ilu33** [comment]
Can you advise on what a "proper release" is? Do you have a link to some sort of docs what WowUp needs? I'd be willing to open issues for those apps but I don't know what to tell them.

**Comment by linaori** [comment]
You can find it under "github" here: https://wowup.io/guide/get-addons/overview

**Comment by ilu33** [comment]
"GitHub the author must have created a tagged release. That tagged release must then contain a packaged zip"
They have tagged releases with a zip file but somehow still did not get it right. No idea what went wrong with their setup.
