### ISSUE TITLE
Reporting SEVERAL addons as not avaible

### ISSUE THREAD

**Issue by N6REJ** [WowUp/WowUp#1137]
**Describe the bug**
why are a BUNCH of addons suddenly marked as ignored stating they aren't accessible, yet curseforge an all oter providers are checked
wago can update them but wowup can't
some like hekili are listed twice

**To Reproduce**
open wow up, scroll down to find MANY on ignore
![image](https://user-images.githubusercontent.com/1850089/155873336-0c24864c-7cfd-4359-aa5a-629c2384e2b2.png)

**Expected behavior**
all addons update as before

**Screenshots**

**Desktop (please complete the following information):**
win 10 x64 pro
Chrome Version 98.0.4758.102 (Official Build) (64-bit)

**Additional context**

**Comment by linaori** [comment]
Does this issue persist after a rescan?

**Comment by N6REJ** [comment]
no, that seems to have fixed that.
The other thing I noticed is hekili is listed twice.
