### ISSUE TITLE
Request: support for lotrointerface

### ISSUE THREAD

**Issue by MrsAngelD** [WowUp/WowUp#125]
Add support for https://www.lotrointerface.com There are very few addons for the game, but it's always been a manual update process. It would be nice to have a way to automate it.

**Comment by idivait** [comment]
https://www.lotrointerface.com/downloads/info663-LOTROPluginCompendium.html - Works for updates from lotrointerface . It's not the most beautiful UI but it works.

**Comment by MrsAngelD** [comment]
> https://www.lotrointerface.com/downloads/info663-LOTROPluginCompendium.html - Works for updates from lotrointerface . It's not the most beautiful UI but it works.

Thanks!

The dev told me to put this request in here because in the future they're looking into possibly supporting other games.
