### ISSUE TITLE
Buttons "ToS" and "Data Consent" in the modal window "Enable Wago.io Provider" are unresponsive.

### ISSUE THREAD

**Issue by rukemn** [WowUp/WowUp#1263]
**Describe the bug**
Buttons "ToS" and "Data Consent" in the modal window "Enable Wago.io Provider" are unresponsive.

**To Reproduce**
1. Go to Options
2. Click on Addons
3. Check the Wago Addon option - an overlayed window opens
4. Click on either of the two buttons ToS / Data Consent

**Expected behavior**
The expected response to the buttons beeing clicked should be to either display the 2 documents in app or open an external browser with the requested information.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: Firefox
 - wowup version : 2.8.2

**Comment by linaori** [comment]
I can confirm this behavior in the latest beta as well 

The links in question:
![image](https://user-images.githubusercontent.com/1754678/170690354-c8958fe2-c05b-4bd3-b9b2-54f5995d810a.png)
