### ISSUE TITLE
WowUp not starting up

### ISSUE THREAD

**Issue by The5kull** [WowUp/WowUp#1274]
When starting the program I am not getting the WowUp window presented. The program is present in task manager (3 times) along with the Updater program. Here I "End task" to kill the program.

The logs:

> [2022-07-04 22:43:07.874] [info]  Main starting
> [2022-07-04 22:43:07.877] [info]  Electron: 18.3.1
> [2022-07-04 22:43:07.878] [info]  BinaryPath: C:\Users\*****\AppData\Local\Temp\2Af2Y6m5XEFogmxQ7v01zJlXAE6\WowUp.exe
> [2022-07-04 22:43:07.878] [info]  ExecPath C:\Users\*****\AppData\Local\Temp\2Af2Y6m5XEFogmxQ7v01zJlXAE6\WowUp.exe
> [2022-07-04 22:43:07.879] [info]  Args [
>   'C:\\Users\\*****\\AppData\\Local\\Temp\\2Af2Y6m5XEFogmxQ7v01zJlXAE6\\WowUp.exe'
> ]
> [2022-07-04 22:43:07.880] [info]  Log path: C:\Users\*****\AppData\Roaming\WowUp\logs
> [2022-07-04 22:43:07.928] [info]  ARGV { _: [], serve: false, hidden: false }
> [2022-07-04 22:43:07.929] [info]  USER_AGENT WowUp-Client/2.8.3-beta.4 (Windows_NT; 10.0.22000; x64;  portable; +https://wowup.io)
> [2022-07-04 22:43:07.930] [info]  Setting default preference: enable_system_notifications -> true
> [2022-07-04 22:43:07.934] [info]  Setting default preference: collapse_to_tray -> true
> [2022-07-04 22:43:07.938] [info]  Setting default preference: use_hardware_acceleration -> true
> [2022-07-04 22:43:07.941] [info]  Setting default preference: current_theme -> default-theme
> [2022-07-04 22:43:07.944] [info]  Setting default preference: wowup_release_channel_2_6 -> 0
> [2022-07-04 22:43:07.948] [info]  Setting default preference: use_symlink_mode -> false
> [2022-07-04 22:43:07.951] [info]  Setting default preference: enable_app_badge -> true
> [2022-07-04 22:43:07.954] [info]  Setting default preference: trusted_domains -> wowup.io,dev.wowup.io,discord.gg,www.patreon.com,github.com,wago.io,addons.wago.io
> [2022-07-04 22:43:07.958] [info]  Setting default preference: acct_push_enabled -> false
> [2022-07-04 22:43:07.962] [info]  Hardware acceleration enabled
> [2022-07-04 22:43:08.250] [info]  App ready: 322ms
> [2022-07-04 22:43:08.252] [error] uncaughtException TypeError: Cannot read properties of undefined (reading 'width')
>     at getWindowConfig (C:\Users\*****\AppData\Local\Temp\2Af2Y6m5XEFogmxQ7v01zJlXAE6\resources\app.asar\app\window-state.js:67:64)
>     at Object.applyWindowBoundsToConfig (C:\Users\*****\AppData\Local\Temp\2Af2Y6m5XEFogmxQ7v01zJlXAE6\resources\app.asar\app\window-state.js:45:19)
>     at createWindow (C:\Users\*****\AppData\Local\Temp\2Af2Y6m5XEFogmxQ7v01zJlXAE6\resources\app.asar\app\main.js:218:17)
>     at App.<anonymous> (C:\Users\*****\AppData\Local\Temp\2Af2Y6m5XEFogmxQ7v01zJlXAE6\resources\app.asar\app\main.js:119:9)
>     at Object.onceWrapper (node:events:510:26)
>     at App.emit (node:events:390:28)
> [2022-07-04 22:44:12.342] [warn]  child-process-gone { type: 'GPU', reason: 'killed', exitCode: 1, serviceName: 'GPU' }

All this on a fresh W11 Pro installation.

**Comment by jliddev** [comment]
This latest beta should fix this issue.
https://github.com/WowUp/WowUp/releases/tag/v2.8.3-beta.6

**Comment by The5kull** [comment]
Working now!
