### ISSUE TITLE
Pihole, wowup and wago.io not working

### ISSUE THREAD

**Issue by TheKrowi** [WowUp/WowUp#1289]
Same as #1246. I tried to look at the link https://discord.com/channels/730098865717379122/761739154026397744/943195768523726890 but that one is dead. Is there another place with information about which stuff to whitelist for it to work?

**Comment by linaori** [comment]
The link is still working fine as long as you're logged into Discord in your browser when you click it. It's the last message in the FAQ channel on Discord if you can't click it.

**Comment by TheKrowi** [comment]
I'm logged in to discord but see the below screenshot. Maybe I need to first join the discord? If so, which server is it?
![image](https://user-images.githubusercontent.com/22818581/187071969-33531e87-0fd9-4265-9845-6394069ab047.png)

**Comment by TheKrowi** [comment]
K, so joining the wowup discord (https://discord.gg/rk4F5aD) makes the link work. Sorry for my stupidity 😅

**Comment by linaori** [comment]
Not your fault, we should probably put this guide on the website on some point as not everyone will have Discord in the first place
