### ISSUE TITLE
"Line" going from top left to bottom right

### ISSUE THREAD

**Issue by m4gnify** [WowUp/WowUp#1296]
**Describe the bug**
Using version [2.9.0-beta.5](https://github.com/WowUp/WowUp/releases/tag/v2.9.0-beta.5)
There is a line going from the top left to top right of the My Addons tab and News tab. I also noticed it is in the Options tab.
It is not present in the Get Addons  tab what I can see.
It moves when you change window size (edge dragging), still going from top left to bottom right.

**To Reproduce**
1. Go to the My Addons or News tab
2. Change the window size until it appears?

**Expected behavior**
No line?

**Screenshots**
![WowUp_CI2cKwcACf](https://user-images.githubusercontent.com/8404962/187931214-90e5a0d0-155d-4e67-a495-70827741e98f.jpg)
![WowUp_3sL5qZrxz7](https://user-images.githubusercontent.com/8404962/187931170-d7dbf072-e72f-47be-b48a-d4a49f400203.jpg)
[WowUp_iSXyxDX4TI.webm](https://user-images.githubusercontent.com/8404962/187931488-ae4c1c27-dd2c-4675-ad64-99b9dfd8de1c.webm)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Thought my monitor was broken at first lol
Haven't tried other beta versions, but it was not there in 2.8.3 from what I have seen.

**Comment by linaori** [comment]
This is a known issue and outside of our control sadly, but it's good to keep track of it

**Comment by m4gnify** [comment]
Is there a list of "Known Issues" that I missed?

**Comment by linaori** [comment]
No, this is just something we ran into and Discussed on Discord

**Comment by jliddev** [comment]
This is an Electron bug of some kind, made a ticket a while ago.
https://github.com/electron/electron/issues/34363

**Comment by m4gnify** [comment]
> This is an Electron bug of some kind, made a ticket a while ago. [electron/electron#34363](https://github.com/electron/electron/issues/34363)

Sadly it doesn't exactly look like it's something they have on their to-do list at the moment

**Comment by kingreboot** [comment]
Same problem, maybe this clean widow might help. 
![Screenshot 2022-09-03 093636](https://user-images.githubusercontent.com/24847320/188280462-e0232208-db77-46d2-84c8-0e2c772f6b1c.png)

**Comment by hibyprime** [comment]
![image](https://user-images.githubusercontent.com/113563379/191570707-bab6db73-fe69-487a-b054-6a47a8c69dce.png)

So this isn't an ideal fix, but removing the border radius on this element appears to remove the line. I think the line is a rendering artifact of that element's border, as it does not act as you'd expect when changing border parameters.  For instance try changing the border radius to 1000px and try to find where the background color comes from. I'm not familiar with this project but I cannot find it, it seems to be bugged.
