### ISSUE TITLE
[WotLKC] Also accept -WOTLKC as file suffix for WotLKC

### ISSUE THREAD

**Issue by frozn** [WowUp/WowUp#1303]
Change
https://github.com/WowUp/WowUp/blob/9bb4dc092624a278bc359e6eb72c815610048ebc/wowup-electron/src/app/addon-providers/github-addon-provider.ts#L437-L439
to
```
  private isWotlk(asset: GitHubAsset): boolean {
    return /[-|_](wotlkc|wrath)\.zip$/i.test(asset.name);
  }
```
to also accept -WOTLKC as file suffix like multiple suffixes are implemented for BCC
https://github.com/WowUp/WowUp/blob/9bb4dc092624a278bc359e6eb72c815610048ebc/wowup-electron/src/app/addon-providers/github-addon-provider.ts#L433-L435

See here for possible suffixes: https://wowpedia.fandom.com/wiki/TOC_format#Multiple_client_flavors

Thanks,
frozn

**Comment by jliddev** [comment]
This was done some time ago. 
https://github.com/WowUp/WowUp/blob/develop/wowup-electron/src/app/addon-providers/github-addon-provider.ts#L427
