### ISSUE TITLE
Unable to install addon via github URL

### ISSUE THREAD

**Issue by mega-watt** [WowUp/WowUp#1310]
**Describe the bug**
Not able to install Details Damage Meters from Github URL:
https://github.com/Tercioo/Details-Damage-Meter

**To Reproduce**
1. Go to Get Addons
2. Click on Install from URL
3. Paste URL "https://github.com/Tercioo/Details-Damage-Meter"
4. Click Install
5. See error ( error.asset_not_found )

**Expected behavior**
Addon installed via github link

**Desktop (please complete the following information):**
 - OS: Windows 10 x86_64
 - Version 2.9.0

**Comment by linaori** [comment]
Details does not have a compatible release strategy on github, see #1245.

You can install details through the Wago provider.
