### ISSUE TITLE
Column sizes in My Addons list

### ISSUE THREAD

**Issue by Takika** [WowUp/WowUp#1315]
I just clean installed current 2.9.0 release on Win10 desktop. After the first restart of the app the columns of My Addons list look like this:
![image](https://user-images.githubusercontent.com/1705821/197970063-0d220b44-9030-47f4-859d-02bb730d11fe.png)

How can I fix this? I can't see any relevant informations of the addons now.

**Comment by linaori** [comment]
There's a bug in the table rendering that has been plaguing WowUp for a while. It's really hard to reproduce, and usually closing the app completely (from tray), and then starting it up again usually fixes it.
