### ISSUE TITLE
Addon install via github URL fails

### ISSUE THREAD

**Issue by lucala** [WowUp/WowUp#1318]
**Describe the bug**
Trying to install from github link gives me an error `ERROR.ASSET_NOT_FOUND`. If the addon is not compliant let me know what the solution is so that I can create an issue on their github.

**To Reproduce**
1. WowUp install from URL
2. Paste `https://github.com/Rycia/azeroth-pilot-reloaded`
3. See error

**Expected behavior**
It should work?

**Screenshots**
![image](https://user-images.githubusercontent.com/14397281/198151326-1f534e0f-82d1-4ce2-8139-a7c1952f650a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - WowUp Version 2.9.0

**Comment by linaori** [comment]
The given repository does not attach the addon in a zip file to the release, therefore it won't work. We should probably update the error message here to hint that this might be the problem.

**Comment by Rycia** [comment]
We don't natively support WowUp, but we'll work on making it happen.

Typically our Github build is meant to be manually installed from releases by dragging the folders into Interface/Addons.
