### ISSUE TITLE
Every addon is listed twice

### ISSUE THREAD

**Issue by YetAnotherDevWannabe** [WowUp/WowUp#1320]
Every addon is listed twice. No idea why. Tried to delete all the wowup folders and start fresh again, same problem.

![image](https://user-images.githubusercontent.com/6054349/198569244-7bb068f2-85c1-47f4-bc7e-41fbccbe625a.png)

**Comment by Cratis1831** [comment]
@YetAnotherDevWannabe try clicking on the rescan button on the top right to see if it resolves the issue

**Comment by YetAnotherDevWannabe** [comment]
I don't have any in the top right, but the one in the bottom right does nothing.
Also I tried deleting all data in the folder and launching again, same result.

**Comment by Cratis1831** [comment]
Click on the 3 vertical dots on top left of the app when you are in the My Addons tab.  It looks like this

![image](https://user-images.githubusercontent.com/1056561/198661598-8e9b27b3-89d5-463c-958d-f1f76179c49c.png)


Then click Rescan

**Comment by YetAnotherDevWannabe** [comment]
Seems to have cleared the problem.
thanks :)
