### ISSUE TITLE
Venture Plan got updated (finally) and is not showing up as an update

### ISSUE THREAD

**Issue by melinerunen** [WowUp/WowUp#1322]
Venture plan got updated since 2022-07-06 and is not being shown as an update in wowup 

https://www.townlong-yak.com/addons/venture-plan

Probably the rest of www.townlong-yak add-ons are not being recognized as an update as well (at least with WarPlan and MasterPlan)

**Comment by linaori** [comment]
TLY addons are not accessible through any API that isn't CurseForge

**Comment by melinerunen** [comment]
Can it be parsed from the release page ( https://www.townlong-yak.com/addons/venture-plan/release ) or is it too much to ask? If not i'll close the issue

**Comment by linaori** [comment]
Scraping html pages is not something we do, but even then is more effort than it's worth.

**Comment by melinerunen** [comment]
awww ok :(
