### ISSUE TITLE
Cannot install "Details!" from git

### ISSUE THREAD

**Issue by Industrial** [WowUp/WowUp#1335]
**Describe the bug**
When adding the `Details!` addon from git you get an error.

**To Reproduce**
1. Go to 'Get Addons'
2. Click on 'Install from URL'
3. Paste in `https://github.com/Tercioo/Details-Damage-Meter`
4. See error `ERROR.ASSET_NOT_FOUND`

**Expected behavior**
Installs correctly from Git.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - WoWUp: 2.9.0

**Comment by Industrial** [comment]
I get the same thing for `https://github.com/nnoggie/MythicDungeonTools`

**Comment by linaori** [comment]
These addons are not attaching their addon zips to releases and are not compatible with WowUp. If you want to install MythicDungeonTools, you can try the new CurseForge version of the app. Details will work there as well. If you prefer Wago, you can install Details through the Wago provider as well.

**Comment by Industrial** [comment]
But I do see zip files in their releases:
- https://github.com/Tercioo/Details-Damage-Meter/archive/refs/tags/DetailsRetail.v9.1.0.8888.145.zip
- https://github.com/Nnoggie/MythicDungeonTools/archive/refs/tags/v4.0.1.4.zip

These are incorrect?

**Comment by linaori** [comment]
These are just the source code zipped up. What's required is an addon zip like on CurseForge, Wago, or WowInterface.
