### ISSUE TITLE
Incorrect software version/Failed to download update

### ISSUE THREAD

**Issue by Jeconti90** [WowUp/WowUp#1339]
Latest download of the WoWup CF 2.9.1. In the app at the bottom right it shows an update available (v2.9.1-beta.8 CF). But checking for updates or telling it to download the update fails. Additionally, checking this github does not show that as an available version. Where did it get this info?

**Comment by Breadwinka** [comment]
https://github.com/WowUp/WowUp.CF/releases/tag/v2.9.1-beta.9

wowupCF is under a different branch in github

https://github.com/WowUp/WowUp.CF/releases

**Comment by jliddev** [comment]
This should be resolved.
