### ISSUE TITLE
Scaling does not stay after restarting WowUp CF

### ISSUE THREAD

**Issue by Raina1007** [WowUp/WowUp#1367]
**Describe the bug**
If you set the scale to something other than 100% then restart wowup.io cf, the font/scaling of the app resets to a 100%, but if you check in options - application, it shows at the scaling you picked prior to restarting the app. The only fix for right now is if your try to manually resize the app, then it goes to the size you set the scaling at prior to the restart. 

**To Reproduce**
1. Go to options - application
2. Click on scaling drop down and set it to anything than 100%
3. Restart WowUp.io CF and whether it is my addons or get addons, it looks like the scaling went back to 100% default. 
4. Check options - application to verify scaling and what it is set to and then try to manually resize app and it will switch to what the scaling is set to at that point. 

**Expected behavior**
To not reset itself back to 100% default after restarting the app

**Screenshots**

**Desktop (please complete the following information):**
 - OS: (Me Macbook - unknown on person in help-me)
 - Browser: N/A
 - Version: WowUp.io CF v2.9.2 - beta.6

**Additional context**
This was first mentioned in help me channel in discord by Grysten

**Comment by jliddev** [comment]
Could be fixed in the latest build

**Comment by Odysseas68** [comment]
I use v2.9.4.beta.3 CF and the scale problem steel exist.
