### ISSUE TITLE
[RESOLVED] WowUp starts minimised.

### ISSUE THREAD

**Issue by themainliner** [WowUp/WowUp#1377]
**Describe the bug**
WowUp starts minimised, I have to right click the notification area icon and select Show.

**To Reproduce**
1. Launch app

**Expected behavior**
It is impossible to change the behaviour in Options | Applications: **Launch WowUp minimised** is greyed out and appears to be in the off position. Couldn't find this option in **preferences.json**.

**Desktop (please complete the following information):**
 - OS: antiX Linux (based on Debian Testing)
 - Browser: Firefox
 - Version: 2.9.2-beta.6

**Comment by jliddev** [comment]
This might actually be fixed in the latest build, had a similar issue on Mac.

**Comment by themainliner** [comment]
Yep! Resolved. Nice work sir.
