### ISSUE TITLE
Uncaught JSON.parse exception at startup

### ISSUE THREAD

**Issue by solargent** [WowUp/WowUp#1383]
**Describe the bug**
I went on a Windows update spree, since I realized I hadn't been getting updates for like a year, and the most recent one I installed (Windows 11 Pro, 10.0.22623 Build 22623) broke my WowUp-CF install.

![image](https://user-images.githubusercontent.com/1126644/209407358-35f22053-6ad6-476a-9926-24fcf2e3426b.png)

I tried to reinstall the latest version (v2.9.2-beta.9) manually, but now I am getting an error similar to the one I was getting back when CF's own client broke on Windows 11 Insider builds.

![image](https://user-images.githubusercontent.com/1126644/209407646-fc8969c1-7bd7-4e2b-9428-7d5eb83d17e1.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro, 10.0.22623 Build 22623
 - Browser: Google Chrome 108.0.5359.125 (Official Build) (64-bit)

**Comment by jliddev** [comment]
Looks like an issue with loading the addons.json file. Could try just deleting/renaming it

located here "%APPDATA%/WowUpCf"

**Comment by solargent** [comment]
Deleting the file seems to have done the trick!
