### ISSUE TITLE
ElvUI Libraries folder shows up after a rescan folders in wow

### ISSUE THREAD

**Issue by Raina1007** [WowUp/WowUp#1384]
**Describe the bug**
If you rescan folders in WowUp and have ElvUI addon installed, ElvUI Libraries folder shows up and its ignored. This was found in our discord help me channel by HardKullez

**To Reproduce**
1. Install ElvUI addon - doesn't matter which version of wow
2. Click on rescan folders in my addons
3. Scroll down until you see ElvUI libraries folder being displayed and it should show as ignored

This was tested after the TukUI team added back the missing information in the toc that was breaking how the addon displayed. The main folder ElvUi and ElvUI Options are not affected, just ElvUI Libraries. I found a partial workaround by adding the Project ID from the ElvUI main folder toc to the ElvUI Libraries toc. When I did this had to reinstall it one time after (the project id stayed) then after that I could rescan as often as I wanted and it wouldn't break how it displayed.

**Expected behavior**
For ElvUI addon to not break during a rescan folders

**Screenshots**

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Version: my version is v2.9.2-beta 9 

**Additional context**
I'm unsure why the ElvUI Library folder is the one that breaks in how the ElvUI addon is displayed in my addons or why adding the project ID to the ElvUI library toc file worked, but something was not setup right in one of the toc files to cause this or the API is seeing the ElvUI library folder as a separate addon that it doesn't have info for thus wowup showing as that

**Comment by HardKullez** [comment]
Seems to be fixed. No such behavior on v2.9.2-beta 11, now works as expected
