### ISSUE TITLE
Add in Projectfolders as another way to check during rescan folders - ElvUI request

### ISSUE THREAD

**Issue by Raina1007** [WowUp/WowUp#1396]
**Is your feature request related to a problem? Please describe.**
During a rescan folders if ElvUI is installed, one folder - ElvUI Libraries breaks in how its displayed or not in My Addons. After trying to find a solution, a suggestion was made by AcidWeb - General Chat - to include X-Tukui-ProjectFolders as another thing that is checked during Rescan folders

**Describe the solution you'd like**
For ElvUI addon to not break how its displayed in My Addons during a Rescan Folders

**Describe alternatives you've considered**
Unknown - attempt was made to add the Project ID to every Toc file in ElvUI and its subfolders, but ElvUI Libraries keeps breaking in how it is displayed regardless during a rescan folders

**Additional context**
See chat for steps that were done to find a workaround/fix in discord - general

**Comment by jliddev** [comment]
Rescan appears to work as expected with elvui 13.17+.

Is this still an issue?

**Comment by Raina1007** [comment]
After testing it, looks to be fixed. Closing ticket.
