### ISSUE TITLE
WowUp doesn't see current addon version

### ISSUE THREAD

**Issue by jimkillian** [WowUp/WowUp#1406]
**Describe the bug**
After updating an addon with CurseForge, WowUp still sees the old version and says it needs to be updated. The new version listed is the one that's actually currently installed.

**To Reproduce**
1. Use CurseForge app to update an addon.
2. Open WowUp
3. See that the updated addon still shows the old version as installed and the new version available is the one already updated to by CurseForge.
4. Click "Check Updates" button and see that nothing changes.

**Expected behavior**
WowUp _should_ see the addon version that's currently installed.

**Desktop (please complete the following information):**
 - OS: Win 10 x64
 - Browser Firefox 109.0 64-bit
 - Version WowUp 2.9.3

**Comment by jliddev** [comment]
This is a non-supported action. WowUp will not scan your file system unless you tell it via the re-scan button.

**Comment by jimkillian** [comment]
Thanks. I didn't realize that option was there. Expected it to check the addons when it starts up.

**Comment by jliddev** [comment]
Yes we try to avoid scanning all the things again just to save some startup time.

**Comment by jimkillian** [comment]
Maybe make this an option for the user? I'd prefer having it take a few more seconds to open and then give me the real current status rather than what the app remembers it being from the last time it was run. Default it to the current process if you want, but let me choose how I want it to work.

Thanks!
