### ISSUE TITLE
Both local and remote Game Version

### ISSUE THREAD

**Issue by tomasforsman** [WowUp/WowUp#142]
Feature Request:
The Game Version collumn could either show both remote and local gameversion or split the column in two.
8.3.0 -> 9.0.1

**Comment by jliddev** [comment]
I guess I dont understand why this would be useful.

**Comment by andrewschott** [comment]
This is useful when you have to peg to an old version of an addon becuase of a bug.  Nice to know when the proper fix rolls out.  

For example if you have $Addon version 1.2.1 that works.  1.2.2 breaks things.  Its nice to be able to wait until 1.2.3 rolls out so one can update to that and in the meantime not have a broken addon.

Although rarer these days, it still does happen.  Had alot of it for Classic, and a few that were wonky on Legion and BFA up thru the first month or so.  As you are very well aware - bugs suck.

**Comment by tomasforsman** [comment]
What happened for me was two things that made me request it. First was that I was waiting for 9.0.1 alpha and I had a community fixed version for 8.3.0. The second was that I had a community fix for a version from one of the sites (curse or wowinterface) and the other one had another naming convention (for some reason). It kept asking me to update but if I did it broke the fix.

It could also be in the Latest Version column: v185.3 (9.0.1)

If it feels like it is clutter for most people it could be an optional thing.

**Comment by jliddev** [comment]
We're going to show only the installed game version, as the remote one is unreliable.
