### ISSUE TITLE
Installing from a GitHub URL doesn't fetch the latest version

### ISSUE THREAD

**Issue by Kaukov** [WowUp/WowUp#1486]
**Describe the bug**
I've imported a few addons from GitHub that aren't released on Wago/WowUpHub. However, importing some addons doesn't fetch their latest version.

One such addon is [Demodal](https://github.com/nezroy/DeModal). The current latest version is 0.8.1, but WowUp always chooses to install 0.8.0. Even after installing it and checking for an update, it says it's up to date.

**To Reproduce**
1. Go to "Get Addons"
2. Click on "Install from URL"
3. Paste the URL "https://github.com/nezroy/DeModal"
4. Click on "Import"
5. It offers to download version 0.8.0 instead of the latest 0.8.1

**Expected behavior**
I would expect to be able to download the latest release from GitHub.

**Screenshots**
![Screenshot 2024-08-19 091829](https://github.com/user-attachments/assets/40643673-5816-427e-8413-0bda876e1d6d)
![Screenshot 2024-08-19 091855](https://github.com/user-attachments/assets/34a9fc6e-2088-4ac8-89e3-878042e69f2c)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Browser: Firefox 129.0.1
 - Version: v2.12.0

**Additional context**
The other addons I've installed via GitHub had their latest version installed without an issue.

**Comment by linaori** [comment]
If you expand the 0.8.0 you will see a specific ZIP attached, that's the file that wowup needs. The Source code is not sufficient to install as addon for most addons and cannot be relied upon.
![image](https://github.com/user-attachments/assets/7ecd7e80-3c6e-4ba2-9739-405ac445c979)
