### ISSUE TITLE
2.20.0 beta doesn't show any data from CurseForge

### ISSUE THREAD

**Issue by cremor** [WowUp/WowUp#1487]
**Describe the bug**
After updating from WowUp.CF 2.12.0 to 2.20.0-beta.2 no data from CurseForge is shown any more.
Already installed addons don't show anything in the description or changelog tabs in their detail dialogs.
Searching for new addons doesn't return any results from CurseForge.

**To Reproduce**
1. Install WowUp.CF 2.20.0-beta.2
2. Check the detail dialog of any addon already installed from CurseForge
3. Try to find a new addon to install from CurseForge

**Expected behavior**
Data from CurseForge should be shown.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: not relevant
 - Version: 2.20.0-beta.2

**Additional context**
Downgrading to 2.12.0 fixes the issue.

**Comment by linaori** [comment]
Work in progress, new beta release should be available soon

**Comment by ncoghlan** [comment]
A likely related symptom: running "Re-Scan Folders" in v.2.20.0-beta.1 CF to fix the game API display issue reported in #1466 resulted in all CurseForge addons getting marked as "Unknown Provider".

(There was some good news in that, though: I was still able to confirm that #1466 is fixed via some affected WoWInterface addons)

**Comment by linaori** [comment]
Searching and getting info/changelog is working again in beta-3.
