### ISSUE TITLE
Missing CF Addons

### ISSUE THREAD

**Issue by argent-codes** [WowUp/WowUp#1491]
**Describe the bug**
I wanted to install [HandyNotes: The War Within](https://www.curseforge.com/wow/addons/handynotes-the-war-within), but a **Get Addons** search didn't show it at all. I ended up installing it with the CurseForge client itself, but then WowUp failed to display it in **My Addons**. I was also able to install it from URL, though I am not sure if this is going to have any side effects. I believe this has happened with other CF addons in the past too, but I can't recall specific examples.

**To Reproduce**
1. Go to 'Get Addons'
2. Search for 'HandyNotes: The War Within'
3. Observe the addons missing from the list

**Expected behavior**
I should be able to search for and install HandyNotes: The War Within.

**Screenshots**
![image](https://github.com/user-attachments/assets/4017d695-32f7-45da-836c-5442e3dac320)

**Desktop (please complete the following information):**
 - OS: [Windows 11[
 - Browser [N/A]
 - Version [2.20.0]

**Additional context**
N/A

**Comment by linaori** [comment]
We're stuck with the CF api to search for addons, it's listed though: 
![image](https://github.com/user-attachments/assets/e328cb71-e408-4331-b800-d98d396a5c91)
