### ISSUE TITLE
[2.x] Installer removing windows pinned shortcut when updating

### ISSUE THREAD

**Issue by jliddev** [WowUp/WowUp#176]
https://github.com/electron-userland/electron-builder/issues/2514

https://github.com/electron-userland/electron-builder/pull/5312

**Comment by mrchops1024** [comment]
What's the plan for this? From the info you provided, we either:

1. Wait for that PR to be merged, and upgrade electron-builder OR
2. Set `createDesktopShortcut` to false and let users create their own desktop shortcut if they want one

**Comment by jliddev** [comment]
I'll wait, i assume most users prefer the desktop shortcut

**Comment by linaori** [comment]
PR got merged 5 hours ago: https://github.com/electron-userland/electron-builder/pull/5312

**Comment by linaori** [comment]
Fixed!
