### ISSUE TITLE
Not recognising the Collect Me addon

### ISSUE THREAD

**Issue by Walkerbo** [WowUp/WowUp#193]
I have the Collect Me addon installed however WoWUp does not list it in my installed addons.
https://www.curseforge.com/wow/addons/collect_me

It does list in the Get Addons list.
<img width="1405" alt="Screenshot 2020-10-21 120221" src="https://user-images.githubusercontent.com/35990554/96660795-421ab200-1396-11eb-857e-c44240d1694a.png">

**Comment by Zonk1987** [comment]
Not only this if you look at this with the red border ![index](https://user-images.githubusercontent.com/25836879/96912271-606dd400-14a2-11eb-9255-8af3a6a6a3f7.png)


Greetings

**Comment by jliddev** [comment]
Can you go to options, and then show log files and send me your latest renderer.log from the alpha?

**Comment by Zonk1987** [comment]
[renderer.log](https://github.com/jliddev/WowUp/files/5431632/renderer.log)

here we go i hope this helps :)

**Comment by jliddev** [comment]
Several fingerprint api fixes have been done since this, is it still happening?

**Comment by Zonk1987** [comment]
Yes to be honest there is a difference between the number of addons 

fresh
[renderer.log](https://github.com/jliddev/WowUp/files/5492450/renderer.log)

![Screenshot_40](https://user-images.githubusercontent.com/25836879/98206970-335a0080-1f3b-11eb-8737-4cdc0ac75bbc.jpg)

**Comment by jliddev** [comment]
Can you identify one or two that are not being found?

**Comment by Zonk1987** [comment]
CurseForge Beta 112 Addons:

- Azeroth Auto Pilot
+ BtWQuests: Shadowlands Prologue
- CopyPaste2
- ElvUI (it is also clear why)
- HandyNotes: Shadowlands
- InputLagFix
+ TradeSkillMaster_AppHelper
- Unlimited Map Pin Distance


Twitch Client 111 Addons:

- Azeroth Auto Pilot
- BtWQuests: Shadowlands Prologue
- CopyPaste2
- ElvUI (it is also clear why)
- HandyNotes: Shadowlands
- InputLagFix
+ TradeSkillMaster_AppHelper
- Unlimited Map Pin Distance


WowUp 114 Addons:

+ Azeroth Auto Pilot
- BtWQuests: Shadowlands Prologue
+ CopyPaste2
+ ElvUI (it is also clear why)
+ HandyNotes: Shadowlands
+ InputLagFix
- TradeSkillMaster_AppHelper
+ Unlimited Map Pin Distance

+ means this addon is in the list 
- means this addon is not in the list

I hope you understand this XD

**Comment by jliddev** [comment]
Sorry for slow reply
BtWQuests: Shadowlands Prologue doesnt show up as its own addon because its bundled with BTWQuests.

![image](https://user-images.githubusercontent.com/20467484/99914611-27549980-2cc4-11eb-9316-e1aaf1d92e5d.png)

TradeSkillMaster_AppHelper seems to be detected fine when installed via WowUp
