### ISSUE TITLE
Failed to scan from WowInterface

### ISSUE THREAD

**Issue by Walkerbo** [WowUp/WowUp#204]
When I re-scan folders I get a popup error; failed to scan from WowInterface.
<img width="215" alt="Screenshot 2020-10-23 110744" src="https://user-images.githubusercontent.com/35990554/96942179-1e837300-1520-11eb-9bbf-41e20b3a5dd7.png">

**Comment by jliddev** [comment]
Typically that only happens if you are unable to connected to WowInterface. Feel free to go to the Options tab and click the show log files button at the bottom and pate that here.

**Comment by Walkerbo** [comment]
[wowup-logs20201025.txt](https://github.com/jliddev/WowUp/files/5433968/wowup-logs20201025.txt)
[wowup-updater.log](https://github.com/jliddev/WowUp/files/5433969/wowup-updater.log)

**Comment by ChasimX** [comment]
I have the same issue.  However, if it matters, I am only using three AddOns which are exclusive to WoWInterface - one which is actually only a Beta release and two which are "Outdated and Discontinued Mods".  I did try changing the default channel to Beta (to see if it picked up the Beta release on WoWInterface), but I received the same message/error.

**Comment by jliddev** [comment]
Please give the beta a try, its got a bunch of fixes that 1.x does not have.

**Comment by ChasimX** [comment]
Thank you for the message.  I now have 2.0.0-beta.4 installed and it still is not showing my AddOns from WoW Interface.  Notably, I only have 3 and 1 of them is not Outdated/Discontinued.  The "active" one is https://www.wowinterface.com/downloads/info11831-DockingStationDisplay.html.  It currently only has Beta releases but, even when I select the default channel for Beta, it simply doesn't show up in Wowup.

Thanks.


Bill Chambers

________________________________

**Comment by jliddev** [comment]
Hmm, I tried installing it from the website and it seemed to be found by the scan. Have you tried hitting re-scan folders?

![image](https://user-images.githubusercontent.com/20467484/98330211-81184c80-1fbf-11eb-9ac8-258203df5009.png)

**Comment by ChasimX** [comment]
I'm stumped.  I have tried Re-Scan Folders multiple times and it still does not show up.  I have even tried completely uninstalling (down to registry entries) and re-installing and it does not show up.  Also, when I select Get Addons, nothing shows up from WoW Interface, only Curse and TukUI.  I can Install from URL and then it shows up in My Addons.  It stays even when I restart the program, but if I Re-Scan Folders it disappears.

Thanks.


Bill Chambers

________________________________
