### ISSUE TITLE
[2.x] WowInterface Game Version Blank

### ISSUE THREAD

**Issue by jliddev** [WowUp/WowUp#205]
WowInterface api does not return the Game Version (9.0.1) from the API. So when doing a fresh install from Get Addons it is blank. To do this you'd have to wait for install to finish, rescan that addon and pull the value from the primary folder's toc.

Maybe do it before you copy the zip file over to lower the chance of reading the wrong folder.

**Comment by linaori** [comment]
Fixed via #483
