### ISSUE TITLE
[Feature Request] Consume less vertical space per line

### ISSUE THREAD

**Issue by Barracuda666** [WowUp/WowUp#247]
It would be great if the lines could be way smaller, like maximum half or better 1/3 of current.
Its alot of wasted blank space that makes me scroll like crazy.

Thank you.

**Comment by strayge** [comment]
* `Current version` can be shown as column (before `Latest version`)
* Images now too small for being informative, looks like they can be hidded
* Font size a bit more than optimal (on FHD resolution)

**Comment by linaori** [comment]
> Its alot of wasted blank space that makes me scroll like crazy.
> Font size a bit more than optimal (on FHD resolution)

You can scroll with the mouse wheel (limited min/max) or use `ctrl +` and `ctrl -` to change the zoom (unlimited min/max). The zoom value should be saved when exiting the app. For me the zoom at fhd at 100% is just fine (including font size), though I can imagine you might be better off with something smaller or bigger.

Information density will always be something that's hard to get right for everyone. For me personally if everything would be smaller and tighter, I'd get lost in the density. I'm not sure decreasing the size of the rows will really help everyone here.

> Current version can be shown as column (before Latest version)

Not sure if there's space for this. Maybe on bigger screens it will work fine, if you have a smaller screen or use the window without maximizing it, the amount of columns will cause a horizontal scroll wheel. Is there any particular reason you want this in a separate column? If anything I'd much rather see the "latest version" be less verbose in here so we can save a column. This value is only important if there's a new version available and you'll already find these through the update button.

> Images now too small for being informative, looks like they can be hidded

I rather have the images displayed, as some icons are very distinctive and helps me find addons much faster than reading text.  

Perhaps the same approach as with gmail can be taken in the future to solve the density issue? 
![image](https://user-images.githubusercontent.com/1754678/97786823-79ffd180-1bae-11eb-8eac-31083d377b80.png)

**Comment by strayge** [comment]
> You can scroll with the mouse wheel (limited min/max) or use ctrl + and ctrl - to change the zoom (unlimited min/max).

Wow. Limited zoom out is not enough, but with 2 additional zoom outs it much more useful. Thanks!  
A bit more user-friendly option for this will be very helpful.

> Information density will always be something that's hard to get right for everyone. 

That's true.
But now I'm installed and comparing `WowUp` vs `Ajour`.
At the same window size `WowUp` can show only 9 addons vs 17 in `Ajour`.
9 addons at the time and 3 full window scrolls to down is a not very comfortable.
As its often needed to one top view to all installed addons for decision if any action is actually required.
![image](https://user-images.githubusercontent.com/2664578/97787387-e389db00-1bc2-11eb-8170-f4b4d1312771.png)

I agree, that with ability to decrease scale it looks much more better and with current density.

> Not sure if there's space for this. 

User can hide useless (for him) columns (really miss this option on `Get Addons` tab).  
For me its `Released At` and `Provider`.  
Unfortunately, at `2.0.0-beta.1` choosed columns resets on restart.

>  Is there any particular reason you want this in a separate column?

For get rid of second text line (or 3rd with long addon names).  
Also with two versions numbers (if they different) one to one is much easier to compare them.

> I rather have the images displayed, as some icons are very distinctive and helps me find addons much faster than reading text.

Looks like that I have wrong addons.  As for me most of them is just screenshots (which is useless in that size)
![image](https://user-images.githubusercontent.com/2664578/97787853-b1c64380-1bc5-11eb-809c-dad95e064eda.png)

> Perhaps the same approach as with gmail can be taken in the future to solve the density issue?

Yes, it's should be good (I have `Compact` mode in gmail).  

But at least
1. Ability to select scale in `Options` with minimum lower that current limit
2. Persist selected columns on restart

should be quite enough for the first time.

**Comment by Barracuda666** [comment]
Thanks for your answer and your time.
I cannot CTRL scroll  or CTRL+/- change anything. nothing happens.

I totally get your point, but all those line wheres not even shown anything, look:


![image](https://user-images.githubusercontent.com/27134216/97788213-9bb18680-1bb7-11eb-9e8f-edd3fcb97d0e.png)

**Comment by linaori** [comment]
AH that's 1.x, if you take a look at what Strayge posted, you'll see what it looks like in in the new version.

**Comment by strayge** [comment]
@Barracuda666 yes, for `2.0.0-beta1` `ctrl+<+/->` works well.

**Comment by Barracuda666** [comment]
Ah sweet sorry for that. i now went to the beta (my virus scanner committed suicide for me overriding his warnings)

But now i get this, WAY better, but my point is still valid:
but now concrete: 
1)Option to remove image
2)Option to put the 2nd line into column

![image](https://user-images.githubusercontent.com/27134216/97788412-fc8d8e80-1bb8-11eb-80b3-0d240cdfc878.png)


BTW: Thank you TONS for your time and effort.

**Comment by strayge** [comment]
@linaori what if show current addon version and installed version in the same column?

* if they equals - shown only one number.
* otherwise - show 2 lines: current and latest.

This approach allows:
* hide duplicated versions
* show old and new versions close to each one for easier comparing
* long addon names (at small window size) will be use only 2 line instead of 3.
* addon names will not visually mix with versions (easier to read at first glance)

**Comment by linaori** [comment]
> But now i get this, WAY better, but my point is still valid:
> but now concrete:
> 1)Option to remove image
> 2)Option to put the 2nd line into column

Removing the image could actually be part of a "compact mode", but wouldn't solve the 2 line issue in the "Addon" column. Currently as far as I know, there are some other ideas/designs that actually use the version number underneath it, so that would have to be changed as well.

If I understand it correctly, the idea of having this as a column is to spot the from -> to upgrades easier? 

>linaori what if show current addon version and installed version in the same column?
>
>  -  if they equals - shown only one number.
>  -  otherwise - show 2 lines: current and latest.

Yes something like that, and possible even changing the color of the new version to something green? I think that would be doable. I personally don't see the need for having the latest version in its own column, I much rather see it merged into where the current version is, though having both in the "Latest version" column and renaming it to something like "version" could also be a possibility. 

I'm not sure if you already know this feature. When right clicking the columns you can hide them if you want. The only issue is that both sorting/selecting are not persisted and will be reset in the next version. 
![image](https://user-images.githubusercontent.com/1754678/97788640-ba654c80-1bba-11eb-9d3e-b00e8e9aae6f.png)

**Comment by strayge** [comment]
> If I understand it correctly, the idea of having this as a column is to spot the from -> to upgrades easier?

Yes. Also for moved it away from addon name (for easier reading list of names).

> I'm not sure if you already know this feature. When right clicking the columns you can hide them if you want. The only issue is that both sorting/selecting are not persisted and will be reset in the next version.

Yes.  
What about allow hide/show image in the same menu (as any other column)?

**Comment by jliddev** [comment]
its likely we'd implement this as part of the 'themes' ticket as a condensed theme

**Comment by jliddev** [comment]
If someone wants to create a new theme for condensed feel free. there are now example themes in the app.
