### ISSUE TITLE
[2.x] Missing Dependency Issue

### ISSUE THREAD

**Issue by Cratis1831** [WowUp/WowUp#257]
If Library knows what the main addon folder/package is

Add to context menu a "Fix Dependency Issue" then have it trigger a delete on the Lib(s) and reinstall the addon

**Comment by jliddev** [comment]
This might be good as a context menu item?

**Comment by jliddev** [comment]
test

**Comment by jliddev** [comment]
I dont really understand the context of this anymore lol
