### ISSUE TITLE
[2.x] WoWup doesnt appear to Tray even after i minimazed but it stays open in the backround apps.

### ISSUE THREAD

**Issue by ForgottenCrusader** [WowUp/WowUp#307]
Just what the tittle says, if i try to reopen it from desktop it continues where i left it off,
![Screenshot_1](https://user-images.githubusercontent.com/73822136/97850439-b3465780-1cfc-11eb-9f96-31dc88135c31.png)
![Screenshot_2](https://user-images.githubusercontent.com/73822136/97850441-b3deee00-1cfc-11eb-8dd4-8a068e54724e.png)

**Comment by jliddev** [comment]
What version of WowUp are you using?
What version of Windows is this?

**Comment by ForgottenCrusader** [comment]
2.0 beta 1
windows home version 2004

> What version of WowUp are you using?
> What version of Windows is this?

**Comment by jliddev** [comment]
Unable to duplicate this so far :/

**Comment by mrchops1024** [comment]
@ForgottenCrusader Is this still happening on beta 4?

**Comment by ForgottenCrusader** [comment]
Yes unfortunatelly, i deleted and reinstalled too but still the same :/

**Comment by iStreit** [comment]
I am having the same issue. Upgraded from the stable version to Beta4 and now the program is not showing in the tray at all. Working fine in the stable version.

**Comment by iStreit** [comment]
Update: The bug is still happening in beta5. But I think I narrowed down the issue. If I change the setting "Current Language" from "system default" to "English" then the tray icon starts to work. I am running Windows 10 Pro with Danish Language pack.

**Comment by jliddev** [comment]
Interesting. Can you send me your main log file. You can find it by going to options > debug > show log files

**Comment by iStreit** [comment]
[main.log](https://github.com/WowUp/WowUp/files/5508607/main.log)

**Comment by ForgottenCrusader** [comment]
Can confirm, after changing langiage from System language to English the icon appears, My system language is in Greek.

**Comment by jliddev** [comment]
Give this a try in the latest beta 7

**Comment by iStreit** [comment]
I can't seem to test it, since once I changed from "System Language" to "English" then the option for "System Language" is no longer in the list to choose.

**Comment by jliddev** [comment]
I think the only way to reset it would be to go to preferences.json and delete the selected_language line

**Comment by iStreit** [comment]
I have tried doing that. But it just adds it with the line again with "en" again when I start the program up afterwards.

**Comment by jliddev** [comment]
If the tray icon is still causing an issue feel free to reopen this
