### ISSUE TITLE
Addon updates not resolving correctly

### ISSUE THREAD

**Issue by Vavictus** [WowUp/WowUp#321]
I've reinstalled and tried to get this issue to correct itself, but I have a list of addons that show that they need updating, but anytime I click update all or individually click it, it just cycles and still shows that it needs to be done. I'll attach a snip showing the issue. Any help would be greatly appreciated, and i apologize if someone else has already posted this. I just couldn't find it elsewhere here.
![wowup1](https://user-images.githubusercontent.com/41553272/98059317-c9473b80-1e14-11eb-89c3-380f782b8134.JPG)

**Comment by mrchops1024** [comment]
You'll want to move to the [2.0 beta](https://github.com/jliddev/WowUp/releases/tag/v2.0.0-beta.2) that's currently available.
