### ISSUE TITLE
[2.x] auto-updater does not respect portable app

### ISSUE THREAD

**Issue by strayge** [WowUp/WowUp#331]
Auto updater on windows portable version installs new version to system.

Steps to reproduce:
1. download `WowUp-2.0.0-beta.1.exe` to any folder
2. run it (it runs without install, used temporary directory)
3. click on update icon - after app restart started new version
4. close app and start `WowUp-2.0.0-beta.1.exe` again - started `beta.1` version

Result:
* new version installed to system
* previous executable file runs old version 

Bad UX patterns:
1. user still got non-updated version if he try to start app the same way as before
2. portable app installed to system which is totally inconsistent with portability

**Comment by jliddev** [comment]
may have to read further if there's anything to do with this https://www.electron.build/

**Comment by mrchops1024** [comment]
Looks like it may be possible to avoid using the updater in a portable environment: https://github.com/electron-userland/electron-builder/issues/3282

**Comment by strayge** [comment]
> Looks like it may be possible to avoid using the updater in a portable environment

or updater should just download new portabale version

**Comment by jliddev** [comment]
I am not opposed to trying PORTABLE_EXECUTABLE_DIR on windows only and sending the user to GitHub or whatever to download the update. but it's not worth building a whole updater flow for something we dont actively promote
