### ISSUE TITLE
[2.x] [Feature request] Ability to remove addons from "Get Addons" tab

### ISSUE THREAD

**Issue by strayge** [WowUp/WowUp#334]
Since #301 it's a bit inconsistence to not have ability to uninstall addons from `Get Addons` without switching to `My Addons` tab.

For me it looks like UX should be similar for both tabs.

**Comment by jliddev** [comment]
Someone is free to make  PR for this, but i dont think i want to undertake it for now.

**Comment by johnlawsharrison** [comment]
@jliddev On it

**Comment by jliddev** [comment]
This is now possible via the details dialog on the get addons page.
