### ISSUE TITLE
Library Management

### ISSUE THREAD

**Issue by yoshimo** [WowUp/WowUp#356]
Addons can either package libraries like  Libstub for example and ship them in a subfolder or depend on them being installed by other Addons and standalone.

1) It would be nice if you could highlight addons with outdated libraries that are availble in an updated version so you can ping the addon author to update them
2) Detect the dependencies between the addon and libs so that you can
3) Purge Libraries that are no longer in use
4) see which addon depends on which other addon

**Comment by jliddev** [comment]
Seems like you'd need the ability to install no-lib versions before this could be worked out?
