### ISSUE TITLE
[2.x] [Feature Request] Allow filtering by 'Provider'

### ISSUE THREAD

**Issue by mrchops1024** [WowUp/WowUp#359]
This would potentially allow someone to filter by provider, and then select all to either ignore or set auto-update.

**Comment by jliddev** [comment]
This seems unnecessary when you can already sort the column by provider?

**Comment by mrchops1024** [comment]
I don't disagree, just opened this up from the conversation on another PR. Feel free to close if it won't be implemented.

**Comment by jliddev** [comment]
It was more of a do you think this would solve that need question

**Comment by mbryantII** [comment]
I am looking for a way to exclusive limit functionality based on a provider for example. lets say I dont want to use.. WoWAce as a provider, I would like the ability to remove that component for any automated looks (either refresh, update all, etc... ) it's a better user experience if you can filter out completely and use the other functionality within the application.

sort works okay, it just adds more burden to the user every time they try to use the application

**Comment by jliddev** [comment]
This should be handled by #317
