### ISSUE TITLE
Remove the affix requirement from GitHub zip files

### ISSUE THREAD

**Issue by akaij** [WowUp/WowUp#36]
I can't use the `Install from URL` feature because [the addon I'm trying to import](https://github.com/Aviana/LunaUnitFrames) doesn't use the expected `-classic` affix in the zip filename, and I'd suspect it's not the only one. Removing it would be great!

**Comment by jliddev** [comment]
Just to comment on this. Larger GitHub integration is a large task that im actively working on but it will not be built into the client. The client will just hook into the existing API to enable this.
