### ISSUE TITLE
maintain window position on restore

### ISSUE THREAD

**Issue by stevietv** [WowUp/WowUp#362]
There seems to be some strange behaviour about where app restores to from system tray.
I use wowup on my second monitor and fully maximised. Its set to start up on boot as minimized.

When restoring the first time after boot it restores maximised to monitor 1, even though it was last active on monitor 2.
When minimizing to tray from monitor 2 and then restoring it restores to half size in middle of monitor 2. the maximize button then doesn't work and it needs to be maximised by double clicking the title bar

**Comment by mrchops1024** [comment]
What version are you experiencing this on?

**Comment by stevietv** [comment]
I was on 2.0.0-beta.4
just did the update to beta.5 and it appears to be playing nice.

**Comment by jliddev** [comment]
We did update to the latest electron, maybe that was it.

**Comment by stevietv** [comment]
I'm continuing to get this issue, on a reboot of my PC WowUP restores to my main monitor and not where it was last open.

**Comment by jliddev** [comment]
Can you go to options -> Debug -> Show Logs and send your main.log?

**Comment by stevietv** [comment]
[main.log](https://github.com/WowUp/WowUp/files/5522522/main.log)

I booted up around 08:00 this morning.

**Comment by stevietv** [comment]
as a follow up. when I shut down wow up and restart it without restarting my PC it restores to the correct place.
However If Wowup is running in the system tray when the computer is shut down, first my second monitor goes off and windows executes the shutdown on the primary monitor, I have the feeling that the window state is then being saved on the basis of the primary monitor.

**Comment by mrchops1024** [comment]
@stevietv Can you do a test for me? Place the window where you want it. Make a copy of your preferences.json file in C:\Users\<username>\AppData\roaming\wowup. Do a shutdown and record the timestamp. After bootup, make another copy of the preferences.json file and record the timestamp. Post the data like this:

prefereneces.json BEFORE

shutdown timestamp

prefererences.json AFTER

startup timestamp

main.log

**Comment by stevietv** [comment]
[preferences.json.txt](https://github.com/WowUp/WowUp/files/5532738/preferences.json.txt) BEFORE

shutdown timestamp: 20:11

[preferences.json after.txt](https://github.com/WowUp/WowUp/files/5532743/preferences.json.after.txt) AFTER

start up timestamp: 20:12

[main.log](https://github.com/WowUp/WowUp/files/5532746/main.log)


however this time it restored to the right place. Its not consistent.

Steps I can do to make it bug out:

1. set window to unmaximized and place anywhere on monitor 1.
main window state becomes:
```
	"main-window-state": {
		"width": 1198,
		"height": 598,
		"x": 296,
		"y": 152,
		"isMaximized": false,
		"isFullScreen": false
	},
```

2. drag window to second screen with title bar and drag in the same motion to top of screen so that Windows automatically maximises it.
main window state becomes:
```
	"main-window-state": {
		"width": 1198,
		"height": 598,
		"x": 296,
		"y": 152,
		"isMaximized": true,
		"isFullScreen": false
	},
```

isMaximized is set as true, but x and y coords are not set

3. shutdown wowup via taskbar icon

4. startup wowup - starts on main monitor maximised when it was shutdown on second monitor maximised.

conclusion - x,y coordinates should be set also when window is maximised.

**Comment by jliddev** [comment]
Is this fixed?

**Comment by stevietv** [comment]
yep, closing
