### ISSUE TITLE
Addons Provided by Curse not being detected for Classic.

### ISSUE THREAD

**Issue by ramma** [WowUp/WowUp#367]
I just downloaded v2.0.0-beta.5 and noticed only WowInterface was showing as a Provider in my addons list with a significant number of addons missing despite terminal output suggesting all addons were scanned. I downloaded v2.0.0-beta.4 and it scanned all the addons just fine showing Curse as the provider for most as expected.

I also tested my retail install with both of those versions and while there was a slight difference in the number of addons detected, there was no issue with detection of Curse provided addons for retail in either version.

Of note, I'm on Linux (Ubuntu 19.04), so this may be related to #348 in some way, but since some addons are still showing for me a new issue seemed appropriate.

**Comment by jliddev** [comment]
feel free to go to options -> debug -> show log files. and send me your latest logs

**Comment by ramma** [comment]
[main.log](https://github.com/WowUp/WowUp/files/5544034/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/5544035/renderer.log)

**Comment by jliddev** [comment]
Looks like its likely some kind of path related issue since Linux is case sensitive. The issue is likely due to a casing mismatch from an addon author. could you give me a list of your classic addons and we can try to figure out which one it is?

**Comment by ramma** [comment]
Sure thing. It's a pretty big list, and a couple addons don't have classic versions (Routes for instance), but work with small changes.

[addons.txt](https://github.com/WowUp/WowUp/files/5544493/addons.txt)

**Comment by jliddev** [comment]
Could you try this again in 2.0 release? there's new logging around scanning I wonder if it will tell us more. I went thru your list of addons but was unable to replicate the issue. i did find some other unreleated bugs tho :D

**Comment by ramma** [comment]
Curse is showing as a provider in the 2.0 release! Only thing of note is some addons are missing from the scan, but I think they're packaged with other addons and I'm just not remembering which at the moment. Thanks a ton!

**Comment by jliddev** [comment]
glad its working :)
