### ISSUE TITLE
Make use of multiple providers for better UX

### ISSUE THREAD

**Issue by yoshimo** [WowUp/WowUp#368]
Not every addon author uploads to every platform at the same time.
Sometimes certain meta data like categories, changelog, images, intended wow version for the addon, downloads,  interface version , whatever can be parsed better from a certain hoster.
Please make sure that the best provider for the data is used and the most recent version offered.

**Comment by jliddev** [comment]
We are not going to combine data from multiple sources, it would make the process wildly complicated.
