### ISSUE TITLE
Use caching for updating multiple installations

### ISSUE THREAD

**Issue by yoshimo** [WowUp/WowUp#369]
Dedicated players can have multiple copies of wow, retail, ptr, beta, classic, (upcoming btc, wotlk, mop, wod, BFA, Legion realms)
Very often addons are shared across these installations, because not every update breaks the api compatibility.
For now it seems like WowUp downloads the same addon package and version again when i switch to updating another wow folder with the same interface version.
Not everyone has a big fibre connection, therefore caching the download/copying over the files from an existing installation would save traffic and can be faster.

**Comment by linaori** [comment]
I think I've seen this suggestion come by a few times now. I think we could implement an caching for downloads with a configurable "up to X MB", or plainly disable it.

**Comment by yoshimo** [comment]
If you are concerned about disk space and the version detection works well, a simple copy from retail to ptr addon folders and vice versa could be used too.

**Comment by jliddev** [comment]
This is probably more trouble than gain to be honest.
