### ISSUE TITLE
[2.x] wowup taking a long time to load up?

### ISSUE THREAD

**Issue by panoplybez** [WowUp/WowUp#378]
I've noticed with beta 8 that when I try to open wowup from the taskbar pin, sometimes it doesn't initialize, or it takes close to 15 seconds before it opens a window, or shows the logo screen for 10+ seconds. 

If I open it from the desktop shortcut to the exe, it sits on the logo screen (with no visible animation in case there's supposed to be some) for 10+ seconds, and in one case never loaded up at all, and I had to kill it and try again. 

I am making sure that I check in Task Manager that there are not any stale wowup processes before I launch. It has 7 windows items running on startup, which drops to 4 after it finally loads in the addon list:

![image](https://user-images.githubusercontent.com/52841691/98590617-17d55980-229d-11eb-84ef-aa82ff5ef9e5.png)

Maybe this is normal, just wanted to mention it in case.

**Comment by jliddev** [comment]
takes about 3 seconds to load on my machine so im not sure. nothing changed with the app startup.

**Comment by panoplybez** [comment]
So, I 'fixed' it by turning off Hardware Acceleration in the options. Now its nice and speedy.

**Comment by panoplybez** [comment]
Of course, I say that, and now its more like 1 in 3 launches it will lag. Spose that's better haha.

**Comment by panoplybez** [comment]
I still can't figure this out, but it keeps happening with each beta (on the latest now). Is there any kind of logging or something I could enable and look at for wowup?

**Comment by linaori** [comment]
Could it be a virus scanner of sorts interrupting?

**Comment by panoplybez** [comment]
I don't have a virus scanner, just built in windows defender really. And it wasn't doing this on the 1.x version. I tried to set this as 'Run as Administrator' as well, but doesn't seem to help.
