### ISSUE TITLE
[2.x] Ignored Addons are still being updated in the background using "Update All" button

### ISSUE THREAD

**Issue by Cratis1831** [WowUp/WowUp#379]
This item was updated when pressing the "Update All" button.

If you look at the "Update At" column it states "Just Now"

![image](https://user-images.githubusercontent.com/1056561/98669459-6a575a00-231f-11eb-9859-68ef99a997d8.png)

You can also see the folders were indeed updated

![image](https://user-images.githubusercontent.com/1056561/98669592-94a91780-231f-11eb-924d-3369497ec8d8.png)

**Comment by jliddev** [comment]
This should be fixed in the next beta
