### ISSUE TITLE
[2.x] Application is taking disk space just from being open (up to gigabytes!)

### ISSUE THREAD

**Issue by sampaiodias** [WowUp/WowUp#385]
It seems that WowUp is taking disk space just from being open, taking more and more MB the longer the process stays alive. I noticed this on beta-5 when there was some gigabytes being used on my SSD when I didn't really install or download anything big recently. I closed WowUp by chance and got more than 5gb of free space back (!!!).

**Comment by jliddev** [comment]
What platform are you on? How are you seeing that it's WowUp causing this? Can you check the memory usage of WowUp?

**Comment by sampaiodias** [comment]
I'm running WowUp on Windows 10 (10.0.18362). I know it was WowUp because I checked the current disk space on My Computer and it was at like 56ish gb (me: "that really odd, gonna investigate later"), and purely by chance I opened WowUp to updated my addons my it was frozen. I closed it, refreshed the My Computed window, and the disk space was updated.

At the moment WowUp (beta-9) is running for a few minutes at 45,5mb of RAM. When this issue happened, it was at beta 5, it was running for a few days I guess but I don't know about RAM usage.

**Comment by sampaiodias** [comment]
One thing to notice, I've been trying to test the auto-update feature recently (both individually and globally). MAYBE there is some correlation.

**Comment by jliddev** [comment]
Are you running the portable version or the installed version?

**Comment by sampaiodias** [comment]
Installed version

**Comment by jliddev** [comment]
I was unable to replicate anything like this leaving it open all day with 5 second auto update time :/

**Comment by sampaiodias** [comment]
I'm currently on beta-9, WowUp consuming 14mb of RAM, left it running for around a day, and just like you it didn't affect my disk space this time. Well, if this is something fixed on a previous version, something much rarer to happen, or just some other random thing that happened at the same time I had this issue... well, if I ever notice this is going on again I'll grab some logs and send you a message.

**Comment by jliddev** [comment]
Feel free to reopen if you get any more clues.
