### ISSUE TITLE
Menu Provider improvements

### ISSUE THREAD

**Issue by vmwinckler** [WowUp/WowUp#387]
In the same way that there is the option to select the channel for stable, beta or alpha through the popup menu, If the installed addon exists with the same name in other sources (curse, tukui and wowinterface) then it would be possible to change the source directly through the menu .

For greater precision it would be possible to make it available for the user to check "this source belongs to addon X" in the tab to find new addons when he finds the same addon in another source but with a difference in the name, this happens a lot, mainly with re-publications in the tukui addons course.

Edit: I find menu "Provider". 👍

**Comment by vmwinckler** [comment]
![image](https://user-images.githubusercontent.com/1237277/99670438-4d253880-2a4f-11eb-9ab9-c90d94549cde.png)
**Perfect**

**Comment by vmwinckler** [comment]
![image](https://user-images.githubusercontent.com/1237277/99670828-e9e7d600-2a4f-11eb-94da-2d5861f8a399.png)
But don't work for Tukui Providers

**Comment by Cratis1831** [comment]
@vmwinckler Tukui doesn't have multi providers, which is why there is no menu for it.  the ones that have multi providers have this icon. 

![image](https://user-images.githubusercontent.com/1056561/99671112-940b3200-2a3f-11eb-9410-e2fb2a4d0655.png)

**Comment by vmwinckler** [comment]
![image](https://user-images.githubusercontent.com/1237277/99671234-84481980-2a50-11eb-98de-3fadb37e34cf.png)
They actually exist, only in Curse they receive an addendum to the name

**Comment by linaori** [comment]
Looks like TukUI is not discovered. Maybe it's not possible to detect the same addon on TukUI. I expect these addons to detect different provider, but I can't say if that's possible to detect by wowup in the current iteration

**Comment by Medoke** [comment]
MerathilisUI is on TukUI and Curse, and detected.

**Comment by vmwinckler** [comment]
#450

**Comment by jliddev** [comment]
Multi provider was implemented, currently if you want TukUI support the author has to put a link to it in the toc like so X-Tukui-ProjectID
