### ISSUE TITLE
Bugs and Improvements with WoWInterface

### ISSUE THREAD

**Issue by vmwinckler** [WowUp/WowUp#388]
![image](https://user-images.githubusercontent.com/1237277/98834499-09627b80-241e-11eb-9511-5758834813db.png)
Addons from WowInterface have a bug in the "Updated in" and "Game Version" columns, I believe you can find the source of the data or how to get to them at [](https://api.mmoui.com/v3/game/WOW/filelist.json) and filtering with `https://api.mmoui.com/v3/game/WOW/filedetails/ "+ id +" .json`

Perhaps with this information it is possible to implement even the search in Wowinterface without the need to send the entire URL.

**Comment by vmwinckler** [comment]
![image](https://user-images.githubusercontent.com/1237277/98834387-e8018f80-241d-11eb-9ceb-0f587228e7c0.png)

**Comment by vmwinckler** [comment]
![image](https://user-images.githubusercontent.com/1237277/98839651-927cb100-2424-11eb-8ab5-5b6b2dea5d82.png)
Now i can't update...

**Comment by vmwinckler** [comment]
![image](https://user-images.githubusercontent.com/1237277/99669632-20245600-2a4e-11eb-96f4-b1253f75516e.png)

**Comment by vmwinckler** [comment]
I believe it may be due to the size of the package, it may be causing timeout or something like that.

**Comment by vmwinckler** [comment]
#103

**Comment by jliddev** [comment]
Can you verify if these are still issues? changes were made to fix these.
