### ISSUE TITLE
Do you accept contributions?

### ISSUE THREAD

**Issue by arphox** [WowUp/WowUp#390]
Hi!

I just noted this addon manager and wondering if you accept contributions for this repository.

If yes, I recommend creating a [CONTRIBUTING](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors) file.

I am a C# developer myself and I am open for contributing.

**Comment by jliddev** [comment]
I have added a contributing file on the dev branch good idea :)
