### ISSUE TITLE
[2.x] Changing the language to Spanish sets it to English instead.

### ISSUE THREAD

**Issue by SkollVargr** [WowUp/WowUp#391]
I've noticed WowUp can't be set to Spanish since beta 9. When you switch from any other language to Spanish the app changes to English and the "Current language" field in the options also shows it's set to English.

The rest of the languages work properly, even the ones that don't have a translation yet, the "Current language" field shows the language you chose.

I've tried in 2 different computers, the other one didn't have WowUp 2.0 installed previously.

P.S.: In the program folder I've also noticed a weird "es-419.pak" file in the "locales" folder.

**Comment by jliddev** [comment]
Looks like theres a missing comma in the es.json. will fix and redeploy

**Comment by jliddev** [comment]
Beta 11 should be fixed

**Comment by SkollVargr** [comment]
Yes, it's fixed, thanks.
