### ISSUE TITLE
Border around window prevents easy closing of application

### ISSUE THREAD

**Issue by MarkFl12** [WowUp/WowUp#393]
The border that is around the entire window causes the top right most pixel of the window when maximised to not be part of the close button. This means the usual behaviour of a sweep up to that corner and a click doesn't close the application.

1. Open Application
2. Maximise it
3. Sweep the cursor into the top right hand corner of the screen
4. Click
5. Should close, but doesn't

 - OS: Windows 10
 - Version 1.19.1

**Comment by linaori** [comment]
This is fixed in 2.0 🎉 
![image](https://user-images.githubusercontent.com/1754678/98858349-bf4eb980-2460-11eb-97d2-474addc1e29c.png)

**Comment by MarkFl12** [comment]
Excellent, any idea when we'll see a release?

**Comment by linaori** [comment]
You can download the 2.0-beta from the website
