### ISSUE TITLE
[2.x] Disable unwanted provider

### ISSUE THREAD

**Issue by TopoDiFogna** [WowUp/WowUp#396]
**Is your feature request related to a problem? Please describe.**
Enable the user to choose providers as they like

**Describe the solution you'd like**
By default enable all available providers so the application behaves as  always but let the users be able to disable some of them if they don't want to use them

**Describe alternatives you've considered**
No alternatives since alla providers are enabled and cannot be disabled ina any way if not changing the code.

**Additional context**
Sometimes when addons are detected, some of them are detected twice due to different name in different providers.
![image](https://user-images.githubusercontent.com/8290162/98926690-ebf1e800-24d7-11eb-8f9b-13102e3fca68.png)
In the above image dbm warlord of draenor and legion(not showed) appear 2 time due to name and version mismatch between providers

**Comment by linaori** [comment]
This change is currently in the works. It will let you change where addons can be found/installed from with a list: #317. Would this be sufficient?

**Comment by TopoDiFogna** [comment]
Yes, this is what I meant! Thank you!

Il gio 12 nov 2020, 11:58 Lynn <notifications@github.com> ha scritto:

**Comment by jliddev** [comment]
Duplicate of #83
