### ISSUE TITLE
[2.x] Unable to install addon from github URL: "https://github.com/Aviana/LunaUnitFrames"

### ISSUE THREAD

**Issue by pedro-cf** [WowUp/WowUp#397]
Unable to install addon from github URL: "https://github.com/Aviana/LunaUnitFrames"

Error Message: 'No Release assets found in https://github.com/Aviana/LunaUnitFrames'

**Comment by jliddev** [comment]
Seems to work fine on 2.x

**Comment by pedro-cf** [comment]
> Seems to work fine on 2.x

![2020-11-12 19-07-00](https://user-images.githubusercontent.com/4175430/98984921-bcb09a80-251a-11eb-9025-ce34836c8d0b.gif)

**Comment by jliddev** [comment]
This is the URL? https://github.com/Aviana/LunaUnitFrames

![lcRKVWmIuS](https://user-images.githubusercontent.com/20467484/98985709-9292b480-24e9-11eb-85cf-ec08d03ec717.gif)

Feel free to send your renderer.log file

**Comment by pedro-cf** [comment]
Yes that is the same URL.

[renderer.log](https://github.com/WowUp/WowUp/files/5533227/renderer.log)

**Comment by jliddev** [comment]
very odd, will add some extra logging around this for the next beta so we can see whats up

**Comment by pedro-cf** [comment]
Any luck? Still can't install it in the current version. Here's recent debug files.
[main.log](https://github.com/WowUp/WowUp/files/5545650/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/5545651/renderer.log)

**Comment by strayge** [comment]
@jliddev wowup awaits `-classic.zip` for classic wow

**Comment by sylcai** [comment]
I am unable to install HeroRotation from their github.

https://github.com/herotc/hero-rotation/

I want to switch to the github release, as they are way faster than curse.

**Comment by jliddev** [comment]
@strayge good eye. @pedro-cf He is right, since this is a classic addon the release must end with -classic thats the issue i was installing it to retail. It is a current limitation of the github support.

**Comment by mrchops1024** [comment]
@sylcai That repository doesn't have a packaged release. In order for WowUp to install the addon, it needs to have a release. See this repo for an example: https://github.com/teelolws/Altoholic-Retail/releases/tag/9.0.1-032

Reference: https://wowup.io/guide/section/get-addons/install-from-url

**Comment by SulpherStaer** [comment]
@mrchops1024 
Please tell me what this link is then: https://github.com/herotc/hero-rotation/releases/tag/9.0.1.15

**Comment by pedro-cf** [comment]
Still unable to install  https://github.com/Aviana/LunaUnitFrames  on classic ?

It has releases https://github.com/Aviana/LunaUnitFrames/releases

No way to solve?

**Comment by pedro-cf** [comment]
> Oooooh this is for classic. Would've been very valuable information to add in your initial post. For classic the asset needs to end with `-classic.zip`.

So in order for this to work the owner of the addon would have to change the folder name? No other way around it?

**Comment by jliddev** [comment]
The current import by url logic is fairly basic, in order to prevent you from having to download the zip and dig through the toc we require classic addons on github to have -classic at the end.

**Comment by Aviana** [comment]
You could extend your algorithm to try for https://raw.githubusercontent.com/Username/AddonName/master/AddonName.toc and read the toc number ;P

**Comment by linaori** [comment]
That's a very flaky way of detecting it, because not everyone uses "master". "develop" is also commonly used, perhaps "classic" when people do provide a classic branch next to retail, and github recently changed the default name to "main". On top of that, there's no requirement to have it placed in the root of your repository, so that's another assumption that can easily prove wrong.

**Comment by Aviana** [comment]
And changing the URL and breaking peoples bookmarks is not a good solution either.

**Comment by linaori** [comment]
I don't expect people to bookmark a download link. Checking the latest version, this is: `https://github.com/Aviana/LunaUnitFrames/releases/download/4030/LunaUnitFrames.zip`, the tag name is in the actual asset so it's not something you'd want to bookmark as you're always getting the same version in that scenario. The only thing that needs to happen (as mentioned above), is that `LunaUnitFrames-classic.zip` is made available.

**Comment by Aviana** [comment]
My mistake. I thought you had to change the entire repository. I guess you can close this now.

**Comment by linaori** [comment]
For future references, maybe there's something we can design to standardize this, like a metadata file in the github assets that can be read? This bridges more than just wowup though, so it's not something we can just toss in. @jliddev is there something you see of value in this, or do you have plans on handling this in a different way?

**Comment by jliddev** [comment]
we're working on a way to standardize this server side we're just not there yet. It's non trivial to figure out what is what on GitHub because every author does things a little differently. The client code is very basic in what it does as to not use up the user's GitHub api quota.
