### ISSUE TITLE
ver 2.x freezes when trying to update addons

### ISSUE THREAD

**Issue by whizzed** [WowUp/WowUp#399]
**Describe the bug**
WowUp 2.x Windows portable version completely freezes when trying to update any addons.

Some additional info:
- 100% reproducible for any Curse-hosted addons.
- It downloads the archive, manages to create a 'bak' folder for the addon, a new folder for the updated addon, copies some (but not all files into the new folder), then the freeze happens.
- I've tried removing everything from the AppData folders and starting from scratch, didn't help.
- Removed and re-added addons from the search tab and from the links. The initial install works, then any subsequent updates fail.
- It has been going on since 2 beta 5 or so
- Version 1.9 works fine
- Windows 10 20H2

**To Reproduce**
- Download the app and unzip it.
- Launch the app
- Press Update button on the main list for any addon that has an update

**Comment by rear-ammonia** [comment]
Oh, the logs don't seem to contain anything unusual. Let me know if I could provide any additional info.

**Comment by jliddev** [comment]
does your wow folder require admin permisisons or something?

**Comment by whizzed** [comment]
No, nothing like that. 1.9 portable seems to be able to write there. Even 2.x writes some files before the freeze
