### ISSUE TITLE
App crashes when trying to install new addon from Search

### ISSUE THREAD

**Issue by Tequima** [WowUp/WowUp#402]
**Describe the bug**
Tried 3 times now to install some extra modules for RareTracker and each time WoWUp has crashed after I clicked the Install button.

**To Reproduce**
1. Click on Get Addons
2. Type RareTracker in Search
3. Maximise window to see all the addons
4. Click on Install button for any of the 3 modules I do not yet have installed (see screenshot & URLs below)
[RareTrackerWorldBosses](https://www.curseforge.com/wow/addons/raretrackerworldbosses-rtwb)
[RareTrackerIcecrown](https://www.curseforge.com/wow/addons/raretrackericecrown-rti)
[https://www.curseforge.com/wow/addons/raretracker-rt](https://www.curseforge.com/wow/addons/raretracker-rt)

**Expected behavior**
Package to be installed

**Screenshots**

![2020-11-13 wowup](https://user-images.githubusercontent.com/54499085/99068625-c2eb5900-25a4-11eb-95f5-a737330ea684.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version  86.0.4240.193 (just updating now)

**Additional context**

**Comment by linaori** [comment]
This bug most likely won't be fixed in 1.x. You can download 2.0-beta from the website and is stable enough to be used instead of 1.x. This bug is not present in 2.0 anymore

**Comment by Tequima** [comment]
This is now working. Many thanks!
