### ISSUE TITLE
Auto Sort Addons Needing Updated to Top

### ISSUE THREAD

**Issue by bolerro** [WowUp/WowUp#405]
**Is your feature request related to a problem? Please describe.**
Currently in v2 Beta 11, the sort is based on whatever column is being chosen as the preferred sort method. So this makes seeing when an addon needs updated difficult if sorted by name and possibly some other sort methods.

**Describe the solution you'd like**
Whenever an addon needs updated, no matter the sort method, it should always be listed at the top until it has been updated or ignored.

**Describe alternatives you've considered**
I believe if this is implemented, an alternative method would not be needed. However it would be possible that having a 'show all updates' button could work.

**Additional context**
While there is the option to 'Update All', not everyone wants to do this and would prefer to see what changes have been made beforehand. This is another reason why having new updates auto-filter to the top is beneficial.

**Comment by linaori** [comment]
Closing this in favor of #472, as a discussion has started there
