### ISSUE TITLE
Tell user what mods were just auto-updated (enhancement request)

### ISSUE THREAD

**Issue by designadrug** [WowUp/WowUp#407]
I love that WowUp will auto update mods and tell me in the Win10 'notification panel' - this is +great+. But it doesn't tell me *what* has been updated. Sometimes you just want to know that an update to Details! just went in. Or you may be waiting for an update to mods that you have disabled because it is still broken in-game and it'd be good to know you can turn-in back on.

A tab that keeps a chronological list of what got updated would be nice. Having the info in the 'notification panel' would be cool too. Perhaps a column in the MyAddons Tab with "last updated" might help.

Thanks in advance; you all freaking rock.

**Comment by jliddev** [comment]
Added in 2.1.0-beta.2

**Comment by designadrug** [comment]
Thank-you! <3
