### ISSUE TITLE
Show Game Version

### ISSUE THREAD

**Issue by Spoony36** [WowUp/WowUp#410]
Am i missing something as your screenshots on your website show when addons were released in the 'get addons' section 

![image](https://user-images.githubusercontent.com/6922184/99150545-46807500-268d-11eb-9b14-d6758f8cffc8.png)

but for me this doesn't show so i am unsure what game version i am installing addons for

![image](https://user-images.githubusercontent.com/6922184/99150524-2355c580-268d-11eb-89de-4cc40c3a223a.png)

**Comment by Spoony36** [comment]
Scrub that, saw it was a beta version :)

**Comment by Spoony36** [comment]
But a nice feature would be to be able to filter out results, so for example i could untick a box that says TUKUI and it wouldn't show me any addons from that source

**Comment by linaori** [comment]
For "get addons", that will be implemented via #317
