### ISSUE TITLE
Set Language dosnt work

### ISSUE THREAD

**Issue by Zonk1987** [WowUp/WowUp#412]
I Updated to the latest version (v2.0.0-beta.12) and tried to set my language to "German" but this dosnt work for me.

1. Update to v2.0.0-beta.12
2. WowUp started already with the german settings but nothing is german beside the "Deutsch" in the dropdown in the Application Options
3. switched to english  
4. restart
5. switch back to german 
6. restart
7. nothing happens everything is english

![Screenshot_42](https://user-images.githubusercontent.com/25836879/99154811-ed2b3c80-26b2-11eb-9b49-9a9bdcd5b63c.jpg)
![Screenshot_43](https://user-images.githubusercontent.com/25836879/99154816-fe744900-26b2-11eb-87ae-bc44b3f5d666.jpg)

**Desktop :**
 - Windows 10
 - Google Chrome
 - 86.0.4240.198

**Comment by gpexio** [comment]
I can confirm German is not properly applied (was it before this version?). Chinese, Korean and Norsk too are not working ( i have no info if they were working before this version tho.)

**Comment by Zonk1987** [comment]
in the previous version i had german

**Comment by Medoke** [comment]
#413 fixes it.

**Comment by gpexio** [comment]
Thank you mr .Divine Rapier
