### ISSUE TITLE
No matching theme

### ISSUE THREAD

**Issue by Zazou89** [WowUp/WowUp#414]
**Describe the bug**
Few elements don't match with the theme

**To Reproduce**
1. Set Horde or Alliance
2. Change language

**Screenshots**
![image](https://user-images.githubusercontent.com/206181/99155605-b278d280-26b9-11eb-9b37-ef5e11df59d1.png)

![image](https://user-images.githubusercontent.com/206181/99155613-befd2b00-26b9-11eb-968b-5831a8765a13.png)

**Desktop (please complete the following information):**
Version 2 Beta 12 on Windows

**Comment by linaori** [comment]
Not all elements are themed yet. Here's a few more:
![image](https://user-images.githubusercontent.com/1754678/99155681-67ab8a80-26ba-11eb-8993-1b4bdcecbecb.png)
![image](https://user-images.githubusercontent.com/1754678/99155630-e05e1700-26b9-11eb-8169-7ce779b290cf.png)
![image](https://user-images.githubusercontent.com/1754678/99155643-01bf0300-26ba-11eb-8036-28c3bc6a413b.png)
![image](https://user-images.githubusercontent.com/1754678/99155648-13080f80-26ba-11eb-88ee-17891b477357.png)

**Comment by NoobTaco** [comment]
I took a stab at the addon menu popup but am hitting a wall on over riding the angular check, and radio buttons. I did change the filter box on the My Addons page to reflect the color pallet for the theme however.

**Comment by jliddev** [comment]
This should be fixed in 13

**Comment by NoobTaco** [comment]
@jliddev It's not. I worked on it all day yesterday. Its due to the model popups not adhering to the themes primary color setting. They are taking the default themes settings. As I fell asleep, I think I may have come up with the solution. Going to work on it this morning.

**Comment by jliddev** [comment]
I did it check 13

**Comment by NoobTaco** [comment]
Ahh. Ok, I just rebased and it does look fixed in develop. I tested yesterday with the release bin. It is still showing v12. Looks like it did not update the build binaries?

![image](https://user-images.githubusercontent.com/1172935/99189407-e1bd2d00-2715-11eb-808e-99ecd7858fb3.png)

**Comment by NoobTaco** [comment]
Looks like my issue was trying to run the client WHILE I had left on the option to minimize to tray. Once I killed 12 13 does indeed launch and does indeed fix the bug.

👍
