### ISSUE TITLE
A light theme

### ISSUE THREAD

**Issue by tinkspring** [WowUp/WowUp#420]
**Is your feature request related to a problem? Please describe.**

I suppose I'm in a minority, but I use most applications with a light theme, I find those considerably easier on my eyes.

**Describe the solution you'd like**

It would be amazing if WowUp had a light theme, to match the rest of the apps I have.

**Comment by jliddev** [comment]
Added light theme support in beta 14 give it a shot

**Comment by tinkspring** [comment]
Oooh, it looks fantastic, thank you!

Closing this issue, since the theme's there and works like a charm.
