### ISSUE TITLE
[2.x] Scrolling issue in the "Options"-tab

### ISSUE THREAD

**Issue by Taizunz** [WowUp/WowUp#421]
**Describe the bug**
In 2.0.0-beta.13 the scrollbar doesn't work on the "Options"-tab.
Using the scroll wheel while hovering the mouse on the right side of the window while in the "Options"-tab doesn't work either.

**To Reproduce**
1. Be on WowUp version 2.0.0-beta.13
2. Go to Options
3. Try dragging the scrollbar while in the "Clients" section of Options. (This issue is also present if the window is small enough for a scrollbar to be visible in the "Application" section.)
4. Try using the scrollwheel on your mouse while hovering your mouse over the right side of the window, or while hovering your mouse over the scrollbar.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 (19041.508)

**Comment by jliddev** [comment]
Should be fixed
