### ISSUE TITLE
Automatically ignore working copies

### ISSUE THREAD

**Issue by niketa-wow** [WowUp/WowUp#427]
**Is your feature request related to a problem? Please describe.**
It's more of an inconvenience if anything. For addon developers, we have to manually go through all of our addons and ignore them to be sure that our working copies aren't overwritten if we choose update all. It's made me hesitant to utilize auto update on addons. My concern would be if I don't notice that I hadn't ignored one of my addons and I'm working on development while it auto updates before I've had a chance to commit my changes, I may lose progress.

Granted, the probability of this happening, I even think is very low. Maybe 1%. BUT, it's more of a peace of mind thing. Also any time I decide to make a new addon, it's just very inconvenient to have to go ignore it since I've been used to that being done automatically.

**Describe the solution you'd like**
I'd like working copies to be automatically recognized and ignored for updates, such as how it worked in the previous Twitch updater. The client is already showing that the installed version is @project-version@, so I imagine you could just look for this to recognize working copies.

**Describe alternatives you've considered**
I suppose just ignoring them manually like I am now. 

**Additional context**
Example of how it's shown in the new CurseForge client (which I don't like and am trying to get away from, hence why I'd love to see this change on this app).
![image](https://user-images.githubusercontent.com/58258335/99213267-c7756480-2792-11eb-812c-01b9e85e2b84.png)

**Comment by speedwaystar** [comment]
this is an essential feature and when i discovered it was missing, i immediately uninstalled WoWUp and very reluctantly went back to the Overwatch client.

the old Curse client, the Twitch client, and the Overwatch client all detect(ed) and support development versions of addons.

here, for instance, is how the Overwatch client deals with my edited version of Mendleev which was last updated to work with WoW 7.0.3 but which I have kept working for years with my own patches.

!(https://i.imgur.com/gH2Ay0p.png)
!(https://i.imgur.com/G6cyoBe.png)

**Comment by jliddev** [comment]
Move to #71
