### ISSUE TITLE
Addon changelog display

### ISSUE THREAD

**Issue by Zazou89** [WowUp/WowUp#430]
**Is your feature request related to a problem? Please describe.**
View addon changelog on WowUP? 

**Describe the solution you'd like**
Displaying changelog in the popup. Maybe here ?
![image](https://user-images.githubusercontent.com/206181/99257210-f6cdb500-2816-11eb-8a4c-be7154b2be46.png)

**Comment by linaori** [comment]
This feature is very much wanted and will be worked on as soon as there's some time

Duplicate of #93 and #54

**Comment by Zazou89** [comment]
Woops sorry
