### ISSUE TITLE
Addons being forgotten, not re-found.

### ISSUE THREAD

**Issue by CMcFadyen** [WowUp/WowUp#434]
WowUp previously correctly found and updated TurnIn (https://www.curseforge.com/wow/addons/turn-in) but it's missing now and a re-scan won't find it.  I've attached my logs from a re-scan today.

[wowup-logs20201116.txt](https://github.com/WowUp/WowUp/files/5550618/wowup-logs20201116.txt)

**Comment by jliddev** [comment]
Seems to work fine in the latest beta

**Comment by CMcFadyen** [comment]
Re-scanning after updating to beta 19 didn't find it, but deleting it, re-installing it and re-scanning it did find it.  Further re-scans don't appear to be removing it from my addon list anymore.  Looks fixed.
