### ISSUE TITLE
Provider menu not working with Overachiever

### ISSUE THREAD

**Issue by Neosaro** [WowUp/WowUp#450]
**Describe the bug**
I have an addon named "Overachiever", currently with provider Curse.
It shows me there's multiple providers. If I right click it shows me only WowInterface.

**To Reproduce**
1. Overachiever addon installed
2. Right click Overachiever entry
3. Put mouse over provider

**Expected behavior**
A menu with:
- Curse
- Wowinterface

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: ?
 - Version: 2.0.0-beta.16

**Additional context**
Installed version: v.1.1.1
Curse version: v.1.1.1
WowInterface version: v.1.0.9

Tried reinstall, and uninstall-install of the addon but not success

If I try to switch to WowInterface, it uninstalls and reinstalls (as expected), downloads v.1.0.9 (expected), but then WowUp doesn't 'see' the two providers.

Other addons with multiple providers, show more than one provider. It's just that one.

**Comment by Zonk1987** [comment]
I can confirm and in the menu the provider is not translated to german language in version 2.0.0-beta.17.

http://prntscr.com/vl6hbu

**Comment by jliddev** [comment]
This is due to a mismatch between the toc file on WowI and the toc file from CF. i addded some code to kind of sync those up. should be working in beta 18

**Comment by Zonk1987** [comment]
i checked it in beta 18 and it works for me but the translation is wrong for me this should be "Anbieter" (german) and not "Providers"
