### ISSUE TITLE
Dark theme selection isn't visible

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#454]
**Describe the bug**
When you select an addon in a dark theme, you can't see the selection. All light themes work, all dark themes are broken.

**To Reproduce**
1. click on an addon or use CTRL+A while using a dark theme

**Expected behavior**
That the row is visibly different from the unselected rows

**Screenshots**
![image](https://user-images.githubusercontent.com/1754678/99555555-bb6eea00-29c0-11eb-8b5c-07f78f10d7ae.png)
![image](https://user-images.githubusercontent.com/1754678/99555615-c75aac00-29c0-11eb-8c22-716082c72019.png)

**Comment by jliddev** [comment]
Should be fixed in beta 18
