### ISSUE TITLE
Re-Scan appears to show mods that are actually up to date

### ISSUE THREAD

**Issue by KevinAllenWiegand** [WowUp/WowUp#461]
After using "Re-Scan Folders", I have 3 addons that show up as needing updating:

Deadly Boss Mods - Burning Crusade and Vanilla mods r675
Deadly Boss Mods - Legion r21
Deadly Boss Mods - Warlords of Draenor r52

I hit "Update All", and it all appears to succeed.  Game version updated to 90002 for these mods.

If I "Re-Scan Folders" again (Check Updates shows no difference), these same three mods show up as needing an update again.

**Comment by jliddev** [comment]
What version of the app are you using?

**Comment by KevinAllenWiegand** [comment]
1.19.1
