### ISSUE TITLE
Add support for installing addons via Curseforge "Install" button

### ISSUE THREAD

**Issue by RhapsodySL** [WowUp/WowUp#462]
As of recent, Curseforge added an "Install" button to addon pages. This uses a URI to direct to Overwolf's Curseforge client and automatically download the file and selected version.

Clicking the Install button redirects you to the following URI (using Deadly Boss Mods as an example):

curseforge://install?addonId=3358&fileId=3114258

In the above URI, the addonId references the addon's ID, while fileId references the version. When clicking the Install button, the Curseforge client will automatically open and install the addon on the version you selected Install for, allowing you to use the Curseforge website rather than the client itself.

Adding support for this URI would be ideal as it furthers WowUp's general goal of being a plug-and-play replacement for the WoW aspect of the Curseforge client.

**Comment by jliddev** [comment]
We had aworking example of this at one point, not sure where it went. but it needs to be configurable.

**Comment by jliddev** [comment]
This was completed
