### ISSUE TITLE
Able to trigger multiple downloads of the same addon

### ISSUE THREAD

**Issue by psykzz** [WowUp/WowUp#468]
**Describe the bug**
Able to trigger multiple downloads of the same addon, by clicking check updates, then update / update all.

**To Reproduce**
1. Go to My Addons
2. Have a number of addons to update
3. Click Update All
4. Click Check updates
5. See that addons need update again, however an update is already in process (in the background, not shown to the user)

**Expected behavior**
After clicking Check updates, to show the in progress downloads.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 2.0.0.beta20

**Comment by jliddev** [comment]
Is this fixed?

**Comment by psykzz** [comment]
Yup - thanks!
