### ISSUE TITLE
Add Git Provider git.tukui.org

### ISSUE THREAD

**Issue by vmwinckler** [WowUp/WowUp#469]
Addon **RematchElvUISkin** outdated on **Curse** and **Tukui**, but has update pending on **Tukui Git**: 
https://git.tukui.org/NihilisticPandemonium/RematchElvUISkin/-/merge_requests

Here: https://git.tukui.org/fuba82/RematchElvUISkin.git

**Comment by jliddev** [comment]
This author does not create releases on their gitlab so there's not much we could do with this until then.

**Comment by psykzz** [comment]
Do you add other addons available via a release on GitHub?

**Comment by linaori** [comment]
Addon authors have to make releases and add the zip with the addon(s) inside it, wowup doesn't do anything other than download & unzip it to the addon directory.
