### ISSUE TITLE
Tooltip is missing translation

### ISSUE THREAD

**Issue by Zonk1987** [WowUp/WowUp#476]
Version v2.0.0-beta.21
![Screenshot_44](https://user-images.githubusercontent.com/25836879/99764643-cbd8af00-2afd-11eb-8831-c811d60071e5.jpg)

"This addon has multiple providers" is not translated to german and some other language.

**Comment by jliddev** [comment]
Someone who knows german would need to translate MULTIPLE_PROVIDERS_TOOLTIP in de.json

**Comment by Zonk1987** [comment]
"MULTIPLE_PROVIDERS_TOOLTIP": "Dieses Addon hat mehrere Anbieter",

**Comment by Nils89** [comment]
Added a PR for this #477
