### ISSUE TITLE
Switching between WoW versions while updating addon, erroneously still shows addon

### ISSUE THREAD

**Issue by EdwinHauspie** [WowUp/WowUp#479]
- Update a big addon (example: Raider.io), or have a slow connection
- Switch to a different WoW version, for example _Retail_ -> _Classic_
- The addon that is still updating, will show on the _Classic_ page, even tough that addon is not installed there

**Comment by EdwinHauspie** [comment]
I see now the client drop down is disabled while addons are updating.
Was this changed maybe in one of the latest beta releases? Anyway, closed.

**Comment by linaori** [comment]
The functionality in the top bar is indeed now disabled when updating a single addon as well, this was made to behave the same as when pressing the "update all" button to prevent the issues as you've reported.
