### ISSUE TITLE
[2.x][Bug] Sorting by GameVersion does not seem to work

### ISSUE THREAD

**Issue by etse** [WowUp/WowUp#481]
**Describe the bug**
When I sort by Game Version the addons does not seem to be sorted correctly. As you can see from the screenshots provided the list is not sorted by Game Version.

**To Reproduce**
1. Install WowUp 2.x Beta
2. Download some addons for different game versions (for instance I have Details! and Raider.IO for 9.0.1 fir 9.0.1 and RareScanner and MythicPlusTimer for 9.0.2)
3. Click table-header "Game version"

**Expected behavior**
The table should be sorted by game version.

**Screenshots**
![image](https://user-images.githubusercontent.com/2163425/99821587-86929c80-2b52-11eb-81f0-48f00f42fa82.png)

![image](https://user-images.githubusercontent.com/2163425/99821637-94e0b880-2b52-11eb-9e76-48a26f36bc52.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v.2.0.0-beta.21

**Comment by linaori** [comment]
I think @jliddev has a fix for this already in the next release (ref: https://github.com/WowUp/WowUp/commit/6a05dd177d0812666980d0f1482dd0f7fecf4f42)

**Comment by etse** [comment]
I can verify that it is fixed in the new release :)

**Comment by linaori** [comment]
Awesome!
