### ISSUE TITLE
Import addons from json file

### ISSUE THREAD

**Issue by alessandrorubio** [WowUp/WowUp#482]
Instead of having to export a whole copy of my addons folder between pc's it would be cool to have a single file thats generated by wowup that i can share on multiple pc installs. This is somehow related to #61 but its not necessarily a backup but just a file representing the addons that wowup needs to install.

Maybe a json file could do the trick.

**Comment by Protuhj** [comment]
This would be awesome!

**Comment by jliddev** [comment]
This is complete as of 2.5
