### ISSUE TITLE
already installed addons disappear

### ISSUE THREAD

**Issue by mogcraft** [WowUp/WowUp#488]
Hello everyone,

some addons, which I installed via WoWUP, disappear from the tab "My Addons"

For example ElvUI Shadow & Light or BigWigs Bossmode. 

In my addon directory (\Interface\AddOns) the folder is included, but in the overview the addon is not shown. I can only reinstall it via the tab "Get Addons".
(See that Screenshot below. In the folder is ElvUI_SLE contained - in the Overview from the Addon not) 
![Screenshot_2](https://user-images.githubusercontent.com/576478/99865425-d2bcfb80-2ba9-11eb-994c-0f94a214ba8f.png)

**Comment by jliddev** [comment]
Disappear? just randomly? that seems odd. has it happened more than once?

**Comment by mogcraft** [comment]
Until then. Two Times. One time with BigWigs and now with Shadow and Light. 

I only noticed it by accident. I get the ingame message from S&L that my addon is not up to date. Checked at WowUp and the addon was not found. It was the same a few weeks ago with Bigwigs

**Comment by mogcraft** [comment]
@jliddev 
A little question. Can I reinstall the addons or should I wait with it for possible troubleshooting?

**Comment by jliddev** [comment]
Are you by chance hitting the re-scan button or something?

**Comment by mogcraft** [comment]
@jliddev I use the re-scan button for almost every update. Has no effect. I upload the debug log. As you can see, it finds the folder of ElvUI Shadow & Lights but it is still not shown in the overview. 
[main.log](https://github.com/WowUp/WowUp/files/5579371/main.log)

**Comment by jliddev** [comment]
re-scan is really only meant to detect changes that were made outside of WowUp. Shadow and light is a weird one in that it's named differently on TukUI and Curse and also can have different versions

**Comment by grufftech** [comment]
Currently I'm experiencing this as well, but I'm assuming it's because the tukui API is verymuch crying.

**Comment by jliddev** [comment]
the fingerprint server is pretty stable now, so should be good

**Comment by DigitlWorld** [comment]
On this note, I just updated to 2.0 and it's no longer recognizing my base ElvUI installation. It was on the list before the update, and gone afterward.

**Comment by Nikki1993** [comment]
Same here. Here is side by side view of both apps, left is 1.x version and right is current 2.x

![image](https://user-images.githubusercontent.com/1446529/100125807-dbe9e900-2e85-11eb-814b-835acab395f5.png)

as you can see the new WoWup version does not detect the Elvui and related addons from Tukui website. Doing a re-scan multiple times yields the same result. This is clearly a regression.

**Comment by jliddev** [comment]
TukUI is down/slow, they will not scan until that is fixed.

**Comment by Nikki1993** [comment]
Perhaps it's a good idea to display some kind of a message that we found these addons but are unable to perform any operations on them as the source is unreachable? simply hiding them from the view makes it seem like WoWup is acting up, not the upstream API.

**Comment by jneuls** [comment]
> Perhaps it's a good idea to display some kind of a message that we found these addons but are unable to perform any operations on them as the source is unreachable? simply hiding them from the view makes it seem like WoWup is acting up, not the upstream API.

This.  The same thing (ElvUI missing from WowUp 2) brought me here and, if WowUp had showed ElvUI in my list of addons (but tinted it red/yellow or with a bang on it, maybe with a tooltip communicating "Hey, the only place we can get updates for this addon is broken.  Again.  Please try again later.") it would have been a _significantly_ less astonishing experience.

**Comment by jliddev** [comment]
yeah we have a PR for it. #526
