### ISSUE TITLE
Window controls having a top-marging

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#491]
Since a recent release (I believe themes), the window controls have a top margin, making it impossible to move your mouse to the corner and click to close. This is in version RC1

![image](https://user-images.githubusercontent.com/1754678/99875958-d6757000-2bf3-11eb-95af-409582624f20.png)

**Comment by Medoke** [comment]
![image](https://user-images.githubusercontent.com/72464426/99877086-57d4fe80-2c04-11eb-8367-faccd904205e.png)
Agree, it came with themes, and as seen on my image, faction/wowup logo is probably causing that.
