### ISSUE TITLE
Suggestion: Filter out addons older than [Game Version]

### ISSUE THREAD

**Issue by gewey** [WowUp/WowUp#497]
I love addons, and I love how simple WowUp is, but the main problem I have with every addon manager is outdated, broken addons cluttering and burying good new functional addons.

I'm sure it's more complicated than it sounds, and some old addons that still work could be filtered out, but if there was an option in settings, similar to how you can choose alpha/beta/release builds for your addons, to "Filter out addons older than (drop down) [Game Version]" when you're browsing for new ones, that'd be awesome. It feels super bad to see exactly what you're looking for only for it to be 4.x.x - 7.x.x last updated 2014, etc, etc. Many addons from as recently as 8.0.1 don't even work. Some addons don't list their game version, so maybe it could go by date, but honestly if the version isn't listed, even if it works, I don't want it anyway because it probably wont work soon.

It makes sense for Minecraft mods to have any version, since you can play any version, but since you're not supposed to be able to play any version of wow (private servers) old ones should be at least filterable so people who want to install broken addons can.

Thank you.

**Comment by jliddev** [comment]
This seems like a lot of overhead, having to constantly keep a list of 'potential' versions up to date and supported for filtering.
