### ISSUE TITLE
Installation / First start : follow OS language

### ISSUE THREAD

**Issue by Zazou89** [WowUp/WowUp#500]
**Is your feature request related to a problem? Please describe.**
When you install / start for the first time WowUp, it's set in English. 

**Describe the solution you'd like**
When you start WowUP for the first time, auto set language following the OS language.

**Describe alternatives you've considered**
I know it's a very minor feature request but not all user know there are a setting to change language.

**Comment by jliddev** [comment]
It should be doing this already const langCode = this.currentLanguage || this._electronService.locale;

**Comment by Zazou89** [comment]
Hum okay, I think I understand why. The French translation is currently broken, that’s why it started in English after a clean install.

**Comment by jliddev** [comment]
should be fixed in rc3

**Comment by Zazou89** [comment]
I’ll test, thank you !

**Comment by Zazou89** [comment]
that's good!
