### ISSUE TITLE
Impossible to set Italian and Russian language (rc.2 version)

### ISSUE THREAD

**Issue by Bito98** [WowUp/WowUp#502]
If I set Italian as default language, the program restarts but it remains in English.
I’ve tried setting in another language first (not English) and then set Italian, but it still returns in English.

**Comment by MrDreek** [comment]
+ Russian language is also not set too.

**Comment by Bito98** [comment]
Edited the title, added Russian problem too

**Comment by jliddev** [comment]
Should be fixed in rc3
