### ISSUE TITLE
ElvUI always appearing as an update

### ISSUE THREAD

**Issue by CDAGaming** [WowUp/WowUp#505]
To be put simply, even after clicking the Update All Button, elvui remained saying there was an update from 12.13 to 12.13
The issue began after updating WowUp from 2.0.0 Beta 21 to 2.0.0 RC 2

Below I've attached screenshots of before and after clicking Update All and letting it go through:
![Screenshot from 2020-11-21 18-21-40](https://user-images.githubusercontent.com/16328918/99890584-7a780f00-2c26-11eb-9751-ba263838ad86.png)
![Screenshot from 2020-11-21 18-22-02](https://user-images.githubusercontent.com/16328918/99890585-7b10a580-2c26-11eb-84e5-54f5e61cb573.png)

Edit: Looking at commits, https://github.com/WowUp/WowUp/commit/2cca03ed13b3901a190e28c55dc68765aa9f2eef likely solves this, and if so, this could be closed and I just still have it here for documenting this issue

**Comment by Medoke** [comment]
Re-Scan folders also solving that :)

**Comment by CDAGaming** [comment]
Closing as both Medoke's solution and the specific commit to WowUp, when I tested it, both fixed this.
