### ISSUE TITLE
Buttons tabs are disabled

### ISSUE THREAD

**Issue by KeziahMoselle** [WowUp/WowUp#510]
**Describe the bug**

When I open WoWUp I can't click on the 3 first tabs, they are disabled.
![image](https://user-images.githubusercontent.com/9168097/99914257-5be44780-2cfc-11eb-8ff4-29ec04d1fd20.png)

**To Reproduce**

I don't know how to reproduce this behavior as it appeared suddenly.

**Expected behavior**

We should be able to click on the tabs "My Addons", "Get Addons" and "About"

**Screenshots**

![lttjBMhIvS](https://user-images.githubusercontent.com/9168097/99914204-158ee880-2cfc-11eb-834e-0047c37dabed.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [v2.0.0-rc.3]

**Additional context**

Note that the update didn't change anything.

**Comment by jliddev** [comment]
Is this your first run of the app?

**Comment by KeziahMoselle** [comment]
Nope, I installed/updated a few addons before, it disabled the tabs buttons yesterady for no reason, I launched the app and tadam 😞

**Comment by jliddev** [comment]
Feel free to post your log files from the debug section of options there.
This is the first report we've had of this.

**Comment by KeziahMoselle** [comment]
Sorry I forgot, will do tomorrow, thank you 🙏

**Comment by KeziahMoselle** [comment]
[main.log](https://github.com/WowUp/WowUp/files/5583567/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/5583568/renderer.log)

**Comment by jliddev** [comment]
hmm decodeProducts is failing on your system

**Comment by jliddev** [comment]
Does this file exist on your machine ? C:\ProgramData\Battle.net\Agent\product.db

**Comment by KeziahMoselle** [comment]
Yes it does : 
![image](https://user-images.githubusercontent.com/9168097/99982135-82f95280-2daa-11eb-925a-dd2d23f504b0.png)

**Comment by jliddev** [comment]
Give rc 6 a try

**Comment by KeziahMoselle** [comment]
![image](https://user-images.githubusercontent.com/9168097/99986993-3153c680-2db0-11eb-9b73-b82cb78b92aa.png)

😢

**Comment by jliddev** [comment]
Gonna need them logs

**Comment by KeziahMoselle** [comment]
[main.log](https://github.com/WowUp/WowUp/files/5584277/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/5584278/renderer.log)

**Comment by jliddev** [comment]
what happens if you clear our that retail path and reselect

**Comment by KeziahMoselle** [comment]
Victory ! 🎉 
Thank you :)

![image](https://user-images.githubusercontent.com/9168097/99987602-f4d49a80-2db0-11eb-81c5-6ab9ea65c3b5.png)

**Comment by jliddev** [comment]
Strange, your system is failing to list the drives to search for the product DB, but glad its going :)

**Comment by KeziahMoselle** [comment]
To be honest I think my Windows is fucked up (like file/save dialog takes a while to load) and this issue is probably a big edge case, thank you for the troubleshoot !

**Comment by jliddev** [comment]
I added one more catch for that, but you shouldnt notice now that it's working
