### ISSUE TITLE
Update from VCS systems

### ISSUE THREAD

**Issue by yoshimo** [WowUp/WowUp#516]
We have #71 to mark addons as in development and prevent accidentally overwriting those addons.
We have #513 to apply patches.

If the user has installed the proper version control system like mercurial, git, subversion or bazaar, why not allow for an update enabled button that does the equivalent of git pull /rebase?

Would be even less work for me

**Comment by jliddev** [comment]
Managing your git repo for you is definitely out of scope of the app.
