### ISSUE TITLE
Mac OS Needs Notorized

### ISSUE THREAD

**Issue by rjcoupe** [WowUp/WowUp#517]
WoWUp refuses to open on Big Sur as it "cannot [be checked] for malicious software" - I couldn't swear to it but I believe this is the error shown if the app has not been signed.

**Comment by KDederichs** [comment]
Yeah that's a signing thing.
You can execute it though by opening Settings -> Security & Privacy -> General -> Open Anyways

**Comment by jliddev** [comment]
The app is signed with a Developer ID Certificate as described here https://developer.apple.com/developer-id/

**Comment by rcoupe-oneweb** [comment]
@jliddev Can you suggest why I get the error described?

@KDederichs for reference, that option's no longer available on Big Sur as it was previously. Apps being signed is now mandatory.

**Comment by rjcoupe** [comment]
> Yeah that's a signing thing.
> You can execute it though by opening Settings -> Security & Privacy -> General -> Open Anyways

@KDederichs this option is no longer available in Big Sur.

@jliddev If it's not a signing issue, can you suggest what might be the case of the error?

**Comment by jliddev** [comment]
Its probably this fun extra step https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db

**Comment by jliddev** [comment]
App is now notarized when building, so the warning should ease up
