### ISSUE TITLE
Doesn't display Curse addons

### ISSUE THREAD

**Issue by Ayagii** [WowUp/WowUp#518]
I can't get the client to display curse addons. Only shows wowinterface addons in the "my addons" tab. I see the curse addons in the "get addons" tab, and when I install them, they are put inside the "my addons" tab, however if I close wowup, and restart, they disappear again. Haven't tried it 
WowUp version: v2.0.0-rc.5
OS: Windows 10
Logs:
[main.log](https://github.com/WowUp/WowUp/files/5583683/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/5583685/renderer.log)

**Comment by jliddev** [comment]
Something weird is going on when it tries to read your files 
[2020-11-15 23:01:25.307] [error] unhandledRejection Error: EIO: i/o error, read

**Comment by jliddev** [comment]
You might try the latest RC

**Comment by RadekRatel** [comment]
This situation is also happening with me - WoWUp 1.19.2 shows 129 addons. WoWUp 2.0.0 shows 32. 
Both for the Retail folder. 

[main.log](https://github.com/WowUp/WowUp/files/5586002/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/5586003/renderer.log)

**Comment by linaori** [comment]
Due to backend problems with wowup, the API is having a hard time verifying if an addon belongs to curse. There's work in progress to fix this problem. Until this is solved, a re-scan can fail detecting addons from curse

**Comment by jwshive** [comment]
The 2.0.0-rc.7 version seems to be working properly at the time of this post.

**Comment by jliddev** [comment]
Fixed an issue with the fingerprint serve, should run fine now :)
