### ISSUE TITLE
Color Accessibility in Alliance and Horde Dark Themes

### ISSUE THREAD

**Issue by ryanfurrer** [WowUp/WowUp#520]
**Describe the bug**
Color of "No" option does not have enough contrast with background. This can be found in the popup prompt to reset the app when enabling/disabling Hardware Acceleration. 

**To Reproduce**
Ensure that you have the Dark Alliance or Dark Horde themes enabled.
1. Go to Options
2. Click on Application on the left
3. Scroll down to toggle "Enable Hardware Acceleration" on/off
4. See error, "No" option is too dark on the gray background.

**Expected behavior**
A brighter color for color may be necessary, or a background applied to it. I know this is not typical of Material UI so a different color may be needed.

**Screenshots**
![Dark Horde Theme](https://user-images.githubusercontent.com/40150036/100015375-db7a2100-2da5-11eb-99f7-59a50857556c.png)
![Dark Alliance Theme](https://user-images.githubusercontent.com/40150036/100015388-e03ed500-2da5-11eb-9bc7-6cf970ac74be.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 version 10.0.19042 Build 19042
 - Browser Chrome version 87.0.4208.66
 - Version [e.g. 22] WowUp version 2.0.0

**Additional context**
Issue is due to the color applied to CSS classes:
`.mat-button.mat-primary, .mat-icon-button.mat-primary, .mat-stroked-button.mat-primary`

**Comment by jliddev** [comment]
Could we just make them white?

**Comment by jar349** [comment]
Is Hardware Acceleration still an option?  I pulled down `v2.1.0-beta.3` but I don't see hardware acceleration in the `OptionsViewModel`

**Comment by linaori** [comment]
![image](https://user-images.githubusercontent.com/1754678/100848283-320bed00-3481-11eb-8109-22a5f39d2f87.png)
