### ISSUE TITLE
default addon chanel

### ISSUE THREAD

**Issue by Addonman** [WowUp/WowUp#524]
**Describe the bug**
Seelcting addon chanel doesnt seems to do anything
**To Reproduce**
options
2. Click on '....' default addon chanel
3. Scroll down to '....' alpha
Error is that addons chanell stay on stable while i selected it to be alpha

**Expected behavior**
expected results -if yo uselect alpha as your default addon chanell then it should show on all of addoons as default chanell

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows

**Additional context**

**Comment by linaori** [comment]
As described in [the guide](https://wowup.io/guide/section/options/wow-clients), this is only for new addons. For existing addons you have to change the channel. You can do this by using CTRL+A to select everything, and then right click -> change addon channel.

**Comment by jliddev** [comment]
@linaori is correct
