### ISSUE TITLE
Start with system fails

### ISSUE THREAD

**Issue by Auxiliotest** [WowUp/WowUp#529]
Hi,

When I enable start WowUp with system it does not start, instead I get a brief what app do you want to open the file with dialogue upon system startup. It does not say which filename it is trying to open. Please find logs attached.

Kind Regards
Alex
[main.log](https://github.com/WowUp/WowUp/files/5596224/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/5596232/renderer.log)

**Comment by jliddev** [comment]
Hmm i dont see anything odd. it happens every time you reboot?

**Comment by Auxiliotest** [comment]
Yes and only when I have the option to start with system enabled and also WowUp does not start unless I start it manually. I could possibly solve it like i did with the older version by manually adding the file to the windows startup variable. Can try that if you want me to?

**Comment by Auxiliotest** [comment]
I manually added it to windows startup via Shell:common startup and that solves my issue with having it to autostart. The in app option to start with system still does not work. But ill close this case now as it is a minor issue that does not affect the main functions of the application and your time is probably better spent on other issues and new features. Thx anyway 💯
