### ISSUE TITLE
Possible Options Bug

### ISSUE THREAD

**Issue by Ramahan53** [WowUp/WowUp#530]
Have to reselect location of the Warcraft _Retail_ folder each time I restart WowUp. Unable to do anything else unless I do so.
Haven't got any other version so no idea of a issue there.

To reproduce the bug just need to restart WowUp.

**Comment by jliddev** [comment]
what version of the app are you using?

**Comment by Ramahan53** [comment]
v2.0.0-rc.1

**Comment by jliddev** [comment]
that's odd, can you send me your renderer log?

**Comment by Ramahan53** [comment]
Fixed with 2.1.0 Beta
