### ISSUE TITLE
[Linux]Resolving `addons` folder is case sensitive

### ISSUE THREAD

**Issue by opospisil** [WowUp/WowUp#532]
**Describe the bug**
I installed wowup on system where I already had a running version of WoW: Shadowlands copied over from windows
Somehow my `addons` folder was all lowercase and WowUp was not picking up any addons installed when I provided correct path to `_retail_` folder.
When I let WowUp to install another addon it created folder called `AddOns` (in camelcase starting with capital)
After renaming my original `addons` folder to `AddOns` WowUp picked up all installed addons correctly

**To Reproduce**
* have addons folder named in all lower case letters
* provide correct path to `_retail_`
* rescan folders
* see that addons list is empty

**Expected behavior**
ideally make it not case sensitive
less ideally but still ok (especially since linux paths and cases can be tricky) mention it in the Docs or better here on GitHub

**Desktop (please complete the following information):**
 - OS: Manjaro 20.2 (Kernel 5.18.18.1)
 - Browser Chromium
- WowUp ver. 2.0.0

**Comment by etse** [comment]
This might be a duplicate of #428

**Comment by opospisil** [comment]
Yeahm definitely looks like it. Was going through reported bugs before creating this one, and it was already hiding under Enhancements. So I'll just close this one and pretend it never happened :D
