### ISSUE TITLE
WowUp overwrites an addon listed in ## Dependencies:

### ISSUE THREAD

**Issue by b-morgan** [WowUp/WowUp#537]
**Describe the bug**
I'm the author of [Skillet](https://www.wowace.com/projects/skillet). I had an alpha version of Skillet installed plus one changed file. While familiarizing myself with WowUp, I found an addon for Skillet that looked interesting, installed it, and WowUp overwrote my copy of Skillet with the latest released version. 

**To Reproduce**
1. Install Skillet with WowUp, latest released version
1. Manually install [latest Skillet alpha](https://www.wowace.com/projects/skillet/files/3123169)
1. Change one file in Skillet
1. Install SkilletTSMPlugin
1. Skillet will be overwritten with the released version because of "## Dependencies: Skillet" in the SkilletTSMPlugin .toc file 

**Expected behavior**
I did not expect Skillet to be touched. An error or warning about Skillet would have been nice.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
With Skillet in an "in progress" state, it is not listed in WoWUp. Listed with a status of  "Modified", "Patched", or "Unknown" would be preferable.

**Comment by jliddev** [comment]
What version of the app are you using? Following your steps does not seem to reproduce this issue.

**Comment by b-morgan** [comment]
It was version 2.0.0. 

I guess my order of execution wasn't exactly as listed. Skillet was installed and in a "work in progress" state before I installed WowUp and did its initial scan. This might be different than a WowUp install of Skillet followed by editing (and changing) a file.

So eliminate step 1. Step 4 should add "with WowUp".

**Comment by jliddev** [comment]
ah, then that would make sense. The app will attempt to install any dependencies that curse tells it to, that are not already installed. This is kind of an edge case so we dont want to make a blanket change to the dependency logic unless we need to. With your modified version it complicates things as we dont _really_ know what that folder is or how to associate it to anything curse related.

**Comment by b-morgan** [comment]
> that are not already installed
Does this mean that with 2.1.0-beta.1 listing all local addons that Skillet in a "work in progress" state will be considered already installed?

**Comment by jliddev** [comment]
The question with that scenario is, if curse says the addon needs INSERT_CURSE_ID how do we know that that folder that was unmatched goes with that addon and that the addon is completely installed ?

**Comment by b-morgan** [comment]
Doesn't the folder name have any bearing on the issue? The .toc file name?

**Comment by jliddev** [comment]
When dealing with curse dependencies thats not really feasible without a lot of extra steps. For example this is what they send us for that TSM plugin in your example.

`"dependencies": [
                {
                    "id": 42081309,
                    "addonId": 14660,
                    "type": 3,
                    "fileId": 2959117
                },
                {
                    "id": 42081310,
                    "addonId": 26886,
                    "type": 2,
                    "fileId": 2959117
                }
            ],`
