### ISSUE TITLE
WowUp should list every addon found locally

### ISSUE THREAD

**Issue by b-morgan** [WowUp/WowUp#538]
**Is your feature request related to a problem? Please describe.**
[](https://github.com/WowUp/WowUp/issues/537) prompted me to create this feature request.

**Describe the solution you'd like**
WowUp should list every addon in my ...\Interface\Addons\ folder with an appropriate status like "Unknown" for those addons it can find in repositories. If the addon is listed in a repository but the state of the local files doesn't match, it should be listed as "Modified" or "Patched".
(Nice to have) If the addon is current set to "Stable" but the local files don't match, check "Beta" or "Alpha" and if a match is found, list the status as "Beta available", "Alpha available",  "Update available", or "Updateable".

**Describe alternatives you've considered**
Ajour lists every addon but I like WowUp better.

**Additional context**

**Comment by jliddev** [comment]
This is live in 2.1.0 beta #526 feel free to give feedback on it :)

**Comment by b-morgan** [comment]
Where does one find 2.1.0 beta?
