### ISSUE TITLE
Can Only See Add-ons From Curse

### ISSUE THREAD

**Issue by Badlife420** [WowUp/WowUp#545]
**Describe the bug**
Can Only See Add-ons From Curse

**To Reproduce**
I installed wowup
only add-on options available are from curse

**Expected behavior**
more add-on options would like to install TukUI

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/75173198/100518995-c7676280-319d-11eb-8259-8fac87f0fb1d.png)

**Desktop (please complete the following information):**
![Untitled2](https://user-images.githubusercontent.com/75173198/100518993-c5050880-319d-11eb-91b8-61236a2f0ed2.png)
 - Chrome Version 86.0.4240.198 (Official Build) (64-bit)

**Additional context**
[main.log](https://github.com/WowUp/WowUp/files/5610786/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/5610784/renderer.log)

**Comment by jliddev** [comment]
Looks like a couple errors, one TukUI is timing out so you're unable to see anything from them.

The second looks like you're trying to install something by URL but we don't understand the url.
