### ISSUE TITLE
Re-Scan Folders does nothing in v2.1.0-beta.1

### ISSUE THREAD

**Issue by ntowle** [WowUp/WowUp#546]
**Describe the bug**
Re-Scan Folders completes immediately with no change in v2.1.0-beta.1 for Retail only.

**To Reproduce**
1. Click Re-Scan Folders on retail
2. Scan completes in <1 second, with no change
3. Contrasted with Classic Re-Scan which takes several seconds and updates the list with file system changes

**Expected behavior**
Expected Re-Scan to do something for Retail.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - WowUp v.2.1.0-beta.1

**Additional context**
In the logs is a just single line (no associated curse-get-scan-results line):

[2020-11-28 10:31:06.699] [info] list-directories E:\World of Warcraft\_retail_\Interface\AddOns

**Comment by jliddev** [comment]
which log file is this from? main or renderer

**Comment by ntowle** [comment]
> which log file is this from? main or renderer

Main. There is actually a stack trace in renderer:

> [2020-11-28 12:03:02.849] [error] TypeError: Cannot set property 'fileStats' of null
>     at t.<anonymous> (file:///C:/Users/Nick/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.2958b501e41b35a52bf3.js:1:1131300)
>     at Generator.next (<anonymous>)
>     at i (file:///C:/Users/Nick/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.2958b501e41b35a52bf3.js:1:1128548)
>     at l.invoke (file:///C:/Users/Nick/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills-es2015.0dd68a3f76e24363f2e7.js:1:6624)
>     at Object.onInvoke (file:///C:/Users/Nick/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.2958b501e41b35a52bf3.js:1:712923)
>     at l.invoke (file:///C:/Users/Nick/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills-es2015.0dd68a3f76e24363f2e7.js:1:6564)
>     at i.run (file:///C:/Users/Nick/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills-es2015.0dd68a3f76e24363f2e7.js:1:2036)
>     at file:///C:/Users/Nick/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills-es2015.0dd68a3f76e24363f2e7.js:1:12968
>     at l.invokeTask (file:///C:/Users/Nick/AppData/Local/Programs/wowup/resources/app.asar/dist/polyfills-es2015.0dd68a3f76e24363f2e7.js:1:7242)
>     at Object.onInvokeTask (file:///C:/Users/Nick/AppData/Local/Programs/wowup/resources/app.asar/dist/main-es2015.2958b501e41b35a52bf3.js:1:712812)
>

**Comment by jliddev** [comment]
I'll throw some more logging into beta 2

**Comment by jliddev** [comment]
Actually it looks like you have a folder with no toc , that might cause this issue.

**Comment by b-morgan** [comment]
I just attempted to re-scan my Classic folder with 2.1.0-beta.1 and nothing happened but a re-scan of Retail worked.
[renderer.log](https://github.com/WowUp/WowUp/files/5611019/renderer.log)
[main.log](https://github.com/WowUp/WowUp/files/5611020/main.log)

**Comment by jliddev** [comment]
looks like a similar issue, i made a change for next beta that should help.

**Comment by ntowle** [comment]
On beta.2 the re-scan works as expected. Here are the new loglines:

> [2020-11-28 23:12:21.364] [warn] Failed to get addonFolder, no toc found: Blizzard_AchievementUI
> [2020-11-28 23:12:21.437] [warn] Failed to get addonFolder, no toc found: Blizzard_ArchaeologyUI
> [2020-11-28 23:12:21.512] [warn] Failed to get addonFolder, no toc found: Blizzard_ArenaUI
> [2020-11-28 23:12:21.588] [warn] Failed to get addonFolder, no toc found: Blizzard_AuctionUI
> [2020-11-28 23:12:21.662] [warn] Failed to get addonFolder, no toc found: Blizzard_AuthChallengeUI
> [2020-11-28 23:12:21.737] [warn] Failed to get addonFolder, no toc found: Blizzard_BarbershopUI
> [2020-11-28 23:12:21.811] [warn] Failed to get addonFolder, no toc found: Blizzard_BattlefieldMinimap
> [2020-11-28 23:12:21.888] [warn] Failed to get addonFolder, no toc found: Blizzard_BindingUI
> [2020-11-28 23:12:21.962] [warn] Failed to get addonFolder, no toc found: Blizzard_BlackMarketUI
> [2020-11-28 23:12:22.041] [warn] Failed to get addonFolder, no toc found: Blizzard_Calendar
> [2020-11-28 23:12:22.118] [warn] Failed to get addonFolder, no toc found: Blizzard_ChallengesUI
> [2020-11-28 23:12:22.193] [warn] Failed to get addonFolder, no toc found: Blizzard_ClientSavedVariables
> [2020-11-28 23:12:22.267] [warn] Failed to get addonFolder, no toc found: Blizzard_Collections
> [2020-11-28 23:12:22.341] [warn] Failed to get addonFolder, no toc found: Blizzard_CombatLog
> [2020-11-28 23:12:22.417] [warn] Failed to get addonFolder, no toc found: Blizzard_CombatText
> [2020-11-28 23:12:22.491] [warn] Failed to get addonFolder, no toc found: Blizzard_CompactRaidFrames
> [2020-11-28 23:12:22.567] [warn] Failed to get addonFolder, no toc found: Blizzard_CUFProfiles
> [2020-11-28 23:12:22.641] [warn] Failed to get addonFolder, no toc found: Blizzard_DeathRecap
> [2020-11-28 23:12:22.719] [warn] Failed to get addonFolder, no toc found: Blizzard_DebugTools
> [2020-11-28 23:12:22.794] [warn] Failed to get addonFolder, no toc found: Blizzard_EncounterJournal
> [2020-11-28 23:12:22.872] [warn] Failed to get addonFolder, no toc found: Blizzard_GarrisonUI
> [2020-11-28 23:12:22.948] [warn] Failed to get addonFolder, no toc found: Blizzard_GlyphUI
> [2020-11-28 23:12:23.023] [warn] Failed to get addonFolder, no toc found: Blizzard_GMChatUI
> [2020-11-28 23:12:23.097] [warn] Failed to get addonFolder, no toc found: Blizzard_GMSurveyUI
> [2020-11-28 23:12:23.171] [warn] Failed to get addonFolder, no toc found: Blizzard_GuildBankUI
> [2020-11-28 23:12:23.244] [warn] Failed to get addonFolder, no toc found: Blizzard_GuildControlUI
> [2020-11-28 23:12:23.325] [warn] Failed to get addonFolder, no toc found: Blizzard_GuildUI
> [2020-11-28 23:12:23.399] [warn] Failed to get addonFolder, no toc found: Blizzard_InspectUI
> [2020-11-28 23:12:23.472] [warn] Failed to get addonFolder, no toc found: Blizzard_ItemAlterationUI
> [2020-11-28 23:12:23.548] [warn] Failed to get addonFolder, no toc found: Blizzard_ItemSocketingUI
> [2020-11-28 23:12:23.628] [warn] Failed to get addonFolder, no toc found: Blizzard_ItemUpgradeUI
> [2020-11-28 23:12:23.702] [warn] Failed to get addonFolder, no toc found: Blizzard_LookingForGuildUI
> [2020-11-28 23:12:23.776] [warn] Failed to get addonFolder, no toc found: Blizzard_MacroUI
> [2020-11-28 23:12:23.856] [warn] Failed to get addonFolder, no toc found: Blizzard_MovePad
> [2020-11-28 23:12:23.933] [warn] Failed to get addonFolder, no toc found: Blizzard_ObjectiveTracker
> [2020-11-28 23:12:24.007] [warn] Failed to get addonFolder, no toc found: Blizzard_PetBattleUI
> [2020-11-28 23:12:24.083] [warn] Failed to get addonFolder, no toc found: Blizzard_PetJournal
> [2020-11-28 23:12:24.157] [warn] Failed to get addonFolder, no toc found: Blizzard_PVPUI
> [2020-11-28 23:12:24.232] [warn] Failed to get addonFolder, no toc found: Blizzard_QuestChoice
> [2020-11-28 23:12:24.311] [warn] Failed to get addonFolder, no toc found: Blizzard_RaidUI
> [2020-11-28 23:12:24.394] [warn] Failed to get addonFolder, no toc found: Blizzard_ReforgingUI
> [2020-11-28 23:12:24.468] [warn] Failed to get addonFolder, no toc found: Blizzard_SocialUI
> [2020-11-28 23:12:24.542] [warn] Failed to get addonFolder, no toc found: Blizzard_StoreUI
> [2020-11-28 23:12:24.619] [warn] Failed to get addonFolder, no toc found: Blizzard_TalentUI
> [2020-11-28 23:12:24.693] [warn] Failed to get addonFolder, no toc found: Blizzard_TimeManager
> [2020-11-28 23:12:24.770] [warn] Failed to get addonFolder, no toc found: Blizzard_TokenUI
> [2020-11-28 23:12:24.853] [warn] Failed to get addonFolder, no toc found: Blizzard_TradeSkillUI
> [2020-11-28 23:12:24.929] [warn] Failed to get addonFolder, no toc found: Blizzard_TrainerUI
> [2020-11-28 23:12:25.007] [warn] Failed to get addonFolder, no toc found: Blizzard_Tutorial
> [2020-11-28 23:12:25.084] [warn] Failed to get addonFolder, no toc found: Blizzard_VoidStorageUI
> [2020-11-28 23:12:25.160] [warn] Failed to get addonFolder, no toc found: Blizzard_WowTokenUI

**Comment by jliddev** [comment]
well thats good news :D

**Comment by b-morgan** [comment]
Works for me as well. Do you need the log?
