### ISSUE TITLE
Mac OS: 16x16 App Icon is Badly Glitched

### ISSUE THREAD

**Issue by alphabitnz** [WowUp/WowUp#547]
Mac OS Big Sur 11.1 beta (unable to test on older / supported versions of Mac OS but possibly irrelevant)

See attached screenshots, the 16x16 icon for the addon manager seems to be having severe graphical issues.
The larger icon is totally fine etc. but I just happened to notice this looking at the application in the Applications folder in list view which uses more condensed icon graphics. 

Thought I'd bring it to attention in case it was not noticed yet. Thanks!

![wowup mac lores](https://user-images.githubusercontent.com/9102111/100525862-a3049800-3228-11eb-9732-28c4d75bdd01.png)

![wowup app info](https://user-images.githubusercontent.com/9102111/100525867-a435c500-3228-11eb-86e5-0c1be420e8d7.png)

**Comment by jliddev** [comment]
Tried several different ways to get electron builder to fix this but was unable. so if anyone has any ideas im game lol

**Comment by alphabitnz** [comment]
> 
> 
> Tried several different ways to get electron builder to fix this but was unable. so if anyone has any ideas im game lol

googled a little:
https://github.com/electron-userland/electron-builder/issues/1663

build a custom 16x16 resolution icon asset into the .ico file 

> The `*.ico` filetype can be used for a variety of sizes all in one file. It can almost be thought of like a small archive of icons. So instead of trying to use multiple `*.ico` files (which won't work), just use something like GIMP or ConvertICO to create a set of icons in 1 `*.ico` file.
> 
> Related: https://graphicdesign.stackexchange.com/questions/17257/creating-an-ico-file-with-multiple-sizes-web-application

**Comment by jliddev** [comment]
think we tried that, the one thats there has like 5 sizes in it i think

**Comment by alphabitnz** [comment]
any chance you can post the ico file?

**Comment by jliddev** [comment]
https://github.com/WowUp/WowUp/blob/master/wowup-electron/electron-build/icon.ico

**Comment by alphabitnz** [comment]
interesting, the ico file preview viewed at 16x16 scale or even an export of just that layer to an ico file seems fine so I think your methods to produce that file were flawless. 

I did find this post regarding jagged icons in electron with some suggestions you may have already seen:
https://forum.quasar-framework.org/topic/2827/windows-app-icon-with-electron-electron-builder-are-jagged

also I made a more defined 3 colour pixel drawn 16x16 icon asset for you in case it helps:
![icon_16](https://user-images.githubusercontent.com/9102111/100534450-c43ea600-3273-11eb-9fc4-58c67cae24f5.png)

**Comment by jliddev** [comment]
i'll have to see if i can remember how to mess with .icons lol

**Comment by alphabitnz** [comment]
I made a couple exports using my new 16x16 icon in place of the previous 16x16 one, but made two exports with different settings in case that is part of the issue
[icon_new16.zip](https://github.com/WowUp/WowUp/files/5632666/icon_new16.zip)

icon_new16_32bpp_8bitaplha_nopalette <- used the GIMP preset settings for the 16x16 layer which im not sure are either default because they are 'recommended' or possibly just the metadata of the png icon file I generated
icon_new16_8bpp_1bitaplha_256slotpalette <- used the same settings for the 16x16 layer as the other layers had showing

**Comment by jliddev** [comment]
Seems like your ico file works Fine on my machine. You'll have to give it a shot when beta 7 comes out.

<img width="377" alt="Screen Shot 2020-12-14 at 1 16 51 PM" src="https://user-images.githubusercontent.com/20467484/102125033-a5f9ae00-3e0e-11eb-9831-b6976c5cc95a.png">

**Comment by alphabitnz** [comment]
![Screen Shot 2020-12-18 at 2 30 09 PM](https://user-images.githubusercontent.com/9102111/102563161-8da2cf80-413d-11eb-9d19-ee59548ad308.png)

Still not looking great i'm afraid, even tried clearing the icon cache in case that was the issue.

Which of the two .ico export did you include there?

icon_new16_8bpp_1bitaplha_256slotpalette
icon_new16_32bpp_8bitaplha_nopalette

**Comment by jliddev** [comment]
I think i used the 256 one i can try the other

**Comment by alphabitnz** [comment]
![Screen Shot 2020-12-31 at 1 45 06 PM](https://user-images.githubusercontent.com/9102111/103388556-78329a00-4b6e-11eb-8a89-41c428c63e1e.png)

Unfortunately doesn't look solved on my end, maybe I need to do more investigation
