### ISSUE TITLE
Button to go directly to the addon page

### ISSUE THREAD

**Issue by infekSK** [WowUp/WowUp#551]
A dedicated button next to the addons currently installed to go to the addon page is a lot smoother than clicking on the addon > view in browser. It may not seem that important but when most addons don't seem to have their update notes ingame, it becomes tiresome going through them all and clicking more than you need to.

**Comment by jliddev** [comment]
when we had it as a column people complained, its not in the context menu and details. thats probably enough places.

**Comment by infekSK** [comment]
It's not in the context menu though, it's only when you select the addon.

It being in the context menu would be better than where it is currently.

**Comment by linaori** [comment]
![image](https://user-images.githubusercontent.com/1754678/100649198-5f05b600-3342-11eb-8b97-023c4d728df2.png)

**Comment by infekSK** [comment]
That's only in the beta client, so I suppose I'll update to that.
