### ISSUE TITLE
Zoom State Not Saved Between Launches

### ISSUE THREAD

**Issue by Brightbrown** [WowUp/WowUp#555]
**Describe the bug**
See title

**To Reproduce**
Launch the application

**Expected behavior:
Not reverting to the default zoom

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6

**Comment by jliddev** [comment]
Can you give this a test on the latest beta?

**Comment by Brightbrown** [comment]
Downloaded the latest beta 2.1.0b13 (took a bit of digging to find it) and see that now there is NO option to change the view at all... the View menu no longer has those controls.

**Comment by jliddev** [comment]
Hmm that's true. However there is still a drop down in the app options tab and the hotkeys to test it. I'll see about integrating the menu to the same mechanism.

**Comment by Brightbrown** [comment]
My bad, thought I checked everywhere... apparently not. Scale seem to persist between launches, might be an idea to provide a few more options between 90% and 75%
