### ISSUE TITLE
Is it possible to support ElvUI: Plugins?

### ISSUE THREAD

**Issue by robwilkes** [WowUp/WowUp#557]
**Describe the solution you'd like**
Support for ElvUI Plugins: https://www.tukui.org/addons.php?cat=19

**Describe alternatives you've considered**
Currently have to check and update manually

Thanks for all your hard work.

**Comment by robwilkes** [comment]
Just noticed the plugin is available on curse (Shadow & Light).
Installs to the same folder (ElvUI_SLE).
WoWUp doesn't detect it when rescanning folders, but after I install the addon manually it's now tracking it.
I guess that's sufficient, it'll update automatically now.

**Comment by linaori** [comment]
The addons provided by TukUI can already be found

With only TukUI as provider:
![image](https://user-images.githubusercontent.com/1754678/100599671-9b182700-3300-11eb-82f5-870da3208009.png)

With every provider enabled:
![image](https://user-images.githubusercontent.com/1754678/100599794-c1d65d80-3300-11eb-9123-be8ed61866d2.png)

Generally speaking there's only 1 provider shown per addon, so if you search for Shadow and Light you should find this:
![image](https://user-images.githubusercontent.com/1754678/100599907-e599a380-3300-11eb-8440-ce6fcf1ff07c.png)
