### ISSUE TITLE
GatherMate2 classic misrecognition

### ISSUE THREAD

**Issue by Mard35** [WowUp/WowUp#561]
App does not recognize correctly the source of GatherMate2 Classic addon. It suggests to update my classic GatherMate2 1.45.6 version to GatherMate2 1.46.3 for retail from https://www.wowinterface.com/downloads/info21293
When I try to switch to update from curse, it gives me an error. That's because of the curse version of classic GatherMate2 link differs from retail one on curse. App is trying to switch to https://www.curseforge.com/wow/addons/gathermate2 link, but there is no classic version. Classic version of GatherMate2 has different location and name https://www.curseforge.com/wow/addons/gathermate2-classic/

**Comment by jliddev** [comment]
This one is more complicated that it seems. But up until recently gathermate2 had classic and retail versions on the same addon. then one day not too long ago they were removed leaving some people stuck. The app is correctly detecting it, you just need to switch to the new addon.
