### ISSUE TITLE
Different Results on Launch than from a Re-Scan

### ISSUE THREAD

**Issue by Brightbrown** [WowUp/WowUp#566]
**Describe the bug**
First kaunch showing things that may go away on a re-0scan

**To Reproduce**
Launch, see things needing updates, re-scan, no updates needed.
Launch, see a beta update needed, but it's seet for stable, re-scan, need for beta goes away

**Expected behavior**
Lunch and re-scan to be the same

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Version: 2.0.1

**Additional context**

**Comment by jliddev** [comment]
still an issue? updates were made to the API earlier today.
