### ISSUE TITLE
default addon channel type option is not working!

### ISSUE THREAD

**Issue by Fooforu** [WowUp/WowUp#567]
**Describe the bug**
default addon channel option is set to alpha. alpha versions exsist. addon channels remain on stable and don't show option to download.

**Comment by Fooforu** [comment]
the curseforge client is doing it properly and wowup is not. please fix because this is the only issue keeping me from dumping their piece of shit software!

**Comment by jliddev** [comment]
Youd have to give me an example, because "properly" is relative.

**Comment by Fooforu** [comment]
ok, first thankyou for replying and I LOVE! wowup and what I mean is when I set the default addon channel to alpha on curseforge it shows the download option if there is an alpha available. if it do this on wowup, it does not! happened just not with Deadly Boss Mods. and when I right click on the addon in question or any addon it shows the 'stable' option still selected.

**Comment by jliddev** [comment]
what version of the app do you have? seems to work as expect for me.

![image](https://user-images.githubusercontent.com/20467484/100941313-0d366a80-34bf-11eb-83f4-a6de30aea315.png)

**Comment by Fooforu** [comment]
2.02

**Comment by jliddev** [comment]
can you send a screenshot of what you're seeing.

**Comment by Fooforu** [comment]
I will try

**Comment by Fooforu** [comment]
![2020-12-02 (2)](https://user-images.githubusercontent.com/58642805/100942772-eb8eb080-34c9-11eb-9360-250b03bf6247.png)

**Comment by Fooforu** [comment]
![2020-12-02 (3)](https://user-images.githubusercontent.com/58642805/100943197-c64e7200-34ca-11eb-9c13-cd37f32430ab.png)

**Comment by jliddev** [comment]
The default channel only works for new installs. You might just do a Ctrl + A to select all then right click and set them alpha

**Comment by Uggers** [comment]
Just to confirm this is exactly what I had to do, 
Existing "discovered" add-ons did not change to Alpha, but once I realised you could select all and set to Alpha it was fine.
All new add-ons (because I change the channel type to Alpha) default to Alpha 

The only real difference between this and curse is curse applied it globally to all discovered add-ons, were as WowUp you need to just select all or the ones you want and change. 

The only "issue" (and I use that term lightly) is it was just not obvious I could select all and change to begin with, I assumed that it would copy Curse's method to begin with, but I figured it out after a minute.

**Comment by linaori** [comment]
Discovering keybinds is a bit tricky at the moment. Perhaps we can add control buttons with tooltips that hint towards it? You can find the existing keybinds in the guide: https://wowup.io/guide/section/wowup/shortcuts

**Comment by Uggers** [comment]
For me i think it was the colour scheme,

When you select them individually, it changed to a darker colour, so I didn't realise that I'd selected everything

So for example you'd think I'd selected ACE3 and ACEGUI, but really I'd selected the other addons around it.

![image](https://user-images.githubusercontent.com/6855065/100996668-3dc6e480-3551-11eb-85e1-9f281fb4427c.png)


Keybinding's are great though, they are typical program defaults I think visually it took me a moment to realise what I was doing

**Comment by linaori** [comment]
I'm sure we can improve the visuals of selected rows other than the color. It confuses me as well. Do you have any ideas on how to improve this?

**Comment by Uggers** [comment]
To be honest the only way I can think if it is to use an entirely different colour that isn't already used in a theme. 

A light blue or maybe an inversion of the background and text colour? Not to sure really without trying some I imagine would look awful without trying a few ones to see.

I sometimes use https://colorhunt.co/ to find some colours when trying to do the UX
Something like this (similar ish)
https://colorhunt.co/palette/219713

Might work, its not to bad really it just took me a moment or 2 to realise what I was actually selecting and what I wasn't

**Comment by linaori** [comment]
Hmm yeah we have some alternating colors in the palette we could use. Another option would be an additional indicator, like an icon of sorts. Though I feel like a "highlight" color would indeed be the best. Selecting something should make it lighter, not darker imo

**Comment by Uggers** [comment]
Yeah that would work too.
The mouse over colour is great its very obvious, it might just be try a few
and see if they work, Like I said it wasn't really that bad I think it just
caught me out at first.
indicator would also work.

In this particular ticket, maybe when you change the channel type in the
settings you could have a tick box for "apply to all existing addons" which
would help too perhaps

**Comment by LittleVulpix** [comment]
Came here to say the same thing; for people who used curse (and then twitch) updater, setting the default preference to X would instantly change it for all addons. It might be better if WowUp does this by default else you'll get confused users. That said, I used CTRL+A -> change, and lived happily ever after too. I just didn't know I could do that!
