### ISSUE TITLE
Sort Order for Updated Addosn

### ISSUE THREAD

**Issue by Uggers** [WowUp/WowUp#568]
It would be nice if the sorting of add-ons could be done a little bit more like Curse or the option to do it.

I like the fact you can sort by all the filters, but I used to have mine like this

Alphabetised, however updates were put at the top of that list.
When those updates were updated. They'd stay at the top of the list saying "recently updated" and would remain there until a new add-on was detected as needing updated then it would recent.

Its not a game breaker if not. It was just helpful to have non add-ons still Alphabetised, but for a while the recently updated ones were kept at the top still so you there was an issue you could see those specifically without having to change the filtering

**Comment by joaosantana81** [comment]
@Uggers So you want to sort your addons alphabetically and keep them sorted even when they are marked to update?

**Comment by Uggers** [comment]
I think "grouped" is probably the better analogy.

- They are all sorted Alphabetically

- Unless an updated is required (Update required ones at the top - anything not requiring updated is Alphabetically below the last one needing updated)

- Once updated, the same view applies but shows the recently update ones at the top group, then after the last recently updated ones the list is Alphabetical again.

- When a new addon needs updating then just pushes the recent ones into the normal alphabetical list and has the new "needs update" at the top


Bit hard to explain as I can't demo it in Curse's addon anymore. It was just handy to see recent updates at the top for a while then eventually it returned to Alphabetical when something new dropped in.

**Comment by jliddev** [comment]
Seems like an overcomplication of "sorting" when you could just click once to sort however, then click again to sort it the original way?

**Comment by Uggers** [comment]
yeah probably :) No worries if not,
I don't think its over-complication per say, but I agree its not a regular use case, more after big patches etc when you have a lot of updates and want to keep an eye on what might be causing lua issues or seeing what's updated again.
But yeah you could just click the sorting each time if you wanted to
