### ISSUE TITLE
Please Notarize Mac App

### ISSUE THREAD

**Issue by mikeacjones** [WowUp/WowUp#569]
**Is your feature request related to a problem? Please describe.**

macOS gatekeeper now requires that apps be notarized. You can still open the app by going into settings and clicking open anyway, but for future installs it would be nice to have it notarized. 

**Describe the solution you'd like**
Add `electron-builder-notarize` to the macOS publish profile for electron builder - should be added as `afterSign`

**Additional context**
Bypassing gatekeeper is frustrating for most Mac users who are unaware it even exists.

**Comment by linaori** [comment]
This has been fixed in #541, just not released yet. If you want to try it out, you can download the beta and see if it works: https://github.com/WowUp/WowUp/releases/tag/v2.1.0-beta.3

This feature is merged into beta2, so everything after that should work.

**Comment by mikeacjones** [comment]
Ah - nice! I’ll try it out. Thanks 💯

**Comment by jliddev** [comment]
This should be complete in the beta.
