### ISSUE TITLE
Select what version you want to DL or some kind of roll back ability

### ISSUE THREAD

**Issue by Addonman** [WowUp/WowUp#570]
**Is your feature request related to a problem? Please describe.**
Yes. On Curse you could select version/release you wanted to DL. Lets say latest version isnt working -how do you go back to version that is working?
**Describe the solution you'd like**
Ability to DL what ever version i want like there was option on CF.

**Describe alternatives you've considered**

**Additional context**

**Comment by jliddev** [comment]
Duplicate of #16
