### ISSUE TITLE
Missing addons

### ISSUE THREAD

**Issue by Addonman** [WowUp/WowUp#572]
**Describe the bug**
I updated addons throug WOWup then went on Curse page to see for new updates and saw Plater has new update.So i tried to see Plater in wowup.He wasnt on list at all even thoug i updated it throug WOWup before numerous times.Then i went to get addons portion of WOWup and it tells me that i need to Install it. So clearly it isnt detecting addon corectly. i can say i had similar exp with some other addons as well.
**To Reproduce**
Dont apply here i think since its simple use of Wowup

**Expected behavior**

For Wowup to detect installed addons and to not mess it up with new avaiable version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10
 - Browser [e.g. chrome, safari] Firefox

**Additional context**

**Comment by Addonman** [comment]
I did rescan of folders and Plater is back on My addons list.

**Comment by jliddev** [comment]
There are several things at play here, sometimes we have a gap in fingerprints due to us having to import them from CF.
