### ISSUE TITLE
Custom tagging

### ISSUE THREAD

**Issue by Sekorhex** [WowUp/WowUp#573]
**Is your feature request related to a problem? Please describe.**
I have more than 50 Addons on the list and its very annoying to find some addons together.

**Describe the solution you'd like**
It would be nice to create own custom tags for every addon. Then when i type on the search bar "pve" then it shows my own tagged pve addons.

**Comment by strayge** [comment]
What if instead just filter by addons categories?  
This way users does not needed to mark all (50+ at your case) addons manually.

**Comment by Sekorhex** [comment]
Every single player has his own preference which addon is for pve etc. So would it be better to give them the option to create his own list with keywords to filter separatly.

**Comment by jliddev** [comment]
We would need to circle back to this once tagging is added for our new provider.

**Comment by jliddev** [comment]
move to #73
