### ISSUE TITLE
Make a tooltip give the reason why an addon is ignored

### ISSUE THREAD

**Issue by yoshimo** [WowUp/WowUp#575]
There are a couple of reasons why wowup would ignore an addon and in the future there might be a few more.

- manually ignored
- automatically ignored because wowup didn't want to break external updaters like raider.io
- it is a detected broken installation
- it was manually modified and doesn't exactly match a released version
- it was detected as a development version because it has .git or a .svn folder inside
- Curse detected it as broken
- WoWup couldn't find the right provider for it
- other

To see which of those reasons is the right one for the addon, i suggest a tooltip for ignored addons, that state the reason for it being in ignored state.

**Comment by jliddev** [comment]
We have added a tooltip and icon for abnormal addons in the latest beta, check that out and we can refine it further. adding a tooltip to everything is overkill.
