### ISSUE TITLE
Delete old folders for renamed addons

### ISSUE THREAD

**Issue by yoshimo** [WowUp/WowUp#577]
From Discord #suggestions

**Is your feature request related to a problem? Please describe.**
Addons get renamed by their author to reflect changes.
Updating the old addon to the new name results in 2 addon folders, one for the new name and one with the old name.

**Describe the solution you'd like**
Match the old name to the new name by reading identifieres like Curse/WowInterface Ids from the files and remove the old one

**Describe alternatives you've considered**
Doing it manually

**Additional context**

The example would be GridStatusRaidDebuff(WOD) with ## X-Curse-Project-ID: 85975
which was recently renamed to PlexusStatusRaidDebuff (Wod) , keeping the ID.

**Comment by linaori** [comment]
If you do an update, the old directory would've been removed, and the new directory added. I've fixed this close to 2.0.0 release. I'll need a reproducer to see why this wouldn't work in your scenario.

**Comment by yoshimo** [comment]
Just copying stuff over, but i could try to reproduce it , maybe with old files on curse.
What would be needed to help fix this?

**Comment by linaori** [comment]
I don't know, because afaik this should already work.

**Comment by yoshimo** [comment]
I played around with this a little.
When i remove the "updated" foldername , do a rescan and then update again the old folder is removed.
So i guess it only gets called when the addon gets an update and there is no in between cleanup run to remove old fragments.

**Comment by linaori** [comment]
When an addon is installed, we save the folder names it installs. When you update or remove the addon, we remove all folders that are listed for that addon. If you remove a folder and then do a rescan, it will no longer see that folder as a part of the WA. 

It sounds to me like it's working as intended as you're not supposed to mess with the addon data yourself anyway 😄

**Comment by yoshimo** [comment]
I fiddled with the addon because you wanted to recreate what happened.
I think we have a timing issue, the update happened before you added your cleanup code.
Because the addon wasn't updated after 2.0something  it wasn't triggered.
Wether it would have happened in the future, is not clear to me.
I think a cleanup shouldn't depend on the next update as you can clearly connect old folder and new folder and see from the most recent update archive that the old folder is no longer needed.

**Comment by linaori** [comment]
WowUp can only clean up information it knows right now. So yes, if these directories were removed _before_ my fix went live, it will never be cleaned. There's nothing that we can use to indicate that these directories have to be removed.

**Comment by yoshimo** [comment]
Nothing? If I have the same project ID listed in two folders in the. toc file I can be sure that folder a and folder b belong to the same Addon even if it now has a different name.

**Comment by linaori** [comment]
How does wowup deal with this in the beta? Does it register both directories? Does it register 1 as "unknown"?

**Comment by yoshimo** [comment]
Current beta marks the old folder as ignored, because it can't find a valid provider for it.

**Comment by jliddev** [comment]
An addons name should not affect anything, if the author changes the actual folder it should be cleaned up if the ID hasnt changed. Im not sure what the actual issue is here?

**Comment by yoshimo** [comment]
The issue is that the old folder is still there.
I assume it happened because the feature of "removing old folders" came at the wrong point in time compared to the rename process.

**Comment by jliddev** [comment]
is this still reproducable?

**Comment by yoshimo** [comment]
Yes i still have two folders for renamed addons  where the .toc shares the same x-curse-project-id.
For example `## X-Curse-Project-ID: 83874` which belonged to GridStatusDungeonDebuff.
This addon is now known to be PlexusStatusDungeonDebuff.
