### ISSUE TITLE
[feature request] Exportable addon configs + sync using common cloud providers (dropbox/google drive/onedrive/etc.)

### ISSUE THREAD

**Issue by olfilato** [WowUp/WowUp#578]
Portability of addon setups is important to a lot of people, so being able to export/backup a config file listing all your addons/their versions/etc. that can be imported by WowUp (either on another machine or as a part of backup recovery process) is a very needed feature.

On top of that feature, it would be nice to have it integrated with common cloud storage providers, so that a user can sync that config file to cloud provider of their choice (requires a login with their cloud storage account for API access). However, to build that, exportable configs need to be implemented first.

If this feature request is approved, I am willing to implement them and open pull requests myself.

**Comment by IB38** [comment]
I was thinking maybe user github repos as a way to store and share your addon configs too?
Could have same SSO thingy, and wowup already has some code working with github api.
Assuminig addon list & settings would be serialized to text, building history of your addons & updates would be easy.

**Comment by jliddev** [comment]
Move to #22
