### ISSUE TITLE
Does NOT do a scan when opened...

### ISSUE THREAD

**Issue by Brightbrown** [WowUp/WowUp#582]
**Describe the bug**
I can launch the app and see updates that I had made the day before... from other means.

**To Reproduce**
Launch the app

**Expected behavior**
Not seeing previously updated items.. i.e. it would do a full scan when launched

**Desktop (please complete the following information):**
macOS 10.13.6

**Comment by linaori** [comment]
I'm not sure what you're referring to. Do you mean that updates made by external sources are not detected?

**Comment by Brightbrown** [comment]
Correct... my expectation is that on launch, a full scan is done.

**Comment by linaori** [comment]
That's not what happens, only updates are checked. Doing a re-scan every time it starts up is too slow and fragile.

**Comment by jliddev** [comment]
We will not be doing a full scan on startup.
