### ISSUE TITLE
Avalonia-based client for all 3 platforms?

### ISSUE THREAD

**Issue by IB38** [WowUp/WowUp#587]
I was thinking, have you considered avalonia-based client?
Migrating main WPF client should be easy enough, i don't think wowup uses anything windows-specific.
This way there would be no need for electron client and everything would have single codebase.

**Comment by linaori** [comment]
That means backporting every single feature added. It also already has a single codebase and cross platform, so I don't think there's anything to gain from switching, other than a lot of work.

**Comment by IB38** [comment]
But it doesn't have single codebase. 
Electron and wpf client are completely separate, every feature added has to be ported (to electron, assuming wpf client is main).
Or do i misunderstand something?

**Comment by jliddev** [comment]
The WPF is no longer supported as we have migrated to the 2.0 cross platform version.

**Comment by IB38** [comment]
Ah, i see. Its a shame you went this way, oh well.

**Comment by linaori** [comment]
I think this way is just fine ;)
