### ISSUE TITLE
[Request] Application Color Themes

### ISSUE THREAD

**Issue by Braxusz** [WowUp/WowUp#59]
This isn't up some peoples alley, but would be be possible to integrate an app theme? Horde/Alliance/Blizzard color schemes etc.?

**Comment by jliddev** [comment]
This could be fun, if someone has the color palettes

**Comment by Braxusz** [comment]
I couldn't really find anything official myself, but here are some links with color coding, and I capped some of the colors from the b.net launcher as well. 

https://pixelimperfectdotcom.wordpress.com/2013/09/05/all-world-of-warcraft-hex-color-codes/
![Blizzard Launcher Light-Gray](https://user-images.githubusercontent.com/70422288/94399673-b1e1a800-011c-11eb-983d-a80448acf399.jpg)
![Blizzard Blue From Launcher](https://user-images.githubusercontent.com/70422288/94399676-b27a3e80-011c-11eb-95c5-7e0b19dda79a.jpg)
![Blizzard Launcher Gray](https://user-images.githubusercontent.com/70422288/94399677-b27a3e80-011c-11eb-9983-9f49dbe9a778.jpg)

**Comment by RaZz0r65** [comment]
Tbh while im fine with the current theme and while it would be nice to have more game focused ones in terms of a simple color change.
I would love to have the current theme just make it slightly darker like this its just a screenshot made darker in photo shop.
As its just ever so slightly too bright be default 
https://i.imgur.com/bDkWNQ0.png

**Comment by jliddev** [comment]
Maybe we look into creating a system to allow community theming.

**Comment by Braxusz** [comment]
I would absolutely take part in that.

**Comment by jliddev** [comment]
added in latest beta
