### ISSUE TITLE
Wants to install/update addons I dont have

### ISSUE THREAD

**Issue by makedir** [WowUp/WowUp#593]
https://i.imgur.com/qvbvKcL.png

I never have installed that addon, when I click open folder it opens WeakAuras a totally different addon.

I am on version 2.1.0-beta 5

**Comment by jliddev** [comment]
New logging will be added to beta 6 to see if we can figure this out.

**Comment by jliddev** [comment]
Can you update to the latest beta, then go to options -> debug -> show log files and send me your latest renderer.log?

**Comment by makedir** [comment]
[renderer.zip](https://github.com/WowUp/WowUp/files/5693165/renderer.zip)

**Comment by makedir** [comment]
your program is saying WeakAuras is "BetterVendorPrice.

see here:

## Interface: 90002
## Title: WeakAuras
## Author: The WeakAuras Team
## Version: 3.1.2
## Notes: A powerful, comprehensive utility for displaying graphics and information based on buffs, debuffs, and other triggers.
## Notes-esES: Potente y completa aplicación que te permitirá mostrar por pantalla múltiples diseños, basados en beneficios, perjuicios y otros activadores.
## Notes-deDE: Ein leistungsfähiges, umfassendes Addon zur grafischen Darstellung von Informationen von Auren, Cooldowns, Timern und vielem mehr.
## Notes-ruRU: Мощный, многосторонний инструмент для отображения графики и информации, основанной на баффах, дебаффах и других триггерах.
## Notes-zhTW: 一個強大且全面實用的顯示圖形和訊息基於增益，減益和其它觸發。
## X-Category: Interface Enhancements
## Globe-Post: WeakAurasOptions, WeakAurasModelPaths, WeakAurasTemplates
## X-Website: https://www.curseforge.com/wow/addons/weakauras
## X-Curse-Project-ID: 65387
## X-WoWI-ID: 24910
## DefaultState: Enabled
## LoadOnDemand: 0
## SavedVariables: WeakAurasSaved
## OptionalDeps: Ace3, LibCompress, LibSharedMedia-3.0, AceGUI-3.0-SharedMediaWidgets, Masque, GTFO, LibButtonGlow-1.0, LibSpellRange-1.0, LibRangeCheck-2.0, LibDBIcon-1.0, LibClassicDurations, LibClassicCasterino, LibGetFrame-1.0

**Comment by jliddev** [comment]
try doing a rescan?

**Comment by makedir** [comment]
yes I have manually downloaded latest weakauras2 3.1.4 and copied them manually into folder, rescane, now its fixed. but that still means there is a bug in your program.

**Comment by jliddev** [comment]
Send me your latest renderer log there werent any examples of you doing a scan in the last one

**Comment by makedir** [comment]
thats nonsense, because the log is there since I use your program. Also how would a new log help if it doesnt show the issue anymore?

**Comment by jliddev** [comment]
ok well i tried to help :)

**Comment by makedir** [comment]
I dont need help this is a bug report to fix your program. Look at this picture:

You can see on this picture: https://imgur.com/qvbvKcL

What do you see? Yes? LEFT version number 3.1.2 is a totally different version branch than the right one, because its two different addons.

**Comment by jliddev** [comment]
i cannot tell you why that is happening from that screenshot, which is why i asked for you logs.

**Comment by makedir** [comment]
and as you even said yourself, the logs dont include anything about "bettervendorprice" isnt that even worse? that means there is another bug in your program, because I never deleted the log files, and theyre there from the first version I ever used your program some weeks ago.

**Comment by jliddev** [comment]
get the latest beta, run a scan, send me the log. until thats done there's nothing more to talk about.

**Comment by makedir** [comment]
[renderer.zip](https://github.com/WowUp/WowUp/files/5710977/renderer.zip)
