### ISSUE TITLE
Duplicated Addons from TukuUI

### ISSUE THREAD

**Issue by vmwinckler** [WowUp/WowUp#594]
After last update, i see ElvUI for install but i have ElvUI installed, i verify and both from same source...

OK, i click on "install" again... i think be resolve situation "installed/not installed"...

Result:
![image](https://user-images.githubusercontent.com/1237277/102108707-fe7e7a80-3e11-11eb-8820-cd29e5822741.png)

- OS: Windows 10 Pro
- My Browsers: chrome, edge.. and other....
- WoWUp version: v2.0.2

**Comment by jliddev** [comment]
do a re-scan
