### ISSUE TITLE
Message: ...ns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:395: attempt to index a nil value

### ISSUE THREAD

**Issue by lynspottery** [WowUp/WowUp#600]
The following Lua error is what popped up in the middle of my screen shortly after I ported to my covenant:

**Describe the bug**
Seems there is a lua error with Blizzard_MapCanvas???

**To Reproduce**
I have no idea how to reproduce this.

**Expected behavior**
I have no idea

**Screenshots**
I forgot to take one

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]    Windows 10
 - Browser [e.g. chrome, safari]  Chrome
 - Version [e.g. 22] Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
Message: ...ns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:395: attempt to index a nil value
Time: Wed Dec 16 14:21:32 2020
Count: 400
Stack: ...ns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:395: attempt to index a nil value
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:395: in function `ApplyCurrentPosition'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:279: in function `SetNudgeVector'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:327: in function `CalculatePinNudging'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:365: in function `UpdatePinNudging'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:29: in function <...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:28>

Locals: self = <unnamed> {
 0 = <userdata>
 GetGlobalPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:311
 PanTo = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:318
 BountyRing = <unnamed> {
 }
 OnMouseUpAction = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:473
 OnMouseDownAction = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:467
 OnCanvasScaleChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:328
 GetNudgeSourceZoomedInMagnitude = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:233
 SetScaleStyle = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:359
 GetNudgeSourcePinZoomedInNudgeFactor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:269
 UpdateTooltip = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:435
 GetMap = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:257
 OnCanvasSizeChanged = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:337
 ApplyCurrentPosition = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:394
 IsIgnoringGlobalPinScale = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:345
 Glow = <unnamed> {
 }
 GetNudgeZoomFactor = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:291
 OnMouseUp = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:178
 OnAcquired = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:144
 PanAndZoomTo = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:323
 SelectedGlow = <unnamed> {
 }
 RefreshVisuals = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:399
 ApplyCurrentAlpha = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:415
 OnLoad = <function> defined @Interface\AddOns\Blizzard_AnimaDiversionUI\AD_WorldQuestDataProvider.lua:9
 TrackedCheck = <unnamed> {
 }
 UpdateSupertrackedHighlight = <function> defined @Interface\AddOns\Blizzard_SharedMapDataProviders\WorldQuestDataProvider.lua:430
 OnReleased = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:148
 IgnoresNudging = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:253
 startAlpha = 0.600000
 normalizedY = 0.567108
 normalizedX = 0.391445
 worldQuestType = 2
 ClearNudgeSettings = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:199
 OnMapInsetMouseLeave = <function> defined @Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:195
 tagInfo = <table> {
 }
 SetNudgeFactor = <function> defined @Interface\AddOns\Bl

**Comment by linaori** [comment]
This error has nothing to do with WowUp
