### ISSUE TITLE
WoWUp can't find an addon update if the addon is manteined on 2 different repository

### ISSUE THREAD

**Issue by MrDuckHunt79** [WowUp/WowUp#605]
As stated in the title, WoWUp can't find an addon update if the addon is manteined on 2 different repository

Example: 
TomTom addon, manteined on CurseForge and WowInterface

On CurseForge latest version is 1.1.9

On WowInteface latest version is 1.2.0

Cause the 2 repository aren't synced

Other addon manager discover the latest version right, wowup hang on the CurseForge one.

**Comment by jliddev** [comment]
Cant find what? you can easily find and install these. What other addon manager ? I dont understand this question?

**Comment by MrDuckHunt79** [comment]
I try to explain better, with this example:

TomTom addon have 2 repository:

One on CurseForge: https://www.curseforge.com/wow/addons/tomtom

One on WoWInterface: https://www.wowinterface.com/downloads/info7032-TomTom.html

When i wrote the the previus message the 2 repository weren't synced (now they are).

On CurseForge the latest one was TomTom-v90002-1.1.9.zip, on  WoWInterface the latest one was TomTom-v90002-1.2.0.zip 

This because the 1.2.0 version on WoWInterface was uploaded on 02/12/20 06:14 PM, on CurseForge was uploaded on 19/12/20 09:53AM after 17 Days. 

Your program had fail to discover the newest one.

Other programs, like sigularity, get the right one.

Now it's clear?

**Comment by jliddev** [comment]
im not sure what you mean by "discover". when you are scanning or are you expecting the app to check both providers and show you the latest?

**Comment by MrDuckHunt79** [comment]
Yes, when we (for we i mean my guildmates) look for addon updates, we look for the latest one, the real latest one (and i suppose that's the result that everyone would expect), as other addon managers do.

We really like your addon manager, and we found only this "bug" (or maybe "missing feature"), that a big downside, compared to other around.

I think that's if WowUp could check version between repository and could chose the latest one will be great.

**Comment by jliddev** [comment]
WowUp is not designed to check for the "latest" across multiple providers. It will find you the latest for your selected provider. There are technical issues with doing it the way you describe. Singularity probably uses their own aggregate service rather than having the client makes the requests which we're not setup to do.
