### ISSUE TITLE
backup addons options

### ISSUE THREAD

**Issue by yajinni** [WowUp/WowUp#61]
Needs to have a backup option.
To be able to set it to auto back up, ex: once a week, daily, etc
To have multiple backups/history/ability to roll back an update.
To be able to chose the locations of the backups, so i can have it store it on a cloud drive if i want.

**Comment by jliddev** [comment]
I support a backup feature, need to think it out though. Dont want to create a bunch of backups on the user system there may be a simple way to get by for now. i'll revisit this soon.

**Comment by BoscoDomingo** [comment]
May I suggest literally making a copy of the WTF and Interface/Addons folders into a directory of the user's choice, and keep a timestamp of when the last backup was done so it can be performed automatically? Sounds simple, intuitive and effective enough to work. No need to think of special systems, and restoring from that backup would be as simple as copying said folders back to the World of Warcraft game directory

**Comment by ayell** [comment]
I manage my addon with a private gitlab repo . It's work like a charm . Maybe it will be a premium feature and u manage our self hosted git server and create a branch or repo by account ? I easy to do with api

**Comment by Walkerbo** [comment]
> May I suggest literally making a copy of the WTF and Interface/Addons folders into a directory of the user's choice, and keeping a timestamp of when the last backup was done so it can be performed automatically? Sounds simple, intuitive and effective enough to work. No need to think of special systems, and restoring from that backup would be as simple as copying said folders back to the World of Warcraft game directory

Yes please; I know that Ajour has this functionality.

**Comment by ayell** [comment]
I do this :)
https://github.com/jliddev/WowUp/pull/119

I hope it will be accept

**Comment by DomGrieco** [comment]
options to set backup location would be really nice. might try and submit a PR for it

**Comment by ayell** [comment]
I did this feature 2 times , one time when the app was in C# and 2nd times when the app it was on Electron . Nobody has marged my PR and I lost my source code . I dont want redo this 3st times ^^

**Comment by jliddev** [comment]
This is more or less complete as of 2.5
