### ISSUE TITLE
[request] Share/export installed addons

### ISSUE THREAD

**Issue by makedir** [WowUp/WowUp#613]
Can you please implement a quick export string as BASE64 which includes all installed addons, you then can import on another PC in the WowUp GUI. That would be handy.

**Comment by jliddev** [comment]
Part of #20 This is not something quick and its not simple. But we will get there.

**Comment by makedir** [comment]
This is like as easy as it can get, mayke a task of 30 minutes. I am a programmer myself. You export the current list as a base64 and then import it again. This is done in Java like in a few lines of code.

**Comment by jliddev** [comment]
Feel free to create a pull request
