### ISSUE TITLE
Windows size not remembered

### ISSUE THREAD

**Issue by Daeveren** [WowUp/WowUp#617]
This only started happening with 2.1.0 beta 10 - after closing WowUp (it was maximised), the next launch it starts in a smaller window, see screenshot.

Using Windows 10 here. This behavior never happened before with other WowUp versions; this behavior persists through computer restarts.

![E1fZdRWG6B](https://user-images.githubusercontent.com/6321337/103162229-b9395000-47f6-11eb-957b-07cd0424b2d8.png)

**Comment by jliddev** [comment]
Ok i reverted back to the old window restore logic should work better next beta.

**Comment by jliddev** [comment]
Is this working as expected now?

**Comment by Daeveren** [comment]
Yes for me it fixed 8 days ago when that beta version was pushed (I thin it was beta 11), forgot to mention here. I've noticed in the beta release notes of a more recent build that there was further code optimization for the window size management and I can confirm that, atleast for me, both these beta versions work ok -- in my use case, WowUp is only being used maximized (I'm on Win10), I close it while the window is maximized and when I relaunch it it now stays maximized.

**Comment by jliddev** [comment]
Thanks!
