### ISSUE TITLE
Install Addon URL Github No Release Assets

### ISSUE THREAD

**Issue by wrath625** [WowUp/WowUp#619]
**Describe the bug**
When attempting to install an addon from a github URL "No Release Assets" are found.

**To Reproduce**
1. Click Install from URL
2. Paste in the example github URL from documentation `https://github.com/WowUp/WowUp.Addon`

**Expected behavior**
It works

**Screenshots**
![image](https://user-images.githubusercontent.com/3255181/103179454-2ffb3b00-4841-11eb-9d4d-45c460885290.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.0.2

**Comment by wrath625** [comment]
I dug into the code.  This is an issue between retail and classic, and the release asset not having `"-classic.zip"` at the end of the file name apparently.

Perhaps there should be a more verbose error message if an asset is found that does not conform to this requirement.

**Comment by jliddev** [comment]
Added more detailed error output for next beta
![image](https://user-images.githubusercontent.com/20467484/103188439-0a485300-488e-11eb-9c63-fdb0d68472d8.png)
