### ISSUE TITLE
Auto ignore addons with .git folder

### ISSUE THREAD

**Issue by eyalsk** [WowUp/WowUp#624]
**Is your feature request related to a problem? Please describe.**
I've accidentally ended up updating my own addon luckily I've pushed the changes just before I've updated so I propose to either ignore addons with `.git` folder within them or at least have a warning before updating them.

**Describe the solution you'd like**
Check for `.get/config` and then match against the following regex `(?:url)\s*=\s*(?:.+github\.com).+(?:\.git)` which should be sufficient for `https`, `ssh` and any other protocol scheme, it's possible to do a less thorough check but it's up to you.

**Describe alternatives you've considered**
If I knew better I'd ignore the addon manually but I didn't know it's going to erase the folder. 

If this was fixed or brought up before you can close this issue. 

Thank you for everything! keep up the good work. <3

**Comment by jliddev** [comment]
I swear we had a ticket for this, but cant find one.

**Comment by jliddev** [comment]
I added a way to set a type of why something is set to unknown resulting in 
![image](https://user-images.githubusercontent.com/20467484/103316449-3d095d00-49ee-11eb-8ec7-7ce313ce8623.png)

**Comment by eyalsk** [comment]
@jliddev This solves the issue at the display level but what does it do when the user tries to update the addon? what happens when the user click on `Update All`?

**Comment by jliddev** [comment]
@eyalsk nothing should happen, its marked as an "unknown" provider

**Comment by eyalsk** [comment]
@jliddev ahh gotcha, thank you! ;)

**Comment by jliddev** [comment]
Its in the latest beta if you want to give it a try

**Comment by cremor** [comment]
> I swear we had a ticket for this, but cant find one.

@jliddev I think you mean #71
