### ISSUE TITLE
Clone Addons / Addon Collections (for reinstall) / Perform Backup

### ISSUE THREAD

**Issue by Uggers** [WowUp/WowUp#626]
A neat feature would be the ability to

1. Clone all your addons from Retail to PTR when a new PTR branch roles out for testing (or when a BETA appears when addons are enabled etc)
2. Could be useful to create a backup set when transferring to a new PC, for example it backs up the install addons that WoWUp can read and then trigger redownloading them all on a new pc?
3. Also schedule/create a full folder back up of specific folders suchs as  "addons", "wtf", "screenshots" etc

**Comment by jliddev** [comment]
This should probably tie in with one of our "sync addons" tickets
