### ISSUE TITLE
Feature suggestion: Export list of installed add-ons into a file (eg: download queue) that can be imported to a new client for a fresh install.

### ISSUE THREAD

**Issue by numbawon** [WowUp/WowUp#630]
Overview: Transferring from on machine to another or a fresh install needs an efficient way to do a fresh install of all the add-ons in an efficient way. al'a import a queue even if it's a basic txt file that could be user edited to delete mods you don't want anymore or something 

From existing install: Export currently installed add-ons to a file or queue. Option one: Allow user to check boxes to be exported of currently installed add-ons. Option two: User editable clear text file that can be user edited to delete lines from the queue that may no longer be wanted  

To new device or installation: Install and or run WowUp and import from file the download queue file from previous step. Tertiary option: End user has an option to deselect items from queue for import. Last, wait for queue to process.

**Comment by jliddev** [comment]
See #482
