### ISSUE TITLE
Update installed addons automatically on start

### ISSUE THREAD

**Issue by miguelarc95** [WowUp/WowUp#634]
Would this even be possible? One thing I find annoying is having to open up WoWUp every day or so, and click the update button. Would it be hard to implement a feature (making it toggleable in the settings) that would automatically update all installed addons daily/weekly, when WoWUp starts?

(sorry if there is already an open issue related to this, but I couldn't find any)

**Comment by aumer-amr** [comment]
You can right-click any addon and enable auto-update for that addon, when WowUp scans your addons for updates, it will auto update that addon. Sadly you have to enable that manually for all your current addons (unless I missed something), however to enable this for future new addons, you can enable it so auto update becomes enable by default.

1. Go to options
2. Make sure you're on "Clients" settings in the left menu
3. Find your installation you want auto-update enabled
4. Enable "Auto Update"

**Comment by aumer-amr** [comment]
Additionally in the same options under "Application" in the left menu, you can enable WowUp to be started when your system starts, this way you don't have to manually open up WowUp every day.

**Comment by miguelarc95** [comment]
Thanks for the quick reply. I found out that you can Shift-click first and last addon to select all addons, and if you toggle Auto-Update to one of them, it will select Auto-Update to all of them. The feature becomes pointless with this 😆 Thanks once again for the help.
