### ISSUE TITLE
Addon Installation Failed error to generic upon rate limit 

### ISSUE THREAD

**Issue by aumer-amr** [WowUp/WowUp#635]
While trying to test my own addon from GitHub, I kept on addon & removing it from my installation. At some point it threw the error "No addon was found, make sure your URL is pointing to the correct page". 

![image](https://user-images.githubusercontent.com/11768106/103342747-a0e16380-4a8a-11eb-9e8e-7070d3ba22a0.png)

It worked before, only until I looked at the logs and found out I was rate limited by GitHub.
<details>
<summary>Logs</summary>

`[2020-12-30 10:27:40.254] [error] {
  headers: {
    normalizedNames: {},
    lazyUpdate: null,
    lazyInit: '[function] ()=>{this.headers=new Map,t.split("\\n").forEach(t=>{const e=t.indexOf(":");if(e>0){const n=t.slice(0,e),a=n.toLowerCase(),o=t.slice(e+1).trim();this.maybeSetNormalizedName(n,a),this.headers.has(a)?this.headers.get(a).push(o):this.headers.set(a,[o])}})}'
  },
  status: 403,
  statusText: 'rate limit exceeded',
  url: 'https://api.github.com/repos/******/**********/releases',
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for https://api.github.com/repos/******/**********/releases: 403 rate limit exceeded',
  error: {
    message: "W for ***.***.***.***. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    documentation_url: 'https://developer.github.com/v3/#rate-limiting'
  }
}`

</details>

**To Reproduce**
1. Install an addon using github
2. Remove the addon
3. Repeat from step 1 until error "No addon was found"
4. Logs should now say rate limited

**Expected behavior**
Instead of "No addon was found", i expected an error that described the issue more, something along the lines of "github is busy, please try again in 30 minutes".

**Additional info**
I looked into Github's docs and found out that they are sending the rate limit back in their response headers, which can be used to detect if the user is rate limited.
https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#rate-limiting

**Comment by jliddev** [comment]
I thought we had something like this already but i guess not. Added a new error case for this.

![image](https://user-images.githubusercontent.com/20467484/103365894-ccfae580-4a86-11eb-8576-f68ba7c40d03.png)

**Comment by aumer-amr** [comment]
Thank you for the wonderful enhancement <3
