### ISSUE TITLE
Restore window doesn't work

### ISSUE THREAD

**Issue by edanluna** [WowUp/WowUp#642]
**Describe the bug**
Restore window size button doesn't works

**To Reproduce**
1. Maximize the window
2. Use the rectangle or Alt+Space to try to restore window
3. Window stays maximized

**Expected behavior**
When using the restore window button the window should have the dimensions it had before clicking the maximize window

**Desktop (please complete the following information):**
 - Windows 10
 - WowUp Version v2.0.2

**Comment by jliddev** [comment]
Seems to work fine

![lRfaCpRelL](https://user-images.githubusercontent.com/20467484/103446662-e008e380-4c47-11eb-8f4d-1f5c9a4e6af1.gif)

**Comment by edanluna** [comment]
After reinstalling it works. I guess is better to close, probably something with my Windows
