### ISSUE TITLE
Gather a database from user input?

### ISSUE THREAD

**Issue by RudolphRiedel** [WowUp/WowUp#645]
**Is your feature request related to a problem? Please describe.**
When I go to "Get Addons" there is only a very tiny amount of addons to choose from, I have 141 listed right now.
And the "Provider" listed for these is only TukUI and Curse.

**Describe the solution you'd like**
What about using the URLs from users who successfully installed an Addon with "Install from URL" to build a database?
Perhaps with an opt-in setting to send this data 
The "provider" listed then would be "Github" for example.

**Comment by jliddev** [comment]
We actually have a project we're working on to support something like this, stay tuned :)
