### ISSUE TITLE
Addon provider is changed after "rescan folder"

### ISSUE THREAD

**Issue by cremor** [WowUp/WowUp#652]
**Describe the bug**
I have two CurseForge addons that switch to a different provider when I run "rescan folder": WeakAuras and Dungeon Tools.

**To Reproduce**
1. Install WeakAuras and Dungeon Tools from CurseForge.
2. Click on 'rescan folders'
3. Check the provider of the addons. It is changed to "Hub".

**Expected behavior**
The provider should still be Curse.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox (why is this relevant?)
 - Version v2.1.0-beta.16

**Additional context**
The name of the addons is changed too. "WeakAuras" is changed to "WeakAuras2", "Dungeon Tools" is changed to "DungeonTools". Maybe this has something to do with the reason why the provider is changed.

Also it seems like the provider priority is not the one documented here: https://wowup.io/guide/section/my-addons/rescan-folders (Hub is missing completely there)
Btw, I'm not sure what "Hub" actually is. Is this documented somewhere?

**Comment by jliddev** [comment]
Hub is our own provider, its not document yet as its not in prod. This behavior is expected, re-scan is a reset as described by the popup.
