### ISSUE TITLE
Multiple Warcraft Folders for Classic

### ISSUE THREAD

**Issue by Rootkit-** [WowUp/WowUp#662]
**Is your feature request related to a problem? Please describe.**
Problem is I have 2 different warcraft folders I need updated for classic on same computer.

**Describe the solution you'd like**
I'd like to add another Classic Folder to update, ie: Classic, Retail, Classic Another Folder

**Describe alternatives you've considered**
Manually swap and refresh addons then update or having to copy paste addons folder everytime i update.

**Additional context**
Should be fairly simple to add another classic path then add it like you did for ptr recently
![image](https://user-images.githubusercontent.com/5389279/103582442-7ab12e80-4ea3-11eb-836e-42b545bc5e83.png)

**Comment by jliddev** [comment]
I've had some thoughts about changing up how installs, which would also accommodate this. But will have to wait until a later milestone.

**Comment by jliddev** [comment]
This should now work as expected in 2.2 beta 6+
