### ISSUE TITLE
Elvui doesn't seem to be updating

### ISSUE THREAD

**Issue by pcg79** [WowUp/WowUp#663]
**Describe the bug**
Elvui has a new version out (12.17).  But WowUp doesn't recognize the addon as having an update.

**To Reproduce**
1. Go to WowUp
2. Search for Elvui.  See it's on 12.16.
3. Go to official [Elvui site](https://www.tukui.org/download.php?ui=elvui) and see it's on 12.17.

**Expected behavior**
WowUp shows a pending update for Elvui

**Screenshots**
<img width="1340" alt="Screen Shot 2021-01-05 at 9 16 18 am" src="https://user-images.githubusercontent.com/10041/103628302-b77a3580-4f36-11eb-9c95-fa1d108e20e0.png">

**Desktop (please complete the following information):**
 - WowUp Mac version 2.0.2
 - OS:  Mac OSX
 - Chrome

**Comment by SoLoR1** [comment]
have same issue... my guess is that "change" from build or two ago that uses mirror and that mirror doesnt "mirrors" :)

**Comment by SoLoR1** [comment]
ah okey... was just guessing since im usually actually reading changelogs in general :)

**Comment by jliddev** [comment]
This particular issue was something separate from the changelogs and should be fixed in 2.0.3
