### ISSUE TITLE
"Released at" column is sorting incorrectly

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#664]
Reported for 2.0.2 initially, but also seems to be present in 2.1-beta18. It seems to partially and randomly sort at times (consistently though)

My `addons.json`: [addons.zip](https://github.com/WowUp/WowUp/files/5769397/addons.zip)

### Beta 18
![image](https://user-images.githubusercontent.com/1754678/103632264-58232200-4f44-11eb-92a1-3ddbfd9489bb.png)
![image](https://user-images.githubusercontent.com/1754678/103632319-6a9d5b80-4f44-11eb-907e-7ca098433340.png)

### 2.0.2 (from Discord report)
![image](https://user-images.githubusercontent.com/1754678/103632363-7be66800-4f44-11eb-9915-136145469f02.png)

**Comment by jliddev** [comment]
🤔

**Comment by jliddev** [comment]
Someone give this a check. I tweaked how it sorts the dates.

**Comment by linaori** [comment]
Seems fixed in beta-19! 👍🏻
