### ISSUE TITLE
GitHub as a Provider

### ISSUE THREAD

**Issue by ridius** [WowUp/WowUp#665]
**Is your feature request related to a problem? Please describe.**
Some of the addons I use, (namely UI mods) have unique variations/packages that are only hosted on GitHub (example: Lorti-UI-Classic). It would be great if WowUp could use the standard GitHub URI structure to download the latest version of a GitHub hosted addon.

**Describe the solution you'd like**
I'd love to see an advanced option that that would allow the user specify a GitHub project URI as a Provider. The client could then use the release/version tags in the URI to compare against the version in the .toc file to see if needs updating or not.

**Describe alternatives you've considered**
I haven't considered any other alternatives. Right now, I just manually update.

**Additional context**
This would depend on the project author using the Git Release/Version Tags correctly, otherwise the version would probably be difficult to check.

**Comment by jliddev** [comment]
WowUp already supports GitHub as a provider, however, the author has to create proper releases in order for it to work. Seehttps://github.com/WeakAuras/WeakAuras2/releases

We do not support raw github repos as most of them need to be compiled/built in someway to be usable.

**Comment by ridius** [comment]
Gothcha. Love the app BTW!!!
