### ISSUE TITLE
WowUp installs oldest version of MouseToolTip

### ISSUE THREAD

**Issue by bardyspoon** [WowUp/WowUp#674]
For some reason, WowUp is installing the oldest version of MoveToolTip. The oldest version is also listed in the search results when searching for the addon.

Link to addon: https://www.curseforge.com/wow/addons/movetooltip-dtip

To work around this issue, I installed the addon manually, and noticed that WowUp does not recognize the installed version, even after re-scanning folders.

WowUp v2.0.3, Windows 10 64-bit, WoW Retail

**Comment by jliddev** [comment]
The author has all releases > 1.0.3 tagged for classic. "gameVersionFlavor": "wow_classic"

See: #306
