### ISSUE TITLE
[Mac] Cmd+W to close the window

### ISSUE THREAD

**Issue by tstirrat** [WowUp/WowUp#676]
**Is your feature request related to a problem? Please describe.**
Cmd+W does not close the main window. 

* I like to have the application stay open in the top bar, but I like to keep the main window closed. 
* Currently I can only close the window by using the mouse, this is less desirable.
* Cmd+Q works, and will kill the entire application
* Usually Cmd+W will close the window without quitting the entire thing on most other Mac software

**Describe the solution you'd like**
Allow Cmd+W to close the main window without quitting the entire app.

**Describe alternatives you've considered**
Clicking on the close button in the top left works fine, but is wayyy less convenient.

**Additional context**
N/A

Thanks for this simple and effective addon updater.

**Comment by jliddev** [comment]
Should be fixed in latest beta
