### ISSUE TITLE
Better "Release At" Field

### ISSUE THREAD

**Issue by Kirbdawg** [WowUp/WowUp#689]
Request 2
An option in "options" to exclude addons updated after a specified date, or expansion.
For example:  I'd like to exclude addons which were last updated over a year ago... so I don't have to look through old addons that don't work anymore.  Should make queries faster, and less garbage to sort through.

Request 1
Please convert the "release at" field to a DATE data type before sorting.  Currently, the "release at" field sorts as text:   for example:  20 days appears newer than 2 days.  This change would be needed before Request2 could work.

**Comment by jliddev** [comment]
The first one isnt really something we can facilitate beyond filtering them out as none of the providers accept a date when searching.

The second thing about the date sorting has been fixed in the beta.
