### ISSUE TITLE
Automatic updates do not work

### ISSUE THREAD

**Issue by Ketris** [WowUp/WowUp#690]
**Describe the bug**
I have 38 addons, most were installed via WowUp. All addons are set to automatically update. None of them actually update on their own. The button saying "Update" appears whenever an addon needs to be updated, so it's automatically CHECKING for updates, but not installing them.

**To Reproduce**
Set all addons to automatic update.
Wait for an addon update to exist.
Watch it not update itself no matter how much time has passed.

**Expected behavior**
Automatic updates should not require ever opening the WowUp UI as long as the tray icon is running.

**Desktop (please complete the following information):**
 - OS: Windows 10 v2004
 - Browser: Chrome
 - Version: 2.0.3 (latest)

**Additional context**
Reinstalling WowUp does not fix anything. Removing all addons and reinstalling them doesn't help either.

**Comment by linaori** [comment]
> Set all addons to automatic update.

Can you tell us which exact steps you took to do this?

**Comment by Ketris** [comment]
I selected all add-ons using shift highlighting, right clicked and enabled
auto update.

I have also previously tried removing all add-ons and reinstalling them
with "newly installed add-ons will be set to automatically update by
default" enabled in the Options page.

Either method ends up with all add-ons showing as "auto update enabled" if
individually rightclicked but the same behavior described above. ("Update"
button appears without having to click "check for updates" but add-ons do
not update automatically)

**Comment by jliddev** [comment]
I am unable to create any issue with this locally, auto update appears to work fine in the background. Have you tried doing a rescan? We had a couple users report that resolved this issue.

**Comment by Ketris** [comment]
I know I had run rescan on more than one occasion in the past to try to correct the issue to no success, but for some reason ever since my rescan 5 days ago things are working correctly now.

The only difference in my config between now and then is that I [b]used[/b] to have Classic installed and set up with addons to also autoupdate, but have since removed it (a few hours before 5 days ago's rescan fix actually). Now the only client configured in WowUp is Retail and everything is working as expected from all supported addon sources.

I'm not about to reinstall Classic, but perhaps the issue was related to having multiple clienttypes set up at once?
