### ISSUE TITLE
Lightheaded addon from WoWInterface

### ISSUE THREAD

**Issue by Orcsplitter** [WowUp/WowUp#706]
**Describe the bug**

The addon does not show up at all when loading.

**To Reproduce**

Open WoWUp addon manager

**Expected behavior**

I expected the addon to show up, since it is from Cladhaire,  a primary addon author at WoWInterface.

**Screenshots**
Think it is pretty explanatory.
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 88

**Additional context**

**Comment by jliddev** [comment]
It will not scan as the author does not have the id in the toc, and WowInterface does not support scanning beyond just the ID
