### ISSUE TITLE
[Bug] CTRL+A does not work until you've selected at least one addon

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#708]
**Describe the bug**
When no addon has been selected before, CTRL+A doesn't selected anything. Once an addon has been selected once, all you need is to focus the app for CTRL+A to work afterwards

**To Reproduce**
1. Open the App
2. Press CTRL+A
3. Select addon
4. Deselect addon
5. Press CTRL+A again

**Expected behavior**
When the app starts up, I expect CTRL+A to work the same as when an addon has been selected (and deselected) in the session before

**Desktop**
 - OS: Windows 10

**Additional context**
Issue is present in 2.1.0-beta.29

**Comment by jliddev** [comment]
I think this was done by design, if the table is not focused ctrl + a does nothing as to keep it from interfering with the select boxes and such
