### ISSUE TITLE
Add "Development" Status

### ISSUE THREAD

**Issue by Wutname1** [WowUp/WowUp#71]
When scanning the user's addons look for a .git folder inside the addon folder. If it exists flag the addon a a "development" version and do not include it in auto-update and remove the Update Button from the UI. The Twitch app currently does this it would be a nice addition to your app.

**Comment by yoshimo** [comment]
Using "git pull" if it has no changes would be even cooler.

**Comment by cremor** [comment]
Since #197 and #225 were closed as duplicates of this issue, please now also handle modified addons (without a .git folder) when fixing this.

**Comment by jliddev** [comment]
Addons with a git folder will now be flagged as code repos.

**Comment by cremor** [comment]
@jliddev What about modified addons? You closed #197 and #225 with the comment that those will be handled in this issue.

**Comment by AlexFolland** [comment]
How do I unignore such a folder?  There's a situation right now where I just want to overwrite my git addons with the releases.

**Comment by Wutname1** [comment]
> How do I unignore such a folder?  There's a situation right now where I just want to overwrite my git addons with the releases.

From the commit messages looks like just delete the .git folder

**Comment by jliddev** [comment]
You could just right click > remove, then install them from Get Addons

**Comment by AlexFolland** [comment]
I want to keep my local working copy though.  The `.git` folder should be allowed to remain.

**Comment by jliddev** [comment]
you want to overwrite the files in your dev folder but keep the git folder?

**Comment by AlexFolland** [comment]
Yes.  That way, I can manage my local copy however I want with git still.

**Comment by Wutname1** [comment]
> Yes.  That way, I can manage my local copy however I want with git still.

If you are trying to test your release build process I just use the PTR for that. Otherwise it just seems like that would cause more issues.  https://imgs.xkcd.com/comics/workflow_2x.png

**Comment by AlexFolland** [comment]
> If you are trying to test your release build process

I'm not.  I'm trying to be able to easily revert an addon to the last state I had it and manage versions of it in case of something broken in an easy update.  There's no reason to destroy the version control.  Git is useful for more than just development.
