### ISSUE TITLE
Not saving the provider on update or re-scan

### ISSUE THREAD

**Issue by Aveelo** [WowUp/WowUp#720]
**Describe the bug**
Reset provider on a wowup update or re-scan

**To Reproduce**
On a wowup update or re-scan WeakAuras and AddOnSkins reset back the provide to (WowUpHub for WeakAuras) and (curse for AddOnSkins) before the update or re-scan i did set WeakAuras to curse and AddOnSkins to TukUI

**Expected behavior**
Never reset the provider

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10 home 20H2 19042.746
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 2.1.1

**Additional context**

**Comment by jliddev** [comment]
The update process does not affect the provider. The re-scan will go with the first provider by design, and the top priority provider is the Hub.

**Comment by MrUzagi** [comment]
This quite frankly makes the Re-Scan Folders useless after the first time, if you have used any other provider other than the top one. Especially if you use GitHub for addons that have moved there and no longer are maintained on Curse or WoWUI.

For this very reason it would be nice if it was possible to lock an addon from getting re-scanned, or lock to a certain provider. Usually it is not all addons that needs re-scanning.

It would also be nice to see a list of folders that WowUp haven't been able to find a match for. And possibly an option to only scan those unknown folders. I'm a heavy user of addons and I'm still not entirely sure all folders are accounted for, or if there are any duplicates with slightly different names from other providers.

And finally, just so I don't come across as quite as whiny, many thanks for WowUp and all the work you do. :-)

**Comment by Aveelo** [comment]
> 
> 
> The update process does not affect the provider. The re-scan will go with the first provider by design, and the top priority provider is the Hub.

Not to be rude or anything

Can you look again to be sure? The wowup update 2.1.0 (2.0.3 to 2.1.0) did affect two my addon on two pc.

ty for all your hard work

**Comment by jliddev** [comment]
@MrUzagi There is a separate ticket somewhere to fix support for re-scanning addons that were manually added from GitHub idealy that should be remembered. Currently (2.1) you can see folders that were not matched with anything however it does require a rescan.

@Aveelo 
You can provide the logs from options > debug > show log files and we can try to see what happened if you want.

**Comment by Aveelo** [comment]
> 
> 
> @MrUzagi There is a separate ticket somewhere to fix support for re-scanning addons that were manually added from GitHub idealy that should be remembered. Currently (2.1) you can see folders that were not matched with anything however it does require a rescan.
> 
> @Aveelo
> You can provide the logs from options > debug > show log files and we can try to see what happened if you want.

main.log
https://cdn.discordapp.com/attachments/395237164914573313/808913073326915584/main.log

main.old.log
https://cdn.discordapp.com/attachments/395237164914573313/808913068573851688/main.old.log

renderer.log
https://cdn.discordapp.com/attachments/395237164914573313/808913071200010250/renderer.log

**Comment by MrUzagi** [comment]
> 
> 
> @MrUzagi There is a separate ticket somewhere to fix support for re-scanning addons that were manually added from GitHub idealy that should be remembered. Currently (2.1) you can see folders that were not matched with anything however it does require a rescan.

Ah, that explains why I don't see such a list. I haven't done a re-scan since before 2.1. Currently I don't really want to do a re-scan, but perhaps I should anyway, just to see what happens. :-)
