### ISSUE TITLE
Version checks across sources

### ISSUE THREAD

**Issue by Addonman** [WowUp/WowUp#721]
Since you have multiple sources addons can come from and authors dont always post their updates  , especially if they are alfpha version, across all sources would it be possiable to add some sort of check that says you have this version here ( selected source) but author has posted updated version on this source that we cover or something like that.
Also i noticed that i can have version from 1 source and go check for same addon in "get addon" section and see that wowup cant tell that i already have addon installed from another source.

**Comment by jliddev** [comment]
While this is technically a thing that can be done, someone would have to manually marry up all addons across all providers at a central location thus making it not really feasible for me to do.
