### ISSUE TITLE
WowUp does not detect addons added using a symbolic link

### ISSUE THREAD

**Issue by syndenbock** [WowUp/WowUp#723]
**Describe the bug**
When I have addons linked into the AddOns folder, WowUp does not detect them (even after a rescan)

**To Reproduce**
1. Go to your AddOns folder
2. Move an addon folder to another location on your computer 
3. Created a symbolic link to that folder `mklink /d "...\AddOns\addonName" "path\to\moved\folder"`
4. Re-Scan Folders in WowUp
5. The addon will no longer be detected

**Expected behavior**
WowUp should detect the addon just as if the symlink was a normal addon folder

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Version 2.1.1

**Additional context**
Apparently this is supposed to work already, that's why I filed it as a bug instead of a feature.

**Comment by jliddev** [comment]
windows 7?

**Comment by syndenbock** [comment]
Yes, Windows 7

**Comment by jliddev** [comment]
Would need to find some VM to test this on

**Comment by syndenbock** [comment]
Do symbolic links work on Windows 10? If the issue exists on Windows 10 aswell you might not need to find a Windows 7 VM.

**Comment by jliddev** [comment]
I was able to look at detecting symlinks, however, it would then overwrite your symlink when updating/installing

**Comment by syndenbock** [comment]
Personally, that would be fine for me. Basically I want to see when an "official" update for one of these addons is available so I can merge changes into my fork. 
So if you could add a confirmation message when a users wants to update an addon that exists as a symbolic link that should be fine, right?

**Comment by jliddev** [comment]
![image](https://user-images.githubusercontent.com/20467484/107835949-f9ca3a00-6d60-11eb-806c-d5e074c418c0.png)

**Comment by syndenbock** [comment]
That's a great solution too, can't wait to use it :D
