### ISSUE TITLE
[Companion Addon] wowup_data_addon not created

### ISSUE THREAD

**Issue by Road-block** [WowUp/WowUp#724]
**Describe the bug**
Trying to use the companion wowup addon for in-game notifications, the data part of the addon is not created.

**To Reproduce**
1. Use the WowUp desktop application (Windows) to install the WowUp companion addon.
2. Exit the WoW Client (Classic 1.13.6.37497)
3. Press `Check Updates` on the Wowup.io application (v2.1.1)

**Expected behavior**
The `wowup_data_addon` addon should be created with information about my addons and available updates.
Starting the game always shows the `"Data addon is missing"` message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Brave (Chrome based)
 - Version 2.1.1
 - 
**Additional context**
Tried starting the app with admin privileges, with the wow client closed or running, no difference.

**Comment by eggy** [comment]
same thing is happening here.
OS: Windows 10
Browser: Chrome
 Wowup.io application (v2.1.1)

Only difference is I'm using the retail client, not classic
If its of interest, I do not have WoW installed to the default location.

**Comment by linaori** [comment]
Can you add the following files?
 - addons.json
 - renderer.log
 
 You can find the log file via options -> debug -> show log files. 1 directory above that you can find addons.json. These files contain file paths of your windows user. If you don't want those public, you can also send these files to me on Discord.

**Comment by linaori** [comment]
@Road-block has provided me with the errors logs, and I found this:
```
[2021-02-09 17:02:21.851] [error] TypeError: Cannot read property 'includes' of undefined
```
The problem seems to be here: https://github.com/WowUp/WowUp/blob/343577488e1d4037f9a70dd007cfc6a20a456231/wowup-electron/src/app/services/wowup/wowup-addon.service.ts#L103

**Comment by jliddev** [comment]
This appears to be an issue with migration not handling unmatched addons.

**Comment by jliddev** [comment]
Can someone check if this particular error is gone in 2.1.2?

**Comment by eggy** [comment]
@jliddev I can confirm I no longer have the issue in v2.1.2.

**Comment by Road-block** [comment]
I'll chime in as well, 2.1.2 works for creating the data addon.

**Comment by linaori** [comment]
Awesome, thanks for reporting back!
