### ISSUE TITLE
WowUp not finding newly released updates from CurseForge

### ISSUE THREAD

**Issue by cjal95** [WowUp/WowUp#725]
Not sure if this issue is related to how you get data from CurseForge but it feels like WowUp is at least half a day behind CurseForge in updates for addons. Easiest example to show is Raider.IO since it's updated daily, current version on CurseForge is 202102090600 while WowUp only finds 202102080600.

I looked at my other addons and noticed that addons that seems to have got update in the past half a day or so on CurseForge isn't available in WowUp yet.
![BugReport](https://user-images.githubusercontent.com/60397509/107341892-d896ee80-6abf-11eb-8ad9-2a5e7f290420.png)

**Comment by cjal95** [comment]
I've been away for a few hours and saw that Raider.IO had an update when I got back. Curious as I had manually installed the latest version I downloaded the update and it overwrote the todays update with an older 202102082225 update. For curiosity I tried re-scanning folders with the manual addon installed and it only half recognizes it.

**Comment by jliddev** [comment]
This is not an issue with WowUp, but with Curseforge. The data on the website often takes many hours before it will hit the API which is what you check for updates.

The second comment is due to the same thing, you cannot match a fingerprint to one that is not available via some API.
