### ISSUE TITLE
Sort Order by Release Date is wrong

### ISSUE THREAD

**Issue by peorth80** [WowUp/WowUp#727]
**Describe the bug**
The list is not correctly ordered when you click on Released Date

**To Reproduce**
1. Go to Get Addons
2. Enter "rare" in the search
3. Click on "Released at" until the arrow points down (desc)
4. The list is not ordered correctly

**Expected behavior**
The list should be ordered from the newest to the olders, in desc/asc (depending on the arrow direction)

**Screenshots**
![image](https://user-images.githubusercontent.com/16003799/107531045-3815fc80-6b9b-11eb-9843-e81664e6b8e7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.1.2

**Comment by jliddev** [comment]
Sorting changed in 2.2
