### ISSUE TITLE
Sorting changed while using AutoUpdate

### ISSUE THREAD

**Issue by grsanta** [WowUp/WowUp#732]
Through 2.0 after updates were applied the items updated stayed at the top of the list and it was easy to see exactly what was updated.  That remains for manually updating, but now when using AutoUpdate the items are resorting back into the list and is more difficult to see what just updated.  I am hoping the AutoUpdate way can be changed back to how it used to behave.

**Comment by jliddev** [comment]
I think this was actually a bug, you can always sort by "updated at" to see what was most recently updated.

**Comment by grsanta** [comment]
If so the bug was the better option.  I could leave it sorted by status and the updating items would stay at the top until I closed.  If I sort by updated date then I don't actually see as items are updating as they are not at the top of the list.
