### ISSUE TITLE
url install failed with discontinued addons

### ISSUE THREAD

**Issue by zween123** [WowUp/WowUp#740]
hi there!
i get an error when install a discontinued addon via url from wowinterface.com

here the addon i wanted to install
`https://www.wowinterface.com/downloads/info16274-BuffTimeDisplayFixer.html`
the addon still works but was not updated since october 2010, therefore it is in the discontinued and outdated mods section.

i'am using wowup version 2.1.2 on win10-64bit

**Comment by jliddev** [comment]
The issue here is that the WowInterface API itself does not return addons marked as discontinued so we cant get the information to install it.
