### ISSUE TITLE
Option: Disable Tray Icon

### ISSUE THREAD

**Issue by F-Lambda** [WowUp/WowUp#742]
When the program is maximized, there's no need for a tray icon, as its only function is to maximize the program on double click. So, it would be great if the tray icon was disabled completely if it's not set to minimize to the system tray on close.

**Comment by jliddev** [comment]
I don't know that I want to tackle this. Discord, Battle.net, Steam all keep the system tray icon while you're using it.

**Comment by strayge** [comment]
@jliddev 
I understand that case.
Discord, Battle.net, Steam all works at background.

But some people does not hold WowUp at background for auto-updates.
They manually update all their addons (after reading changelog).

For that kind of people tray icon is useless as it only 2 states:
1) app opened and showed on taskbar, so no need for tray icon.
2) app closed and there is no tray icon anyway.

**Comment by linaori** [comment]
> Discord, Battle.net, Steam all works at background.

Just tested this with Discord and bnet, both have an icon in the tray, regardless of whether or not you allow it to run in the background (close to tray). Same goes for apps like spotify and slack. 

My advice: hide your icon tray by default if it's too full.

**Comment by Maia-Everett** [comment]
I support the OP here. I only launch wowup sporadically to update my addons, not keep it running all the time. I launch it, update my addons, and immediately close it. The tray icon is distracting.
