### ISSUE TITLE
TBC-Classic Support

### ISSUE THREAD

**Issue by jliddev** [WowUp/WowUp#743]
We need to make significant changes to support TBC-Classic specific addons.

**Comment by jliddev** [comment]
Waiting to find out more about the TBC client so we can implement it.

**Comment by jliddev** [comment]
TBC is more or less supported at this point

- Curse does not work as they have not added full support yet via API
- WowIterface never supported classic really
- TukUI pending word from Blizz

**Comment by jliddev** [comment]
Updated to work with new Curse flavor

**Comment by jliddev** [comment]
Waiting for the actual TBC release to support that new installation target

**Comment by MightBeChris** [comment]
Can you add a _classic_beta_ option in the client locations list?  You've got retail beta and both PTRs.  But I can't add my TBC beta despite the above saying TBC is supported.

**Comment by linaori** [comment]
Classic beta is mapped to tbc, along with classic ptr
