### ISSUE TITLE
Wrong tab in addon info popup partially selected

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#745]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1754678/109011410-20696880-76b1-11eb-8083-c97d7e40a6f3.png)

**To Reproduce**
1. have an update ready
2. start wowup
3. open the addon popup by clicking on the name

**Expected behavior**
The right side should be highlighted as active tab

OS: windows 10
Version: V2.2.0-beta5

**Extra Info**
This also inconsistently keeps happening for other addons and goes away after clicking on the tab once. It feels like it takes the wrong width into account when different addons have a different popup width

**Comment by jliddev** [comment]
Appears to be an issue with angular material not handling the dialog resize when the content loads.

**Comment by linaori** [comment]
Fixed in 2.2-beta
