### ISSUE TITLE
[FEATURE] Import/Export Mod List

### ISSUE THREAD

**Issue by sporkwitch** [WowUp/WowUp#753]
**Is your feature request related to a problem? Please describe.**
Simple method to export list of currently installed mods that can be imported later (to simplify moving between computers or reinstalling).

**Describe the solution you'd like**
Depending on what data is required to pull a mod, this could be as simple as exporting the mods' URLs, one per line, in a text file, but worst case JSON format would likely be a good one to keep things simple.

For formatting / versioning, could have the first line / entry by the game version (Classic, Retail, Retail PTR, etc.), then the mods after.

Export/Import buttons could be placed next to "re-scan folders" or added to the update dropdown.

**Describe alternatives you've considered**
Backing up the mod folders manually or manually writing down a list of all mods would work, but is less than convenient, especially with how many mods is common to use at once in WoW.

**Comment by jliddev** [comment]
This is more or less the same as #482

**Comment by sporkwitch** [comment]
Apologies, I missed that one when I was looking through before posting
