### ISSUE TITLE
Updated addons and columns

### ISSUE THREAD

**Issue by MuTLY** [WowUp/WowUp#754]
**Is your feature request related to a problem? Please describe.**
When checking for addon updates, the "Updated at" and "Released at" columns generate confusion to the user, like so:
![image](https://user-images.githubusercontent.com/777006/109991608-38f90480-7ce9-11eb-80ae-add5b0e756ac.png)

**Describe the solution you'd like**
"Released at" and "Updated at" need to be fixed. 

"Updated at" should use the latest date timestamp (or whatever) of the addon.
"Released at" should be the first date the addon was released to the public.

I guess it makes more sense.

**Comment by jliddev** [comment]
Thats what they are now?

Updated at is when you updated it,
Released at is when the author released it.

**Comment by MuTLY** [comment]
I see what you mean now, but either way this is so confusing. I was expecting the information being about the addon itself, not about my actions.

**Comment by jliddev** [comment]
Im not sure i understand either, you were thinking the updated at column was when the addon was updated at the provider?

**Comment by jliddev** [comment]
Is there some header you feel would make it more clear?
