### ISSUE TITLE
Memory Leak Issues

### ISSUE THREAD

**Issue by ErikElgerot** [WowUp/WowUp#762]
Have been having issues with WowUp memory leaks in the last week or two. If you leave the client running, it will gradually balloon in memory usage - noticed it at one point in the last few days when it caused WoW to freeze up and crash due to insufficient memory. Checked Task Manager, and WowUp was eating almost 9GB of RAM.

**Comment by linaori** [comment]
There have been a few reports so far but we haven't been able to reproduce it yet.

Can you share the following information?
 - Which addon providers you have enabled (Options -> Addons)
 - A screenshot of your settings under Options -> Application
 - A screenshot of your configured clients (Options -> Clients)
 - Your Windows version, wowup version

Then I have a few more questions:
 - Have you noticed any other behavior that's slightly off?
 - How long is it running when it starts increasing memory usage and do you have an indication of how fast this goes? 
 - How many addons do you have installed?
 - How many addons do you have on auto-update?
 - Are you using alpha/beta channels for addons?
 - Do you have any addons installed that are not available on any of the existing providers? (unknown addon providers in your list)
 - Do you have the ability to test the latest beta client to see if the issue is still present there? [Beta releases can be found here](https://github.com/WowUp/WowUp/releases)

**Comment by ErikElgerot** [comment]
> There have been a few reports so far but we haven't been able to reproduce it yet.

As someone who works in gamedev, I agree that those bugs are the worst! =)

> Can you share the following information?
> 
> * Which addon providers you have enabled (Options -> Addons)

All four are checked (WowUpHub, Curse, TukUI and WowInterface)

> * A screenshot of your settings under Options -> Application

![image](https://user-images.githubusercontent.com/39994730/110783738-1aef4f00-8269-11eb-9a70-e219d2ab8aaa.png)

> * A screenshot of your configured clients (Options -> Clients)

![image](https://user-images.githubusercontent.com/39994730/110783879-45d9a300-8269-11eb-8cd6-2245e0c2ef9e.png)
(everything below those are the same default settings and no PTR or Beta paths)

> * Your Windows version, wowup version

Windows 10 (64-bit), WowUp version 2.1.2, but also happened on the previous version before the client update that was the other day.

> Then I have a few more questions:
> 
> * Have you noticed any other behavior that's slightly off?

Nothing that I've noticed, no.

> * How long is it running when it starts increasing memory usage and do you have an indication of how fast this goes?

Probably quite a while, since I left it in the background/systray as I set it to start on boot semi-recently.

> * How many addons do you have installed?

156 addons on retail, none on classic

> * How many addons do you have on auto-update?

None that I can see/find. I tend to just check the WowUp client when I remember and click update all.

> * Are you using alpha/beta channels for addons?

None at the moment that I can see.

> * Do you have any addons installed that are not available on any of the existing providers? (unknown addon providers in your list)

No, all are listed as curse or wowinterface.

> * Do you have the ability to test the latest beta client to see if the issue is still present there? [Beta releases can be found here](https://github.com/WowUp/WowUp/releases)

Could do, I'll check memory usage every few hours of the stable/release build for a few days, then repeat the same with the latest beta to see if there's any difference.

**Comment by linaori** [comment]
Going to set up my own WowUp to match your settings to see if I can find anything. In the meanwhile if you or anyone else has information to add, please do so.

If anyone else is experiencing memory leaks, please fill in the same questions as above and reply to this issue

**Comment by jliddev** [comment]
Please supply the latest renderer and main log files. Changes were made to the two background update loops in the latest 2.2 beta to see if that fixes the issue.

**Comment by christopherjtaylor** [comment]
Hey there, just wanted to add my experience to this issue. My games started uncharacteristically hitching tonight. Thought I needed to restart my computer, but checked task manager and saw WoWUp was using 17GB of RAM. It grew to 19GB in just the few seconds I was watching it. Happy to provide any details if helpful.

**Comment by jliddev** [comment]
Try using the beta as above and see if it still happens.

**Comment by aggixx** [comment]
>     * Which addon providers you have enabled (Options -> Addons)

WowUpHub, Curse, TukUI, WowInterface

>     * A screenshot of your settings under Options -> Application

![image](https://user-images.githubusercontent.com/510805/113809933-cd161b80-972e-11eb-9721-7a368e26b675.png)

>     * A screenshot of your configured clients (Options -> Clients)
 
![image](https://user-images.githubusercontent.com/510805/113809946-d69f8380-972e-11eb-87ae-1e44f0e0a160.png)

>     * Your Windows version, wowup version

Windows 10 Pro x64 Version 20H2 (OS Build 19042.867)

>     * Have you noticed any other behavior that's slightly off?

No.

>     * How long is it running when it starts increasing memory usage and do you have an indication of how fast this goes?

Both times its occurred it had already been running for multiple hours. Once I've noticed the problem, the memory usage appears to balloon very rapidly. My physical RAM usage would max out, it would crash other programs (WoW etc) freeing up more ram, at which point I check task manager and the RAM usage is climbing at a rate (I would guess) around 50-200 MB/s.

>     * How many addons do you have installed?

46

>     * How many addons do you have on auto-update?

Probably 30-40? I think it got reset when I upgraded to 2.20-beta.21.

>     * Are you using alpha/beta channels for addons?

I was using 2.12 until I upgraded to 2.20-beta.21 after reading this issue. Will let you know if I experience the issue on 2.20.

>     * Do you have any addons installed that are not available on any of the existing providers? (unknown addon providers in your list)

There are no addons in the WowUp list with an unknown provider. I do have other addons that would not be available via those providers, but they are not in the WowUp list.

For what its worth, the second time I had the issue (just now) I had a total of 64GB of committed memory before I killed WowUp. Nearly all of that memory was freed up (60GB+) when I killed WowUp, although that memory was no longer attributed to WowUp in task manager. The first time I experienced the issue the memory was attributed to WowUp in task manager.

**Comment by aggixx** [comment]
[renderer.log](https://github.com/WowUp/WowUp/files/6268977/renderer.log)
[main.log](https://github.com/WowUp/WowUp/files/6268978/main.log)

**Comment by linaori** [comment]
@aggixx so just to make sure, you experienced this issue on 2.1.2? Because the screenshots you've posted are from the beta

**Comment by linaori** [comment]
woopsie!

**Comment by aggixx** [comment]
Yes. So far I experienced it on 2.12 only and then upgraded to the beta.

**Comment by brett1337** [comment]
getting this really really bad the last month or so, grinding my comp to a halt after a couple days, please fix!

**Comment by linaori** [comment]
Workaround is to disable minimize on close, and if WowUp starts up with system, disable the minimize option there as well

<img width="704" height="100" alt="Image" src="https://github.com/user-attachments/assets/933616d2-246b-44c3-b33b-8787f18fa281" />

**Comment by brett1337** [comment]
ya i have definitely done that, i was stunned it was this one app. I feel like if this is still happening all these years later it might be worth prioritizing a fix or having an open issue! Thanks for the reply.
