### ISSUE TITLE
Incorrect Sorting of Addons

### ISSUE THREAD

**Issue by ugurilter** [WowUp/WowUp#764]
When i sort the addons according to Download counts, it still shows the addons with provider "WowUpHub" on top.

**Steps to reproduce the behavior**
1. Go to 'Get Addons'
2. Click on 'Downloads'
3. You'll see that the addons are sorted according to the number of downloads but the ones with "WowUpHub" as provider are above other addons with much higher download numbers.

**Expected behavior**

**Screenshots**
https://prnt.sc/10ivs4f

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by jliddev** [comment]
This is addressed in the beta for 2.2
