### ISSUE TITLE
Sorting by 'Downloads' in "Get Addons" is incorrect

### ISSUE THREAD

**Issue by Protuhj** [WowUp/WowUp#767]
**Describe the bug**
Sorting by the `Downloads` column in the "Get Addons" section seems to be sorting by the alphanumeric value of the string, and not the actual numeric value represented by the value string

**To Reproduce**
1. Go to 'Get Addons' tab
2. Click on 'Downloads' tab to change sorting order
3. Note that addons with hundreds of downloads are above those with billions and millions

**Expected behavior**
With no search filter, `ElvUI` or `TukUI` should be at the top because they have 2 billion downloads, but there are about 50 addons above them.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 2.1.2

**Comment by jliddev** [comment]
This is addressed in 2.2
