### ISSUE TITLE
Changelog tab does not support bbcode

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#768]
![image](https://user-images.githubusercontent.com/1754678/111071719-c998c700-84d7-11eb-883f-24b3c7a00f3f.png)

**Comment by jliddev** [comment]
It _does_ but only for WowI

**Comment by linaori** [comment]
It only doesn't support it for wowi?

**Comment by jliddev** [comment]
wat

**Comment by jliddev** [comment]
Ah i assumed this was for the CF addon im caught up now

**Comment by linaori** [comment]
That explains my confusion, yeah this one is on Wowi already

**Comment by Nils89** [comment]
some line feeds are missing:
![1](https://user-images.githubusercontent.com/23194902/112846216-18348c80-90a6-11eb-8eb6-5ae495eba737.png)
