### ISSUE TITLE
Can't find CurseForge addons of one author

### ISSUE THREAD

**Issue by cremor** [WowUp/WowUp#771]
**Describe the bug**
WowUp doesn't show any addons from the CurseForge author "AzerPUG".

**To Reproduce**
1. Go to 'Get Addons'
2. Search for any of the following: "AzerPUG's Valor ToolTips", "AzerPUG's", "AzerPUG", "valor", "GameUtility", "InstanceUtility"
3. Notice that no addons by AzerPUG are found

**Expected behavior**
Addons should be found.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox latest
 - Version: v2.1.2

**Additional context**
"Install from URL" doesn't work either because CF URLs are not accepted.
If I install "AzerPUG's Valor ToolTips" manually and re-scan the folder it is shown as an unknown addon.

**Comment by linaori** [comment]
The author (AzerPUG) has explicitly requested us to block their addons from being installed through WowUp.

**Comment by cremor** [comment]
Oh, wow. Thanks for the information.
