### ISSUE TITLE
TukUI and ElvUI download count is suspect

### ISSUE THREAD

**Issue by dotted** [WowUp/WowUp#772]
**Describe the bug**
Suspect data received from TukUI causes ElvUI and TukUI to always be sorted at the top when listing by downloads as they are both listed as having 2 billion downloads.

**To Reproduce**
1. Ensure TukUI provider is enabled
2. Go to 'Get Addons'
3. Click on 'Downloads' column header to have it sorted descending
4. See both TukUI and ElvUI having 2 billion downloads.

**Expected behavior**
I would expect WowUp to ignore suspect data like this, especially for download count as that can give addons undue exposure to people browsing new addons and simply using download count as the metric to what they are going to install.

**Screenshots**
![image](https://user-images.githubusercontent.com/136996/111369807-c2201c00-8697-11eb-83bb-1f0ee6dc0d4a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - WowUp version: 2.2.0-beta.12

**Additional context**
When seeing the exact API response of `https://www.tukui.org/client-api.php?ui=tukui` and `https://www.tukui.org/client-api.php?ui=elvui` the exact download count for both is `2147483000` a number suspiciously close to a signed 32-bit integer maximum of `2147483647`. The 3rd most downloaded addon on TukUI is AddOnSkins at a mere 2 million downloads, furthermore the top most downloaded addon on CurseForge is DBM with 326 million downloads increasing my suspicion that the download count is suspect.

**Comment by jliddev** [comment]
Talked with a member of the their team, they believe the data to be valid enough. Seems fine as we know they have been around for many years and are very popular. If this were some random addon i'd be more inclined to do something.

**Comment by dotted** [comment]
Some food for thought: The TukUI website as it exists today was created from scratch as they apparently had no backups and previous version had been entirely wiped by a malicious actor. The new site was launched around July 30th 2017 that means the following:

* Average hourly downloads of both TukUI and ElvUI since July 30th 2017 (31848 hours ago as of writing): (2147483000 downloads * 2 addons) / 31848 hours = **134858.264255 downloads per hour**
* Average hourly bandwidth requirement for latest version of TukUI and ElvUI:  134858.264255 downloads per hours * 45339296 total download size of TukUI and ElvUI in bits = **6.11437876 Terabits per second**.

Now they could have been able to perfectly reconstruct all their data through internet archives, unfortunately I don't know when they started tracking their number of downloads, but to be as charitable as possible lets say they started on the day World of Warcraft first launched, November 23rd 2004:

* Average hourly downloads of both TukUI and ElvUI since November 23rd 2004 (143016 hours ago as of writing): (2147483000 downloads * 2 addons) / 143016 hours = **30031.3671198 downloads per hour**
* Average hourly bandwidth requirement for latest version of TukUI and ElvUI:  30031.3671198 downloads per hours * 45339296 total download size of TukUI and ElvUI in bits = **1.36160104 Terabits per second**.

And that's just the average numbers, you'd think the numbers would be much higher during expansion launches and major content patches.

So considering all this I remain highly sceptical of the download numbers they claim. But that said, if their team insists the numbers are accurate then so be it.

**Comment by AcidWeb** [comment]
Download counts for both projects broken long time ago and nobody care enough to fix them. Returned value is obviously wrong and too big to be real but even if they would return correct ones they would still be on the top. We talking about ElvUI.

**Comment by kodewdle** [comment]
Well anyway, let me say you're welcome! ✌
For the wonderful world you know 🌎
Hey, it's okay, it's okay, you're welcome! 💕

**Comment by jliddev** [comment]
Moana was a solid movie for what it's worth.

**Comment by ugurilter** [comment]
Even today, if you look at the number of downloads from the same api you will see that the number of downloads is not changing at all and is set to a hardcoded value big enough so that no other addon can pass it soon.

```json
{ "name": "Tukui", "author": "Tukz", "url": "https://www.tukui.org/downloads/tukui-20.17.zip", "version": "20.17", "changelog": "https://www.tukui.org/ui/tukui/changelog", "ticket": "https://git.tukui.org/Tukz/Tukui/issues", "git": "https://git.tukui.org/Tukz/Tukui", "id": -1, "patch": "9.0.5", "lastupdate": "2021-03-10", "web_url": "https://www.tukui.org/download.php?ui=tukui", "lastdownload": "2021-04-01 13:50:01", "donate_url": "http://www.tukui.org/support.php", "small_desc": "Minimalistic and lightweight world of warcraft user interface", "screenshot_url": "https://www.tukui.org/images/screenshots/t18.jpg", "downloads": 2147483000, "category": "Full UI Replacements" }```
