### ISSUE TITLE
Linux - UI not completely loading

### ISSUE THREAD

**Issue by kubuntugamer** [WowUp/WowUp#773]
**Describe the bug**
Since beta 6 of version 2.2.0, when launching the WowUp application on Linux/Kubuntu, the UI does not populate with objects(see screenshot), and remains at a "Loading" prompt. This behviour was not experienced with beta 5 and prior.

**To Reproduce**
Launch WowUp appication

**Expected behavior**
The expected behaviour is that the UI populates with clickable objects

**Screenshots**
![Screenshot_20210317_131529](https://user-images.githubusercontent.com/52578831/111520427-1540b000-8726-11eb-998b-f7150e060940.png)

**Desktop (please complete the following information):**
Kubuntu 20.10
Microsoft Edge for Linux/Google Chrome

**Additional context**
I experience the same behaviour on both my desktop PC and my laptop. If there is some means i can use to get debug information to submit please instruct me how to do so.

**Comment by jliddev** [comment]
Reproduced locally, will look into

**Comment by jliddev** [comment]
Give beta 13 a try

**Comment by kubuntugamer** [comment]
> Give beta 13 a try

it's working. UI populated and I was able to click around on the interface and set and save options.
