### ISSUE TITLE
White block in changelog

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#775]
related changelog: https://addons-ecs.forgesvc.net/api/v2/addon/306489/file/3244822/changelog

![image](https://user-images.githubusercontent.com/1754678/111812271-3ea13d80-88d8-11eb-9995-c68cc2e88b97.png)

![image](https://user-images.githubusercontent.com/1754678/111812190-2a5d4080-88d8-11eb-8048-41d70cd782e0.png)

**Comment by Nils89** [comment]
fixed, can be closed
