### ISSUE TITLE
Cant download from Curse (with url) and cant find AddOn in Curse.

### ISSUE THREAD

**Issue by JFEspanolito** [WowUp/WowUp#779]
**Describe the bug**
In Get Addons Finder, cant see addon's from Curse.
If i put the url, mark errors.

**To Reproduce**
1. Go to 'Get Addons'
2. Click on 'Finder'
3. Write 'addons in curse' ( example showmemyheal )
4. See error (addon dont show)

or

1. Go to 'Get Addons'
2. Click on 'Install from URL'
3. Write 'url' ( example https://www.curseforge.com/wow/addons/showmemyheal )

**Screenshots**
![imagen](https://user-images.githubusercontent.com/6903502/111922608-63c0b800-8a60-11eb-8612-bb096ce6c5b8.png)
![imagen](https://user-images.githubusercontent.com/6903502/111922613-67543f00-8a60-11eb-804a-22611ed18c59.png)
![imagen](https://user-images.githubusercontent.com/6903502/111922614-6a4f2f80-8a60-11eb-94fd-1fbccd2ca546.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 2.1.2

**Comment by Nils89** [comment]
You are searching for Retail, but the Addon is marked as Classic. 

Change from Retail to Classic (top left corner) and try again.

**Comment by jliddev** [comment]
Could probably improve that error message.
