### ISSUE TITLE
"Show Columns" black text in Get Addons 

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#783]
![image](https://user-images.githubusercontent.com/1754678/112315979-f6ed2e00-8caa-11eb-9c70-669be404aed7.png)

For reference what My Addons looks like:
![image](https://user-images.githubusercontent.com/1754678/112316076-0e2c1b80-8cab-11eb-8b90-03cc1f46cfc1.png)

**Comment by Nils89** [comment]
Fixed, can be closed
