### ISSUE TITLE
Reinstalls deleted addon

### ISSUE THREAD

**Issue by DjRicko** [WowUp/WowUp#787]
If you manually delete an addon aka. deleting the actual folder insides Interface/AddOns, WowUp will auto install it again once an update would be available for it. I asssume This is caused by WowUp just storing a database of installed addons and which version they should currently be on. So it will do nothing for a while, untill the version number of that addon changes and will then suggest to update the addon, even tho the folder is actually deleted.

**Comment by linaori** [comment]
if you manually remove the addon, you have to do a re-scan in wowup to detect the change. This behavior is currently working as intended. My advice is to not mess around with the addon folders manually
