### ISSUE TITLE
Add Unknown Provider Generic Help

### ISSUE THREAD

**Issue by jliddev** [WowUp/WowUp#791]
Add some generic info about why an addon may be marked unknown with a tooltip

**Comment by Nils89** [comment]
works, but tooltip is not centered and maybe add this tooltip also if hovering the provider "Unknown"? And the "Unknown" is not translated.

![Bildschirmfoto 2021-03-29 um 15 40 43](https://user-images.githubusercontent.com/23194902/112845498-35b52680-90a5-11eb-9850-e342a6cb54ca.png)
also for code repos:
![Bildschirmfoto 2021-03-29 um 15 40 47](https://user-images.githubusercontent.com/23194902/112845556-42397f00-90a5-11eb-8a12-2529fcd1e726.png)

**Comment by jliddev** [comment]
Hmm, to add a tooltip to that cell we have to make a custom one, which has other implications

**Comment by jliddev** [comment]
ohh i get it now, lets move it to the same thing as the code repo

**Comment by jliddev** [comment]
Changed it to be similar 
![image](https://user-images.githubusercontent.com/20467484/113730481-8f2cdf00-96bd-11eb-8130-f2916fb9dd99.png)

**Comment by Nils89** [comment]
Looks Good :) 

can you also center the text?

**Comment by jliddev** [comment]
Maybe
![image](https://user-images.githubusercontent.com/20467484/113732739-758c9700-96bf-11eb-91ff-90df1100d476.png)

**Comment by Nils89** [comment]
Look goods, only the word "Unknown" under Provider is not translated

**Comment by jliddev** [comment]
Created #816
