### ISSUE TITLE
Missing translation "No Rows To Show"

### ISSUE THREAD

**Issue by Medoke** [WowUp/WowUp#795]
Missing translation "No Rows To Show"

**To Reproduce**
1. Go to 'My Addons' tab
2. Search for something nonexistent.
3. No Rows To Show.

**Expected behavior**
No Rows To Show must be TRANSLATED.

**Screenshots**
![зображення](https://user-images.githubusercontent.com/72464426/112702462-39c22800-8e9c-11eb-9fc3-3d76838f9d31.png)

**Comment by Nils89** [comment]
fixed, can be closed
