### ISSUE TITLE
TBC Classic Beta

### ISSUE THREAD

**Issue by hepkat** [WowUp/WowUp#804]
**Describe the bug**
TBC Classic Beta addons have now been enabled for testing. The WowUp client doesn't detect the beta client properly for this iteration of beta. The install path of TBC beta is `%programfiles(x86)%\World of Warcraft\_classic_beta_`

**To Reproduce**
1. Options
2. Beta -> Select (path)
3. Enter `%programfiles(x86)%\World of Warcraft\`
4. Receive error
> Alert
> Unable to set "C:\Program Files (x86)\World of Warcraft\" as your beta folder.
> Path not found: "C:\Program Files (x86)\World of Warcraft\_beta_WowB.exe".
5. Same result if I select the proper path of `%programfiles(x86)%\World of Warcraft\_classic_beta_`

**Expected behavior**
Should detect `_classic_beta_` path.

**Screenshots**
![image](https://user-images.githubusercontent.com/25138984/113243669-4a8de780-9268-11eb-9626-77c5a8574385.png)
![image](https://user-images.githubusercontent.com/25138984/113243736-6b563d00-9268-11eb-8542-5025407bb856.png)
![image](https://user-images.githubusercontent.com/25138984/113243644-3e098f00-9268-11eb-8560-77f39565d1e2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A
 - Version N/A

**Comment by CyanoHao** [comment]
Fixed in #803.

Here is a pre-built Windows portable app: https://nowar.lanzous.com/b01i51i6f (WowUp-2.2.0-beta.16-burning-beta-preview.exe)

**Comment by jliddev** [comment]
We can't be posting non official builds here. Will break the update path for users that pick it up.

**Comment by drohm** [comment]
Is the current Beta section in Option for retail?  If so, I'd suggest a separate section for Classic Beta, since the path is different and the exe is different as well:

- C:\Program Files (x86)\Blizzard\World of Warcraft\_classic_beta_\WowClassicB.exe

For shits and giggles, I tried making a link from _beta_ to _classic_beta_, but it errored out because the application is looking for 'WowB.exe'.

**Comment by hepkat** [comment]
> Is the current Beta section in Options for retail? If so, I'd suggest a separate section for Classic Beta, since the path is different and the exe is different as well:
> 
> * C:\Program Files (x86)\Blizzard\World of Warcraft\_classic_beta_\WowClassicB.exe
> 
> For shits and giggles, I tried making a link from _beta_ to _classic_beta_, but it errored out because the application is looking for 'WowB.exe'.

Probably a good idea.

**Comment by jliddev** [comment]
This was completed for testing in 2.2 beta 17
