### ISSUE TITLE
Addon using Github provider picking up pre-release versions

### ISSUE THREAD

**Issue by thirdgencubfan** [WowUp/WowUp#807]
**Describe the bug**
I have WeakAuras2 added to WoWUp using a Github URL, but WoWUp keeps picking up "bc-alpha-1" as the latest release, when in fact it should be "3.2.2" as of this writing.

**To Reproduce**
1. Click on "Install from URL", paste Github URL for WeakAuras 2 (https://github.com/WeakAuras/WeakAuras2) into "Install Addon URL" prompt.
2. Click "Import" and then "Install"
3. After install process finishes, go to "My Addons" tab
4. See WeakAuras installed as "WeakAuras-bc-alpha-1-bc.zip"

**Expected behavior**
The install from Github URL should have installed 3.2.2 (as of this writing), presumably from https://github.com/WeakAuras/WeakAuras2/releases/latest.

**Screenshots**
Screenshot showing WeakAuras installed as "bc-alpha-1" instead of 3.2.2: https://i.imgur.com/oKQW0P2.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - WoWUp version 2.1.2

**Comment by jliddev** [comment]
App should start checking for -bc for bc builds since it's the new thing

**Comment by jliddev** [comment]
Should be fixed in latest beta
