### ISSUE TITLE
Windows certificate store integration

### ISSUE THREAD

**Issue by PampuTV** [WowUp/WowUp#808]
Hi there,

many networks are using a network firewall with active ssl inspection. To avoid problems in communication produced by an ssl inspection, most applications use the Windows certificate store to check for trusted certificates.

WowUp doesn't use the Windows certificate store. As a result of that installing and updating addon updates isn't possible as long as the network firewall is doing an ssl inspection.

Feature request: integrate the Windows certificate store into the WowUp client.

Some information about ssl inspection:
Explained in detail on many websites, for example here: https://sectigostore.com/blog/what-is-ssl-inspection-and-how-does-it-work/.
Short: https communication is an encrpyted communication based on certificates. When a network firewall does an ssl inspection, the network firewall decrypts this communication with its own ssl certificate. Because of that an application that trys to access the internet over https doesn't see the ssl certificate of the targeted website (e.g. tukui.org). The application only see the ssl certificate of the network firewall. If implemented right, the ssl certificate of the network firewall is installed into the Windows certificate store. Because of that every application that can read and check the Windows certificate store, doesn't have a problem with ssl inspection. 
SSL inspection is necessary to highly increase the security of your network. If your network firewall can't decrypt the encrpyted communication, it neither can't check for viruses or anything like that download from a website.

Thanks a lot.

Kind regards,
Dominik

**Comment by linaori** [comment]
@jliddev I found this package, I'm not 100% sure if this solves the problem as I don't know enough of SSL setups: https://www.npmjs.com/package/win-ca

Nodejs seems to have support for it:
 - https://github.com/nodejs/node/commit/3aa17e4e513f0bf281ee754eb58a33b737be2867
 - https://github.com/nodejs/node/commit/33012e9866cbb43db562dd6a3feffe8cd4ec5838

**Comment by yoshimo** [comment]
I would consider this a non-issue.
TLS Inspection is more common in a corporate network, where you shouldn't be updating wow addons anyway.
If the government is intercepting your connections to Curse, Wowinterface, Wowhub and whatever else will be added later, you are in trouble anyway and WowUp shouldn't comply with such crazy networks.

**Comment by PampuTV** [comment]
Well, I openend this as a feature request and not an issue.
But, I'm not the only one who has this problem. There are some friends of mine having the same problem.
At the present time of smart home and home office there are an increasing number of home users that are using a network firewall including TLS inspection.

**Comment by linaori** [comment]
It doesn't seem like a big change if the above package is sufficient. In the end it's up to @jliddev to decided whether or not something gets added. I can imagine If it's more work to implement that this ticket will be on the backlog for a while, or closed.

**Comment by jliddev** [comment]
I added that package in beta 16 you should some output saying it loaded

**Comment by PampuTV** [comment]
Already on beta 17. The package added in beta 16 didn't change anything. I'll take a look in the debugs if I can see something about the package.
