### ISSUE TITLE
Cannot find addon even though it is available on CurseForge

### ISSUE THREAD

**Issue by Hemario** [WowUp/WowUp#810]
The addon in question is https://www.curseforge.com/wow/addons/azerpugs-valor-tooltips.

**To Reproduce**
1. Go to "Get Addons"
2. Search for "AzerPUG's ToolTips"
3. Look for the addon
4. Can't find the addon :(

**Expected behavior**
Addon should be found in the list

**Comment by jliddev** [comment]
The author has requested that we not allow their addons on WowUp.
