### ISSUE TITLE
Update all clients is unavaiable if there are no updates for the current client

### ISSUE THREAD

**Issue by liamcooper** [WowUp/WowUp#813]
**Describe the bug**
I currently use wowup for retail and classic addons, there's a bug in the application that doesn't allow you to update all clients if the current client that you have selected doesn't have any updates, you have to select another client for this option to become available.

**To Reproduce**
I have updates for my classic client.
When the app loads I have retail selected as default.
Retail doesn't have any updates, so the update dropdown is disabled.
If I select classic from the dropdown, then the update option is enabled, and I can choose to update all clients.

**Expected behavior**
I would expect the dropdown option to update all clients to be available regardless of whether the current client doesn't require any updates.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox (not sure why it's relevant)
 - Version: 87.0

**Additional context**

**Comment by liamcooper** [comment]
I actually have screenshots of this now.

This is retail client with an update, you can see the dropdown is enabled:
![image](https://user-images.githubusercontent.com/7249112/113837330-a46d4080-9785-11eb-810c-bb2e03f916ba.png)

And this is classic client without an update, dropdown is disabled:
![image](https://user-images.githubusercontent.com/7249112/113837374-b18a2f80-9785-11eb-8b0c-1062d1b34bf9.png)

**Comment by linaori** [comment]
Just throwing an idea in here because I think we might have to look into the dropdown in general. It could be something like this now that we support multiple installations of 1 client with custom names:
```
 [ Update <client a> | V ]
   | update <client a>   |
   | update <client b>   |
   | update <client c>   |
   | update all clients  |
 ```
 
 And I could imagine that some people would want to always update everything, and some want a different client selected by default.

**Comment by jliddev** [comment]
Hmm, feels like that dropdown would be the same as just going thru your client dropdown and hitting update all.

**Comment by linaori** [comment]
Correct, it would just visually be more clear what it does with less clicks

**Comment by jliddev** [comment]
![image](https://user-images.githubusercontent.com/20467484/114493506-4b1b6c00-9be0-11eb-801d-3783382009fc.png)
The dropdown can now be disabled independently of the current client button
