### ISSUE TITLE
An error occured matching your addon folders with WowInterface

### ISSUE THREAD

**Issue by ManuDinicola** [WowUp/WowUp#821]
**Describe the bug**

Some addon are ignored and cannot be update to the following error : An error occured matching your addon folders with WowInterface

**Screenshots**
<a href="https://ibb.co/KKHfjr5"><img src="https://i.ibb.co/MBLtDCg/2021-04-10-16h08-20.png" alt="2021-04-10-16h08-20" border="0"></a>

**Desktop (please complete the following information):**
Windows  10
Wowup version 2.1.3

**Comment by jliddev** [comment]
These types of addons should now be marked in the latest beta if you want to give it a try https://github.com/WowUp/WowUp/releases
