### ISSUE TITLE
Allow "ignored" addons to be reinstalled after "re-scan folders"

### ISSUE THREAD

**Issue by fireymerlin** [WowUp/WowUp#828]
**Is your feature request related to a problem? Please describe.**
After using "re-scan folders" any addon that is marked "ignored" won't let me reinstall by right clicking on the name.  I have to go to the "get addons" tab, search and install that way.

**Describe the solution you'd like**
I'd like to be able to right click on an "ignored" addon in the "my addons" tab and select "re-install".

**Describe alternatives you've considered**
I have to search for the addon in "get addons".

**Additional context**

**Comment by jliddev** [comment]
These addons are probably ignored because they are set to Unknown provider. Meaning we dont have enough information to know what it is, so there is no way to re-install it.
