### ISSUE TITLE
Addon names in WoWUp are sometimes broken if they contain color codes in them.  (|c|r)

### ISSUE THREAD

**Issue by Xruptor** [WowUp/WowUp#847]
There are some addons out there that have colorized some of all of the addon name in the TOC file.  In game they work fine when you look at the Addon list as they colorize correctly.  However, it seems that sometimes WoWUp has complications displaying addon names properly in the applications addon list.  I've tried this with multiple addons and it always breaks it due to the color codes.  You can create dummy addons as well with various color codes and it also still breaks it.  It's odd as sometimes it does it and sometimes it doesn't.  It seems to work when you forcefully do a rescan briefly.  Yet when you restart the client the name is broken again.

I believe what needs to be done is the WOWUp client needs to remove or parse the color codes properly to display the true name of the addon.

Example: 
https://github.com/Xruptor/nSpellTracker
or
https://github.com/lithammer/nSpellTracker

Displays like this on the WoWUp client.
![image](https://user-images.githubusercontent.com/202515/116256306-11e70e00-a741-11eb-80e5-f0819319cf84.png)

**Comment by jliddev** [comment]
What version of WowUp do you have? it works fine. 
![image](https://user-images.githubusercontent.com/20467484/116258954-02fd5d00-a73b-11eb-82fd-0cb78610e405.png)

**Comment by Xruptor** [comment]
Version 2.2.0
![image](https://user-images.githubusercontent.com/202515/116260965-2fb67200-a745-11eb-8e48-72888e361a73.png)

**Comment by Xruptor** [comment]
> What version of WowUp do you have? it works fine.
> ![image](https://user-images.githubusercontent.com/20467484/116258954-02fd5d00-a73b-11eb-82fd-0cb78610e405.png)

Doesn't seem to happen all the time.  Which is why I put "sometimes".  Seems to happen when the addon first loads up or after it refreshes.  Rescanning the addons at times will work or not.  It's completely random.  Though I will say about 7 out of 10 times it does occur on my end.  Possibly because I'm actively coding in the project?  Maybe a GitHub or folder scanning issue?

**Comment by jliddev** [comment]
Its just a basic regex replace, should always be the same. If you identify something that breaks it every time i am happy to fix it.

**Comment by Xruptor** [comment]
> Its just a basic regex replace, should always be the same. If you identify something that breaks it every time i am happy to fix it.

I'll keep an eye on it.  Oddly after doing rescan folder a couple of times it no longer seems to be doing it.  It now displays properly.  So I'm not entirely sure what's going on.  If it does it again I'll let you know.
