### ISSUE TITLE
In-line search, spaces and wildcards

### ISSUE THREAD

**Issue by harl** [WowUp/WowUp#849]
WowUp's search functionality seems to behave oddly, in an inconsistent manner, or at least its behaviour is unclear to me.

Search for "boss" and the results include "Deadly Boss Mods (DBM)" and "BossSwingTimer". (That's expected.)
Search for "wigs" and the results **don't** include "BigWigs" and "LittleWigs". (That's definitely not expected.)
Search for "location" and it shows a bunch of addons containing "location" in their name, but **not** Broker_Location, even though searching for "broker_location" finds it just fine, and also other terms can be found in underscore-combined addon names just fine. (This is inconsistent and confusing and not expected.)

Search for "stimei" and it finds addons by the author "LetsTimeIt". (random example really) (This is OK.)
+Search for "anzil" and it doesn't find "Stanzilla" at all, it has to be exactly "Stanzilla" to find his addons. (Why?)

Search for "macro tools" and it includes all kinds of addons, that don't even have to have "macro" or "tool" in their name (but probably in their description). Adding quotes around the term seems to do nothing, same with wildcards * and ?
(This "works", but should definitely support some way for an exact search, including quotes and/or wildcards.)

Altogether, this makes me feel like I can't trust the search results, especially when it claims to find nothing at all.

(Regular expressions even seem to confuse the server, because they aren't parsed correctly.)

**Comment by jliddev** [comment]
Assuming you're looking for CurseForge addons, you're using their search the same as their client and their website. Not a custom search that we created. Feel free to make a ticket for them to fix it, the community would thank you.
