### ISSUE TITLE
No Agent Path

### ISSUE THREAD

**Issue by alexriedl** [WowUp/WowUp#852]
**Describe the bug**
Starting with version 2.2.0 application seems to not start correctly using app image on linux. I am directed to the options tab with a warning no WoW installations found. 

**To Reproduce**
1. Usage appimage version 2.1.3 and install multiple addons
2. Update to 2.2.0
3. Launch application

**Expected behavior**
Application starts (does any config migration needed) and I am presented with the list of addons I have installed

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 2.2.0

**Additional context**
In the logs I see
`09:28:38.375 › Cannot import wow installations, no agent path`
and then later
`09:28:40.762 › Skipping addon load installation unknown`

In preferences.json i do see `"blizzard_agent_path": "",` but not sure exactly what that should be set to.
No other obvious errors

Interestingly I found this in the code:
```
tap((blizzardAgentPath) => {
          // On Linux this will be empty, as we dont know where the blizz database is
```

**Comment by jliddev** [comment]
This is by design. There is no way for the app to guess where your blizzard product database is on Linux. Linux users must manually add the exe they use to play the game.

**Comment by alexriedl** [comment]
In case anyone else stumbles onto this issue, looks like it can be set to the following to work:
`"blizzard_agent_path": "<WINE PREFIX PATH>/drive_c/Program Files (x86)/World of Warcraft/Launcher.db",`

**Comment by jliddev** [comment]
Or... just select the exe from the UI
