### ISSUE TITLE
Support alternative github asset names

### ISSUE THREAD

**Issue by SamMousa** [WowUp/WowUp#863]
**Is your feature request related to a problem? Please describe.**
We use the bigwigs/packager github action for building our release.
It creates a file called `Addon-v1.0.0-bcc.zip`.

**Describe the solution you'd like**
I'd love for this file to be recognized by the wowup client.

**Describe alternatives you've considered**
Upload multiple duplicate asset files with different names to accommodate the different clients.

**Additional context**
We might also want to be in the wowuphub!

https://github.com/lantisnt/ClassicLootManager

**Comment by linaori** [comment]
Currently `-classic` and `-bc` are supported. I think it would make sense to support the same suffixes as with the toc files though. This means adding `bcc` for tbc, and `mainline` for retail.

Working example in the 2.3-beta: https://github.com/WowUp/WowUp.Addon/releases/tag/1.0.0

**Comment by eidota** [comment]
Please add the support for -bcc files. There are a number of otherwise up to date addons that cant be handled by the manager.

**Comment by linaori** [comment]
@eidota have you tried the beta, as I mentioned this is working for 2.3.1-beta?

**Comment by eidota** [comment]
Ah your link took me to ingame addon, i didnt see you were referencing the beta for the manager. Installed it now and it works like it should. Thanks!

**Comment by linaori** [comment]
Awesome, we're working towards releasing this version soon, so hopefully that solves the issue permanently.

**Comment by linaori** [comment]
@SamMousa can you confirm that this is now working for you in the latest version?
