### ISSUE TITLE
Addon search using the exact name showing my result far down the list

### ISSUE THREAD

**Issue by brittyazel** [WowUp/WowUp#865]
**Describe the bug**
I am the author of the addon Enhanced Raid Frames, and when I search my addon name, using the exact name of the addon, it shows up 26th in the list. Everything above it has more downloads, yet none of them come even close to matching the name. I believe whatever algorithm is used to populate the order is prioritizing download count over name a bit too aggressively.

**Expected behavior**
Using the exact name of an addon should result in it being first on the list. An exact match should take precedence over download count.

**Screenshots**
![Screenshot 2021-05-15 093626](https://user-images.githubusercontent.com/3747347/118371365-290b6580-b561-11eb-88a6-e821763cc1fc.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.2.1

**Comment by linaori** [comment]
The search goes through Curse, so we use whatever they return. In theory we can do a smart sort over the results though, because I've encountered this specific issue several times before with a bunch of addons. @jliddev do you think a custom sort over the results would be an option?

**Comment by brittyazel** [comment]
Oh I didn't know that. Thanks for the info. It seems like a custom sort would be a big boon and give more control to WoWUp. Perhaps it could be extended to live-resort based on download count, name, date, etc. And, honestly, I'm very skeptical that this will be fixed on the CurseForge side.
