### ISSUE TITLE
Case insensitive sorting of addons

### ISSUE THREAD

**Issue by Karakaz** [WowUp/WowUp#875]
**Is your feature request related to a problem? Please describe.**
Slightly annoying when the 'aux' addon is listed at the bottom even though it starts with 'a'.

**Describe the solution you'd like**
Sort alphabetically but case insensitive.

**Additional context**
![image](https://user-images.githubusercontent.com/5980958/118950610-a3b9f380-b95a-11eb-902d-dfe055a2aad6.png)

**Comment by jliddev** [comment]
Changed 
![image](https://user-images.githubusercontent.com/20467484/119289799-e0af1000-bc10-11eb-8c90-8269ffd4261d.png)

**Comment by Karakaz** [comment]
Just updated the application. This works if explicitly sorting by name, but as a secondary sort (sorting by `Status` and eveything is up to date), the sorting of addons is still case sensitive.

**Comment by Karakaz** [comment]
Thanks for following this issue through :)
