### ISSUE TITLE
Dragging a column out of the screen will remove it until you restart the app

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#876]
**Describe the bug**
WowUp: 2.3.0

When dragging the columns out of the window, they will be removed from the table. You can't get them back until you restart the app.
![W7AHoU9enH](https://user-images.githubusercontent.com/1754678/118958174-74f34b80-b961-11eb-9d8b-9c13425b8e1c.gif)

There's no option in the right click menu that defines this behavior either:
![image](https://user-images.githubusercontent.com/1754678/118958266-8d636600-b961-11eb-8feb-6270d0013512.png)

**To Reproduce**
1. Go to my-addons or get-addons
2. Drag columns out of the app

**Expected behavior**
Either make it work like the hiding column functionality, or not remove them (probably the easiest) making it a column sort only. The column sort seems to be stored in the preferences, removing them does not.

**Comment by jliddev** [comment]
For the record, that top video is hilarious.
