### ISSUE TITLE
Ubuntu 20.04 WowUp 2.2 and above cannot add WOW install

### ISSUE THREAD

**Issue by markone89** [WowUp/WowUp#877]
Dear All,

I have a interesting problem with all of the WowUP subversions from 2.2 and above.
When I open up the app, it cannot detects the wow install folder path. When I try to re-pick the folder I cannot choose it the Nautilus only opens the selected folder.
When I launch the 2.1.3 version everything looks fine, and it's working as excepted. From the past months I'm using this version for workaround.
In the syslog I found only the following error entry:

May 20 17:16:26 --.------ org.gnome.Nautilus[10377]: 17:16:26.622 › Cannot import wow installations, no agent path

Operation system: Ubuntu 20.04

Can anyone help me please? This is very frustrating :D

**Comment by catthou** [comment]
When you 'pick' wow it wants you to select the Wow.exe (or WowClassic.exe as the case may be) - are you able to select it and hit 'open' in the file picker? If not, what's stopping you? And if so, what happens in WowUp immediately after that?

**Comment by markone89** [comment]
I'm sorry maybe i was not write well the proble.
So....I'm using a Ubuntu 20.04 with kernel 5.8 wine 6.0 for play WOW Game.
everything works well from the past october. I refrashed every addon with WoWUP. It worked fine.
After an update, (when the 2.2 version released), the program cannot detect non of the installed game folder(s) I played classic aswell.  I tried many times to rescan the folder only the message above from syslog showed me somewhow the WoWUp try to call the Nautilus in an unusal way.
In 2.1.3 everything works fine (using daily).
Can anybody help me or I will have to cehck for a another program which will goes?

**Comment by linaori** [comment]
@markone89 have you tried this, and fill in the path to your wow executable?

![image](https://user-images.githubusercontent.com/1754678/119224997-7d828800-bb01-11eb-8eb0-364b1542e5a8.png)

**Comment by markone89** [comment]
It want to select the wow install folder path. where it can look for the _retail_ folder

**Comment by markone89** [comment]
Yes i tried and it shows only Open and cannot select any folder...In the version 2.1.3 I can select the folder or open it to select the subfolder.
According to syslog something not parametered well in the WoWup: org.gnome.Nautilus[10377]: 17:16:26.622 › Cannot import wow installations, no agent path

**Comment by linaori** [comment]
Can you add a screenshot of what it looks like when you're trying to select the wow client executable?

**Comment by markone89** [comment]
![Uploading wowup.png…]()

**Comment by markone89** [comment]
![wowup](https://user-images.githubusercontent.com/57287248/119225321-617fe600-bb03-11eb-90fc-e69ad4dcadba.png)

**Comment by markone89** [comment]
> ![wowup](https://user-images.githubusercontent.com/57287248/119225321-617fe600-bb03-11eb-90fc-e69ad4dcadba.png)

Megnyitás means Open and not Select

**Comment by linaori** [comment]
Open the directory and select the wow executable

**Comment by linaori** [comment]
In the windows explorer you get this, not sure if something like this is possible in Nautilus 
![image](https://user-images.githubusercontent.com/1754678/119225619-018a3f00-bb05-11eb-9219-dfc944267a1d.png)

**Comment by markone89** [comment]
OMG....Thank you very much that helped..maybe I should read the manual first better, cause I did not except I should choose the exe..Strange because below 2.2 you should choose the folder, and also I shows locate the folder...

Thank you very much for your help I appreciate it :)

**Comment by linaori** [comment]
> Strange because below 2.2 you should choose the folder, and also I shows locate the folder...

This was done to support multiple clients. This way you can have multiple Retail clients or multiple classic clients

**Comment by markone89** [comment]
Understand, thank you very much :) Nice to know this also :)
