### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by Dillonzer** [WowUp/WowUp#878]
**Describe the bug**
When trying to download or update I am running into the following error: `Unable to get local issuer certificate`

**To Reproduce**
1. Open up WoWUp
2. Try to download or update an addon

**Expected behavior**
Download / Update should be applied

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Windows Feature Experience Pack 120.2212.2020.0

**Additional context**
- I'm assuming this is due to not forcing TLS1.2? This is happening on a Work PC so I'm assuming there is specific ports it's trying to use that are unsecure.
- Also seems to only happen when using Curse as the provider.

**Comment by jliddev** [comment]
We have had this issue in the past you probably have some kind of custom root certificate since its  work machine.

**Comment by Dillonzer** [comment]
Thanks @jliddev. Do you know if there is any work-around? I'm assuming not but since it's only Curse I wonder if there is something I can do.

**Comment by jliddev** [comment]
Whoever's certificate is not properly signed should fix it ultimately. The only workarounds are to disable all ssl verification really which is not ideal.

**Comment by Dillonzer** [comment]
Ah okay thanks. I'll do some digging.
