### ISSUE TITLE
Issue around latest addon, rescan, and provider order

### ISSUE THREAD

**Issue by bmiles2001** [WowUp/WowUp#879]
This is for Classic Wow TBC during the prepatch. 

**Describe the bug**
The Addon Provider order does not always show the latest or correct Addon version for TBC.

**To Reproduce**
1. Click on Get Addons
2. In the filter/search box, type in classicaura (for ClassicAuraDurations). 
3. Observe author, provider, and version. Current version is 2.5.53-bcc from Provider: Curse
4. Install ClassicAuraDuration from Curse
5. Click Re-Scan Folders button
6. Observe that ClassicAuraDurations wants you to install 1.13.65 provided by WowInterface for the 1.13.7 Game Version.
7. Note: If you deselect WowInterface as a provider and do the same steps, it will not be able to find this same addon.

**Expected behavior**
Since I am running the Wow TBC Client, I should not be trying to install a 1.13.65 game version. It should be trying to install 2.5.x game version addons. 

**Screenshots**

**Desktop (please complete the following information):**
- Windows 10 Pro

**Additional context**
Since we installed ClassicAuraDurations from Curse, the rescan also forgets we got it from Curse (expected) but shouldn't it know at some level "this is available from WowInterface AND Curse" ?  Would it help to be able to reorder the providers under Options > Addons ? Also, you'll notice in the screenshot that my Threat Plates is a 10.2.0 version and it wants me to "Update" to 10.1.8 which is a lower version.

![image](https://user-images.githubusercontent.com/9649021/119024096-56dd1980-b968-11eb-9979-403ba61f9278.png)

![image](https://user-images.githubusercontent.com/9649021/119024058-4cbb1b00-b968-11eb-8cac-f929d431e716.png)

**Comment by jliddev** [comment]
We're currently tracking a bug with the CF api, they are returning incorrect fingerprints. So when you rescan we're unable to match your folder to anything in curse due to invalid fingerprints on their end.

**Comment by jliddev** [comment]
This issue should be largely gone on the latest version of WowUp
