### ISSUE TITLE
WowUp hangs after running for a while

### ISSUE THREAD

**Issue by b-morgan** [WowUp/WowUp#880]
**Describe the bug**
I leave WowUp running (icon in the system tray) but after some amount of time (currently unknown how long) the window will be frozen. 
**To Reproduce**
1. Leave WowUp running
2. After a while, Click on anything
3. Nothing happens

**Expected behavior**
I expect that it shouldn't matter how long WowUp has been running. When I return to its window, the controls should work.

**Desktop (please complete the following information):**
 - Windows 10 (1909)
 - Chrome Browser Version 90.0.4430.212 (Official Build) (64-bit)
 - WowUp 2.3.0

I suspect that this isn't enough information so please tell me what additional info is needed.

**Comment by jliddev** [comment]
Please provide logs from Options > Debug > Show Log Files

**Comment by b-morgan** [comment]
I started new logs just after I created this ticket. I'll provide the logs after it hangs up again.

**Comment by b-morgan** [comment]
(Still waiting for the hang to occur)
