### ISSUE TITLE
Running WowUp causes Battle.net to update all clients.

### ISSUE THREAD

**Issue by b-morgan** [WowUp/WowUp#882]
**Describe the bug**
After I have run WowUp, Battle.net thinks all the clients need to be updated (and does so). Nothing is actually changed.

I originally blamed this behavior on Battle.net and opened a thread in the WoW forums: [https://us.forums.blizzard.com/en/wow/t/battlenet-updating-all-versions-of-wow-over-and-over/941555/41](url)

After numerous clearing of folders and reinstalling Battle.net numerous times the suggestion was to open a ticket which I did: [https://us.battle.net/support/en/case/detail/79516490](url)

After 3+ hours on the phone with Blizzard support which included uninstalling and installing Battle.net, we discovered that Battle.net appears to be behaving as expected except when the WowUp application is run. It doesn't matter whether or not any addons are updated, just the fact that the application is run (and then closed completely, i.e. system tray quit).

**To Reproduce**
1. Open the Battle.net application and let it update all the clients.
2. Close the Battle.net application (configured as Exit Battle.net completely when the X is clicked).
3. Open the Battle.net application, no client updates needed.
4. Close the Battle.net application.
5. Repeat steps 3 and 4 including playing WoW (one or more of the three flavors). End with the Battle.net application closed.
6. Open WowUp application.
7. Close the WowUp application.
8. Use the system tray icon to quit WowUp completely.
9. Open the Battle.net application. It now thinks all clients need to be updated. Let the updates complete. Return to step 2.

**Expected behavior**
Running WowUp and/or leaving it running should have zero effect on Battle.net updates.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, 1909, 64-bit
 - Browser: Chrome Version 90.0.4430.212 (Official Build) (64-bit)
 - Version WowUp 2.3.0
 
**Additional context**
This started happening more than a month ago (it had been happening weeks before I entered the forum post on April 18, 2021). I only recently narrowed it down to this interaction with the WowUp application and Battle.net application. WowUp logs are attached along with MSInfo and DxDiag output (which Blizzard requested).

[logs.zip](https://github.com/WowUp/WowUp/files/6524847/logs.zip)
[main.log](https://github.com/WowUp/WowUp/files/6524848/main.log)
[renderer.log](https://github.com/WowUp/WowUp/files/6524849/renderer.log)

[MSInfo-DxDiag.zip](https://github.com/WowUp/WowUp/files/6524857/MSInfo-DxDiag.zip)

**Comment by linaori** [comment]
Yes, this is incredibly annoying and started for me way before that already. I suspect somewhere around the release of their latest launcher as I didn't notice this issue in the beta. 

There's nothing we can do about this though... I suspect the wow client sees a process with "wow*.\.exe" in the name and does a safety check to prevent cheats/mods/modified files from being present.

**Comment by b-morgan** [comment]
Nothing you can do is totally unacceptable. At the very least, you should create a dummy process named wow*.exe and prove that your theory is correct. I also believe that I was running WowUp for a while before this behavior started and since the name of your application hasn't changed, this already begins to poke holes in your theory.

This problem does not occur when the WeakAuras desktop application is running, the Zygor desktop application is running, and/or the TSM desktop application (or any combination of those three). Granted none of those applications are named wow*.exe but they all do exactly the same thing as WowUp (i.e. update addons) only on a limited basis (i.e. one specific application each).

**Comment by b-morgan** [comment]
On a brighter note... The Blizzard technician I spoke with said that they would be willing to "consult" with the WowUp developer(s) through their ticket process to help resolve this issue.

**Comment by linaori** [comment]
> Nothing you can do is totally unacceptable.
> you should create a dummy process named wow*.exe and prove that your theory is correct.

In case you forgot, this is an open-source project done by people in their spare time. Demanding us to fix this or calling it unacceptable is not okay. We have literally 0 control over the Blizzard Launcher and how it behaves.

You can test this yourself by running the app locally in dev build, and you'll see that the launcher works just fine. Whatever it is, the Blizzard launcher reacts to the executable.

>  I also believe that I was running WowUp for a while before this behavior started and since the name of your application hasn't changed, this already begins to poke holes in your theory.

Which can mean 1000 different things, including a change in the blizzard launcher. Blaming the behavior of the Blizzard launcher on WowUp makes no sense unless you have actual proof that WowUp is actively causing this.

> This problem does not occur when the WeakAuras desktop application is running, the Zygor desktop application is running, and/or the TSM desktop application (or any combination of those three). Granted none of those applications are named wow*.exe but they all do exactly the same thing as WowUp (i.e. update addons) only on a limited basis (i.e. one specific application each).

I have not seen such reports from Ajour, Cursebreaker, nor Overwolf either. WowUp only touches the Interface/AddOns directory for writing, and reads from some other directories (which shouldn't even be close to causing issues). In fact I've had issues with the rio app **locking** wow game files, making it impossible for me to copy my profile data, and that caused 0 issues.

In fact, the only thing that's required in the current setup, is that WowUp.exe is running. I don't think there's anything actively doing stuff in the WoW directory at all, but @jliddev knows more about that.

**Comment by b-morgan** [comment]
I apologize for my outburst. After spending 3 hours on the phone with a Blizzard technician who was very thorough with his troubleshooting steps I guess I wasn't expecting you to blame them for causing the problem less than 5 minutes after opening the issue.

I have added a link to this issue to my Blizzard support ticket and we will see what their response is to your analysis.

**Comment by linaori** [comment]
As you can see, we are aware of this issue and have tried to contact Blizzard on several occasions (other than this tweet), with no success: https://twitter.com/WowUpAddons/status/1379436136917950474

@jliddev mentioned last night that he might have found the issue. For now I have been able to avoid the updates by uninstalling the addon manager addon.

Long story short of what @jliddev has discovered, it seems that the blizzard launcher doesn't like read-only files, and will try to make all files read+write when you start the launcher. Somehow some addon files for the data addon are copied as read only from what I read, causing the launcher to "correct" this behavior. This seems to be an issue with every read only file in the addon directory:

Not sure why the Blizzard launcher aggressively messes with permissions in this particular directory. 

Before:
![image](https://user-images.githubusercontent.com/1754678/119224490-f46a5180-bafe-11eb-9ab0-e758f1368383.png)

During:
![image](https://user-images.githubusercontent.com/1754678/119224513-0c41d580-baff-11eb-8b27-5b675f073d5a.png)

After:
![image](https://user-images.githubusercontent.com/1754678/119224529-1b288800-baff-11eb-9da6-d582b488e70e.png)

**Comment by b-morgan** [comment]
Excellent news! 

I'm sorry to hear that you are having problems communicating with Blizzard. While it took a couple of iterations, I finally got to talk directly with their support staff and it was, IMO, a very productive conversation. I suggest opening a support ticket and persevering until you get non-boiler plate responses.

**Comment by b-morgan** [comment]
Anything I can do to help test?

**Comment by linaori** [comment]
If you know how to build an executable locally that can reproduce this behavior, then you can. I sadly don't so we might have to wait until @jliddev has time to review and test this

**Comment by linaori** [comment]
@b-morgan please try the latest beta and see if that fixes it for you. So far I have not been able to reproduce the read-only state on the tga file and the Blizzard launcher is behaving: https://github.com/WowUp/WowUp/releases/tag/v2.3.1-beta.2

**Comment by b-morgan** [comment]
Looks like we have a winner!
