### ISSUE TITLE
Addon gets flagged as ignored after re-scan (expected/Curseforge API problem?)

### ISSUE THREAD

**Issue by maduk6** [WowUp/WowUp#894]
**Describe the bug**
Freshly installed addon per Wowup gets into "ignored" (did not match with any provider) status after re-scan.

**To Reproduce**

Addon used: Attune
https://www.curseforge.com/wow/addons/attune

Client: TBC Classic

1. install Attune per "Get Addons"
2. do a rescan

**Expected behavior**
Addon is not getting put into a ignored state.

**Screenshots**
![image](https://user-images.githubusercontent.com/45685391/119996187-b83b6300-bfce-11eb-9eb0-c6ae342f3bed.png)

**Desktop:**
 - OS: Win10
 - Wowup v2.3.0

**Additional context**
API Output from Attune:
https://addons-ecs.forgesvc.net/api/v2/addon/414434
`{
	"id": 414434,
	"name": "Attune",
	"authors": [
		{
			"name": "CixiDelmont",
			"url": "https://www.curseforge.com/members/100434007-cixidelmont?username=cixidelmont",
			"projectId": 414434,
			"id": 324278,
			"projectTitleId": null,
			"projectTitleTitle": null,
			"userId": 100434007,
			"twitchId": 461926810
		}
	],
	"attachments": [
		{
			"id": 307485,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/avatars/thumbnails/307/485/256/256/637388448071552291.png",
			"title": "637388448071552291.png",
			"url": "https://media.forgecdn.net/avatars/307/485/637388448071552291.png",
			"status": 1
		},
		{
			"id": 379727,
			"projectId": 414434,
			"description": "",
			"isDefault": true,
			"thumbnailUrl": "https://media.forgecdn.net/avatars/thumbnails/379/727/256/256/637560544303936201.png",
			"title": "637560544303936201.png",
			"url": "https://media.forgecdn.net/avatars/379/727/637560544303936201.png",
			"status": 1
		},
		{
			"id": 331942,
			"projectId": 414434,
			"description": "Summary of the latest updates",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/331/942/310/172/attune-updated.jpg",
			"title": "Updated Interface",
			"url": "https://media.forgecdn.net/attachments/331/942/attune-updated.jpg",
			"status": 1
		},
		{
			"id": 329895,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/329/895/310/172/attune_questtooltip.PNG",
			"title": "Quest Tooltip",
			"url": "https://media.forgecdn.net/attachments/329/895/attune_questtooltip.PNG",
			"status": 1
		},
		{
			"id": 343216,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/343/216/310/172/attune-listsamestep.PNG",
			"title": "List of guildies on the same step",
			"url": "https://media.forgecdn.net/attachments/343/216/attune-listsamestep.PNG",
			"status": 1
		},
		{
			"id": 343217,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/343/217/310/172/attune-showcompleted.PNG",
			"title": "Show list completed",
			"url": "https://media.forgecdn.net/attachments/343/217/attune-showcompleted.PNG",
			"status": 1
		},
		{
			"id": 359842,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/359/842/310/172/attune-toonprofiles.PNG",
			"title": "Toon Profiles",
			"url": "https://media.forgecdn.net/attachments/359/842/attune-toonprofiles.PNG",
			"status": 1
		},
		{
			"id": 364062,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/364/62/310/172/attune-raidplanner.png",
			"title": "Raid Planner",
			"url": "https://media.forgecdn.net/attachments/364/62/attune-raidplanner.png",
			"status": 1
		},
		{
			"id": 348628,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/348/628/310/172/attune-interfaceoptions2.PNG",
			"title": "Interface Options",
			"url": "https://media.forgecdn.net/attachments/348/628/attune-interfaceoptions2.PNG",
			"status": 1
		},
		{
			"id": 330273,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/330/273/310/172/attune-partyraid.png",
			"title": "Survey/Export party/raid",
			"url": "https://media.forgecdn.net/attachments/330/273/attune-partyraid.png",
			"status": 1
		},
		{
			"id": 323571,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/323/571/310/172/attune-export.PNG",
			"title": "Export window (in game)",
			"url": "https://media.forgecdn.net/attachments/323/571/attune-export.PNG",
			"status": 1
		},
		{
			"id": 351447,
			"projectId": 414434,
			"description": "Display your guild progress in Discord",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/351/447/310/172/attunebot2.PNG",
			"title": "Discord AttuneBot - In Progress",
			"url": "https://media.forgecdn.net/attachments/351/447/attunebot2.PNG",
			"status": 1
		},
		{
			"id": 351446,
			"projectId": 414434,
			"description": "Display your guild progress in Discord",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/351/446/310/172/attunebot1.PNG",
			"title": "Discord AttuneBot - attuned",
			"url": "https://media.forgecdn.net/attachments/351/446/attunebot1.PNG",
			"status": 1
		},
		{
			"id": 329390,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/329/390/310/172/attune.PNG",
			"title": "The new Attune interface",
			"url": "https://media.forgecdn.net/attachments/329/390/attune.PNG",
			"status": 1
		},
		{
			"id": 317687,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/317/687/310/172/attune-demo.png",
			"title": "Website Progress",
			"url": "https://media.forgecdn.net/attachments/317/687/attune-demo.png",
			"status": 1
		},
		{
			"id": 329813,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/329/813/310/172/guild-tab.PNG",
			"title": "Guild SummaryTab",
			"url": "https://media.forgecdn.net/attachments/329/813/guild-tab.PNG",
			"status": 1
		},
		{
			"id": 323572,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/323/572/310/172/attune-upload.png",
			"title": "Upload form - Website",
			"url": "https://media.forgecdn.net/attachments/323/572/attune-upload.png",
			"status": 1
		},
		{
			"id": 330274,
			"projectId": 414434,
			"description": "",
			"isDefault": false,
			"thumbnailUrl": "https://media.forgecdn.net/attachments/thumbnails/330/274/310/172/attune-resultoptions.PNG",
			"title": "New filter options for results",
			"url": "https://media.forgecdn.net/attachments/330/274/attune-resultoptions.PNG",
			"status": 1
		}
	],
	"websiteUrl": "https://www.curseforge.com/wow/addons/attune",
	"gameId": 1,
	"summary": "Attunement progress",
	"defaultFileId": 3314495,
	"downloadCount": 343280.0,
	"latestFiles": [
		{
			"id": 3314495,
			"displayName": "Attune-1.13.7.224.zip",
			"fileName": "Attune-1.13.7.224.zip",
			"fileDate": "2021-05-18T23:57:52.68Z",
			"fileLength": 482791,
			"releaseType": 1,
			"fileStatus": 4,
			"downloadUrl": "https://edge.forgecdn.net/files/3314/495/Attune-1.13.7.224.zip",
			"isAlternate": false,
			"alternateFileId": 0,
			"dependencies": [],
			"isAvailable": true,
			"modules": [
				{
					"foldername": "Attune",
					"fingerprint": 795145938,
					"type": 3
				}
			],
			"packageFingerprint": 2236481311,
			"gameVersion": [
				"1.13.7"
			],
			"sortableGameVersion": [
				{
					"gameVersionPadded": "0000000001.0000000013.0000000007",
					"gameVersion": "1.13.7",
					"gameVersionReleaseDate": "2021-04-20T00:00:00Z",
					"gameVersionName": "1.13.7"
				}
			],
			"installMetadata": null,
			"changelog": null,
			"hasInstallScript": false,
			"isCompatibleWithClient": true,
			"categorySectionPackageType": 1,
			"restrictProjectFileAccess": 1,
			"projectStatus": 4,
			"renderCacheId": 2315768,
			"fileLegacyMappingId": null,
			"projectId": 414434,
			"parentProjectFileId": null,
			"parentFileLegacyMappingId": null,
			"fileTypeId": null,
			"exposeAsAlternative": null,
			"packageFingerprintId": 665243611,
			"gameVersionDateReleased": "2021-04-20T00:00:00Z",
			"gameVersionMappingId": 2952091,
			"gameVersionId": 8292,
			"gameId": 1,
			"isServerPack": false,
			"serverPackFileId": null,
			"gameVersionFlavor": "wow_classic"
		},
		{
			"id": 3324236,
			"displayName": "Attune-227.zip",
			"fileName": "Attune-227.zip",
			"fileDate": "2021-05-25T12:15:17.393Z",
			"fileLength": 483632,
			"releaseType": 1,
			"fileStatus": 4,
			"downloadUrl": "https://edge.forgecdn.net/files/3324/236/Attune-227.zip",
			"isAlternate": false,
			"alternateFileId": 0,
			"dependencies": [],
			"isAvailable": true,
			"modules": [
				{
					"foldername": "Attune",
					"fingerprint": 3699429068,
					"type": 3
				}
			],
			"packageFingerprint": 2365112344,
			"gameVersion": [
				"2.5.1",
				"1.13.7"
			],
			"sortableGameVersion": [
				{
					"gameVersionPadded": "0000000002.0000000005.0000000001",
					"gameVersion": "2.5.1",
					"gameVersionReleaseDate": "2021-03-31T00:00:00Z",
					"gameVersionName": "2.5.1"
				},
				{
					"gameVersionPadded": "0000000001.0000000013.0000000007",
					"gameVersion": "1.13.7",
					"gameVersionReleaseDate": "2021-04-20T00:00:00Z",
					"gameVersionName": "1.13.7"
				}
			],
			"installMetadata": null,
			"changelog": null,
			"hasInstallScript": false,
			"isCompatibleWithClient": true,
			"categorySectionPackageType": 1,
			"restrictProjectFileAccess": 1,
			"projectStatus": 4,
			"renderCacheId": 2327803,
			"fileLegacyMappingId": null,
			"projectId": 414434,
			"parentProjectFileId": null,
			"parentFileLegacyMappingId": null,
			"fileTypeId": null,
			"exposeAsAlternative": null,
			"packageFingerprintId": 669389631,
			"gameVersionDateReleased": "2021-03-31T00:00:00Z",
			"gameVersionMappingId": 2973680,
			"gameVersionId": 8287,
			"gameId": 1,
			"isServerPack": false,
			"serverPackFileId": null,
			"gameVersionFlavor": "wow_burning_crusade"
		}
	],
	"categories": [
		{
			"categoryId": 1007,
			"name": "Data Export",
			"url": "https://www.curseforge.com/wow/addons/data-export",
			"avatarUrl": "https://media.forgecdn.net/avatars/54/443/636135209651648632.png",
			"parentId": 1,
			"rootId": 1,
			"projectId": 414434,
			"avatarId": 54443,
			"gameId": 1
		},
		{
			"categoryId": 1013,
			"name": "Quests & Leveling",
			"url": "https://www.curseforge.com/wow/addons/quests-leveling",
			"avatarUrl": "https://media.forgecdn.net/avatars/54/449/636135209685443713.png",
			"parentId": 1,
			"rootId": 1,
			"projectId": 414434,
			"avatarId": 54449,
			"gameId": 1
		}
	],
	"status": 4,
	"primaryCategoryId": 1007,
	"categorySection": {
		"id": 1,
		"gameId": 1,
		"name": "Addons",
		"packageType": 1,
		"path": "Interface\\Addons",
		"initialInclusionPattern": "(?i)^([^/]+)[\\\\/]\\1\\.toc$",
		"extraIncludePattern": "(?i)^[^/\\\\]+[/\\\\]Bindings\\.xml$",
		"gameCategoryId": 1
	},
	"slug": "attune",
	"gameVersionLatestFiles": [
		{
			"gameVersion": "1.13.7",
			"projectFileId": 3324236,
			"projectFileName": "Attune-227.zip",
			"fileType": 1,
			"gameVersionFlavor": "wow_burning_crusade"
		},
		{
			"gameVersion": "2.5.1",
			"projectFileId": 3324236,
			"projectFileName": "Attune-227.zip",
			"fileType": 1,
			"gameVersionFlavor": "wow_burning_crusade"
		}
	],
	"isFeatured": false,
	"popularityScore": 12070.029296875,
	"gamePopularityRank": 127,
	"primaryLanguage": "enUS",
	"gameSlug": "wow",
	"gameName": "World of Warcraft",
	"portalName": "www.curseforge.com",
	"dateModified": "2021-05-25T12:23:51.883Z",
	"dateCreated": "2020-10-21T02:40:07.117Z",
	"dateReleased": "2021-05-25T12:15:17.393Z",
	"isAvailable": true,
	"isExperiemental": false
}`

**Comment by jliddev** [comment]
This is correct, since prepatch went live curse has been sending down the incorrect fingerprints for addons with multiple tocs.
 In the above JSON you'll see 3699429068 is the fingerprint of the latest 227 version. That's incorrect. The value should be 538160949 which is what we and their own client calculate on our side. So when it comes time to match, we cant because their server is broken.

This can be cross checked by installing the addon in their own client and hitting refresh where it will now be marked as "Modified" similar to our "Unknown" provider

**Comment by maduk6** [comment]
Alright, thanks for the fast respone and great work on wowup.

**Comment by jliddev** [comment]
Going to reopen since this question appears several times a day.

**Comment by Morgulec** [comment]
Additional question regarding ignored state. Will there be option to select ignored addon and check for new/proper version by right-click instead of doing re-scan now and then?

**Comment by jliddev** [comment]
There are issues with something like that, many addons have multiple folders that are required to perform a proper scan. so trying to scan just one wont work often.

**Comment by jliddev** [comment]
Someone want to check if this is working as expected now in 2.3.2? https://github.com/WowUp/WowUp/releases/tag/v2.3.2-beta.2
