### ISSUE TITLE
Re-scan cause some addons to be ignored

### ISSUE THREAD

**Issue by Morgulec** [WowUp/WowUp#895]
Hello, i've noticed that doing re-scan may cause some addons to become marked as ignored. Those addons were previously been properly downloaded and/or updated through WoWUp app.

**To Reproduce**
1. Install Attune
2. Click re-scan folders
3. Attune now is marked as ignored

**Expected behavior**
Installed addon should remain in proper active state.

**Screenshots**
![addons](https://user-images.githubusercontent.com/4264939/119997754-5aa81600-bfd0-11eb-8159-a9d7fcffd990.JPG)

**Desktop (please complete the following information):**
 - Win8
 - Browser Firefox
 - WoWUp ver 2.3.0

Additional question regarding ignored state. Will there be option to select ignored addon and check for new/proper version by right-click instead of doing re-scan now and then?

**Comment by jliddev** [comment]
See #894
