### ISSUE TITLE
Neat Minimap is incorrectly recognized as MerathilisUI-TBC

### ISSUE THREAD

**Issue by timss** [WowUp/WowUp#897]
**Describe the bug**
For some reason WowUp was showing me that there's was an update avilable for "MerathilisUI-TBC" from the TukUI provider, however I didn't have this addon installed. When choosing "show folder" it gave me the directory of another addon "Neat Minimap", which I did have installed (classic 1.13.6).

Using the "Re-Scan Folders" functionality did however fix the problem for me, but just thought it was a curious bug that might be worth reporting. If it's not considered a problem, please go ahead and close the issue :)

**To Reproduce**
1. Install Neat Minimap version "v1.07.03"
2. Choose "Classic" version of World of Warcraft in WowUp (i.e. TBC)
3. Press "Check Updates"

**Expected behavior**
WowUp to suggest updating Neat Minimap from version "v1.07.03" to "v1.08.00".

**Screenshots**
![image](https://user-images.githubusercontent.com/1747578/120022236-6f92a280-bfec-11eb-951a-f0dfda8ae63c.png)
<img src="https://user-images.githubusercontent.com/1747578/120022246-715c6600-bfec-11eb-870d-6eeb04ddfc37.png " width="100">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: n/a
 - Version: Wowup v2.3.0

**Comment by jliddev** [comment]
Can you provide the toc file from the folder in question.

**Comment by timss** [comment]
```## Interface: 11306
## Title: Neat Minimap
## Notes: Neat Minimap auto hides/shows buttons and clutter as needed (|cFF99E5FF/nmm|r)
## Author: MooreaTV moorea@ymail.com
## Version: v1.07.03
## DefaultState: Enabled
## LoadOnDemand: 0
## SavedVariables: NeatMinimapSaved
## OptionalDeps: SexyMap, ElvUI
## Globe: check-classic
## X-OpenSource-License: LPGLv3
## X-OpenSource-Releases: https://github.com/mooreatv/NeatMinimap/releases
## X-Curse-Project-ID: 341067
## X-WoWI-ID: 25284
MoLib/MoLib.lua
MoLib/MoLibUI.lua
NeatMinimap.lua```

**Comment by jliddev** [comment]
I am unable to replicate this issue by installing that version in any client

**Comment by timss** [comment]
Figures since it got fixed after the re-scan, but worth a shot :)
