### ISSUE TITLE
Addon not detected MikScrollingBattleText

### ISSUE THREAD

**Issue by DavidBabel** [WowUp/WowUp#898]
**Describe the bug**
An installed working addon is not detected.

**To Reproduce**
1. Install this addon : https://www.wowinterface.com/downloads/info18809-Release0.6.html
2. Open WoWUp
3. Search for "Mik"
4. See nothing

**Expected behavior**
The addon is visible and updatable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
The BC client should handle WoW Retails addons if wanted, most of them works well. (EavesDrop, TSM, Ark)

**Comment by jliddev** [comment]
You installed the addon manually?

**Comment by DavidBabel** [comment]
Finally yes

**Comment by DavidBabel** [comment]
Yes it is not searchable from WoWup

**Comment by jliddev** [comment]
If you install something manually wowup wont know until you do a re-scan

**Comment by DavidBabel** [comment]
My bad, smart. 

It works though. But the patched version is not yet on curse.

![image](https://user-images.githubusercontent.com/5599375/120209221-b7a10780-c22e-11eb-8b4d-56c8cb5e480c.png)

Thanks !

**Comment by jliddev** [comment]
You might check the game version on that one, wow interface served out the TBC version i think. WowI does not have a concept of classic/retail on their api.
