### ISSUE TITLE
Addon "Tukui Nameplate Features" incorrectly detected

### ISSUE THREAD

**Issue by leobolin** [WowUp/WowUp#905]
**Describe the bug**
Whenever I Re-Scan Folders, WowUp somehow finds and adds the addon "Tukui Nameplate Features" to my list of installed addons. I have never ever used TukUI, and I do not have the addon anywhere on my computer. If right-click it in the list and choose "Show Folder" I get an error message saying that the folder does not exist.

**To Reproduce**
1. Click the Re-Scan Folders button
2. Wait for the scan to complete

**Expected behavior**
The addon should not be detected since I do not have it.

**Screenshots**
[https://i.imgur.com/e4CdlRw.png](https://i.imgur.com/e4CdlRw.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.3.4 (has also been happening in previous versions for at least a few months)

**Comment by jliddev** [comment]
You will need to go to debug > dump debug data. Then supply us with the logs then we can take a look at what this might be.

**Comment by leobolin** [comment]
Well, now I'm unable to reproduce the bug.
