### ISSUE TITLE
UI Refresh stops when the application is minimized to tray with pressing the close button

### ISSUE THREAD

**Issue by fkrisi11** [WowUp/WowUp#910]
**Describe the bug**
UI Refresh stops when the application is minimized to tray with pressing the close button.
You can see this from not being able to switch tabs visually, once you opened the application back up by double clicking the tray icon.
As soon as you move the window, the ui starts refreshing properly and it works, until it is closed again with the Close (X) button.

Might be related to #880 ?

**To Reproduce**
1. Open program
2. Close program with the Close button (X) in the top right
3. Double click tray icon to show the app again
4. UI doesn't refresh anymore
5. Move application window, and it start to refresh again, until it is closed again.

**Expected behavior**
UI refreshes right away, after it is shown

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by jliddev** [comment]
Unable to replicate this with given steps, could be related to #880
