### ISSUE TITLE
Mac M1 Support

### ISSUE THREAD

**Issue by jliddev** [WowUp/WowUp#918]
Have the builder create an arm64 build for Mac

This is blocked until GitHub updates the build agent to Mac 11+

**Comment by Nils89** [comment]
You can get access to the Mac 11 pool:
https://github.com/actions/virtual-environments/blob/main/docs/macos-11-onboarding.md

**Comment by jliddev** [comment]
I filled out the form, but the docs say they aren't accepting new people. So we'll see. Looks like they are updating the xcode version on the existing Mac 10.x pool in a couple weeks, might try that.

![image](https://user-images.githubusercontent.com/20467484/121777286-e3898a80-cb56-11eb-8cf1-c4d14e439c11.png)

**Comment by Nils89** [comment]
Can be closed
