### ISSUE TITLE
Game Version is incorrect for addons that have .toc files for multiple clients

### ISSUE THREAD

**Issue by nzall** [WowUp/WowUp#922]
**Describe the bug**
Some addons use the same source code for multiple clients of the version, with a .toc file being used to indicate the compatible version. For example, TomTom has a TomTom.toc, a TomTom-Classic.toc and a TomTom-BCC.toc file. For TomTom, even though I'm in my retail addon list, WowUp uses the BCC.toc file to determine the game version to show in the client.

**To Reproduce**
1. Install TomTom addon from the Curse provider
2. See that WowUp lists game version 2.5.1 instead of the expected 9.0.5

**Expected behavior**
WowUp should list Game Version 9.0.5.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.3.4

**Comment by linaori** [comment]
Hmm I don't think anything in this code has changed in the latest beta in regards of this code, it seems to work for me? 
![image](https://user-images.githubusercontent.com/1754678/121809260-752ef000-cc5c-11eb-98e3-3a80bf6a0ee0.png)

**Comment by linaori** [comment]
Okay I can confirm this behavior for a re-scan, something is not going right there. I have the same issue with "grounded" as well.
![image](https://user-images.githubusercontent.com/1754678/121809373-d35bd300-cc5c-11eb-9ca1-78674a5d7707.png)

**Comment by jliddev** [comment]
Give this a shot in the 2.4 beta, hopefully multi toc works better
