### ISSUE TITLE
Incorrect "Curse did not have any matching game version files" for Baud Mark (BCC)

### ISSUE THREAD

**Issue by matthewhively** [WowUp/WowUp#949]
Description:
For the addon "Baud Mark", the wowup client incorrectly states "Curse did not have any matching game version files"
This probably affects other addons, but I don't see any other examples in my personal list.
This might be related to #922 ?

Reproduction:
- Manually Install baud mark BCC
- rescan
- Observe wowup indicates no matching version could be found.
- use "view on curse" link
- Observe a matching version is in fact listed on the mod page.

Expected behavior:
wowup should identify the matching version correctly.

Version Info:
 - OS: Windows 10
- wowup client version 2.3.4

Additional Notes:
I tried to dump debug information but I was not able to find the dump log file.
Maybe its related to to how curse is displaying the version numbers? In the files tab the version column shows "2.5.1 +1"
_However the retail version appears to work correctly, so it probably isn't the case since it shows its version as "9.1.0 +2"_

**Comment by linaori** [comment]
I suspect it doesn't work because the files returned for those addons are not marked with `wow_burning_crusade` but with `wow_classic`. Doesn't look like a WowUp issue to me, though I can't tell if it's the author that tagged something wrong, or CurseForge being CurseForge.
https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=1&searchFilter=Baud+Mark

**Comment by Nils89** [comment]
The author supports with that version classic and tbc:
```
"gameVersion":[
   "1.13.6",
   "2.5.1"
],
```
so the `gameVersionFlavor":"wow_classic"` become the first gameVersion, think that is the issue

**Comment by linaori** [comment]
I don't know if `gameVersion` is used atm, I haven't kept track of those changes.

**Comment by jliddev** [comment]
@Nils89 that array is not super useful due to the fact that CF wills till serve addons for 2.5.1 that were current in like 2010. CurseForge has yet to add proper multi toc support.

**Comment by Nils89** [comment]
Yes that is what I mean:
CF Medions only the first version of supported game versions and leave the rest out
