### ISSUE TITLE
VenturePlan update not detected

### ISSUE THREAD

**Issue by tomrus88** [WowUp/WowUp#950]
I have VenturePlan 4.15a installed, new version 4.16 was released already

**Describe the bug**
WowUp not detecting updates for VenturePlan from https://www.townlong-yak.com/addons/venture-plan

**To Reproduce**
Click "Check Updates"

**Expected behavior**
Addon update should be detected

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by linaori** [comment]
The author of Venture plan hasn't updated their API, and it's officially not maintained anymore. We're investigating alternative solutions to see what we can do.

**Comment by jliddev** [comment]
The Townlong Yak API has been discontinued. We have reached out to the author so the ball is in his court. As of right now there is no way to get the data properly.

https://www.townlong-yak.com/addons/about/update-api

**Comment by MrUzagi** [comment]
Oh wow. Townlong Yak is working hard at becoming completely useless. It's nearly impossible to find anything there unless you know the exact url as it is.

**Comment by cremor** [comment]
I just updated VenturePlan to 4.16a via WowUp. Did they fix their API?

**Comment by linaori** [comment]
There have been made some agreements with TLY and we're currently hosting a mirror of sorts for the latest available version

**Comment by cremor** [comment]
Oh, ok. Can we expect this mirror to be updated reasonably quickly after new versions are published?

And what would happen if this mirror one day doesn't exist any more? Would WowUp notify about that (e.g. like when an addon is deleted on Curse)?

**Comment by linaori** [comment]
> Oh, ok. Can we expect this mirror to be updated reasonably quickly after new versions are published?

That's what we aim for. I don't know how fast, but it shouldn't be (much) slower than before.

> And what would happen if this mirror one day doesn't exist any more? Would WowUp notify about that (e.g. like when an addon is deleted on Curse)?

No idea, we'll see what we can do about that then. Currently WowUp doesn't have support for "this addon is now abandoned" at all.

**Comment by jliddev** [comment]
This specific issue is currently resolved.
