### ISSUE TITLE
My addons filter is ignored after reinstalling addon

### ISSUE THREAD

**Issue by liamcooper** [WowUp/WowUp#955]
**Describe the bug**
When you are looking at the my addons tab and type in the filter to filter the addons, then right click an addon and click re-install addon, after the addon is installed the list reloads and the filter is ignored.

**To Reproduce**
1. Go to my addons tab
2. Type something in the filter that will result in an addon showing in the list
3. Right click the addon and choose re-install

**Expected behavior**
I expect the list to not ignore the filter that has been entered.

**Screenshots**
My addons tab with a filter applied
![image](https://user-images.githubusercontent.com/7249112/123305317-e05baa80-d517-11eb-999b-1c189a8fda68.png)

Clicked to re-install atlas addon
![image](https://user-images.githubusercontent.com/7249112/123305361-ee113000-d517-11eb-8c8c-ef59191bb62d.png)

Filter is being ignored
![image](https://user-images.githubusercontent.com/7249112/123305388-f49fa780-d517-11eb-8ad3-e6499318376f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 2.3.4

**Comment by linaori** [comment]
This happens in other scenarios as well

**Comment by jliddev** [comment]
use #977
