### ISSUE TITLE
App Badge Notification - Specific Client Selection

### ISSUE THREAD

**Issue by Merxxz** [WowUp/WowUp#976]
**Is your feature request related to a problem? Please describe.**
I would like to only show the App Badge Notification number for retail client. My current solution is to delete ptr/classic/beta locations from WoWUp for now.

**Describe the solution you'd like**
Some more options to select what clients you'd like the App Badge Notification to apply for (i.e. checkboxes for all clients you care to show).

**Describe alternatives you've considered**
To keep it simple, maybe an optional dropdown to select the one client you care to show. Not as customizable as above solution.

**Comment by linaori** [comment]
> My current solution is to delete ptr/classic/beta locations from WoWUp for now.

You can solve this by ignoring all addons for a specific client, saves you from having to delete the client locations.

![image](https://user-images.githubusercontent.com/1754678/124004197-139aaf80-d9d8-11eb-91aa-3f011c2fc282.png)
