### ISSUE TITLE
Issue while searching and removing addons.

### ISSUE THREAD

**Issue by NobodyNParticular** [WowUp/WowUp#977]
**Describe the bug**
After filtering for a set of addons (filter used: tomcat, Retail version selected above list) and removing a discontinued one in the list; the filter does not clear but the list reverts back to unfiltered. Selecting the filter and pressing enter does not reperform the filter. I had to clear the Filter field with the X and retype the filter in. A few times I had to move from My Addons page to any other tab and then back in order to get the Filter to recognize any entry. In a few more tests deleting a character and replacing it in the Filter field seemed to work but as it was behaving inconsistently I felt it was worthy of bringing it to your attention. I also just noticed entering a character in the Filter changes the width of the Addon in my demonstration. I will add images. Probably have to be at just the right window size to occur but there you go.

**To Reproduce**
1. Filter on an addon
2. Remove one filtered addon
3. Return to Filter field. Press enter.
4. Filter not accepted.

**Expected behavior**
I did not expect the filter to be cleared. When the page reverted to either a different filter or the normal list I expected to be able to press enter for the filter to be accepted. 

**Screenshots**
Filtered on "tomcat" and selected Remove
![Step 1 2 Filter and remove](https://user-images.githubusercontent.com/42982380/124322645-d0624d00-db4d-11eb-8e09-57204f85cc39.PNG)
Result of Removal
![Step 2 Result of Removal](https://user-images.githubusercontent.com/42982380/124322675-df48ff80-db4d-11eb-88f5-67f6f4225c6e.PNG)
Cursor is at end of tomcat in Filter field and enter/return pressed several times.
![Step 3 Cusor is at end of tomcat and enter  slash  return pressed several times](https://user-images.githubusercontent.com/42982380/124323356-2f749180-db4f-11eb-8a9c-fe1d40eb3491.PNG)
Filter cleared. Notice Ackis Recipe List: Blacksmithing is on one line
![No filter entered has different addon width compare with The Other](https://user-images.githubusercontent.com/42982380/124323773-d9541e00-db4f-11eb-9068-e925bb91ef75.PNG)
Filtered on "a" and now Ackis Recipe List: Blacksmithing is now on two lines. This behavior made me think I was seeing a different list after the Filter removal when "tomcat" was entered. I would clear the Filter and the addon list would change visually. I now realize I was seeing was the same list but with behavior of text in the filter field being cleared.
![The Other](https://user-images.githubusercontent.com/42982380/124322755-04d60900-db4e-11eb-9df5-5ed629e8b58a.PNG)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows Version 20H2 (OS Build 19042.1052) 
 - Browser: MS Edge Version 91.0.864.59 (Official build) (64-bit)
 - Version: WowUp v2.4.2

**Additional context**
The last two images demonstrate the change in width of the Addon column or the change in font size when a filter is applied. It is subtle but demonstrable under the right conditions but probably not worth fixing.

**Comment by jliddev** [comment]
This should actually be resolved in the latest beta
