### ISSUE TITLE
Drop Down List on "myaddons" not working

### ISSUE THREAD

**Issue by Skyview0** [WowUp/WowUp#978]
When looking at different versions of WoW, the drop down list on "My Addons" is a dashed line, shows the drop down arrow, but does NOT allow selection to change to a different version.  I have to go to "get addons" to change which version of wow from the drop down list

**To Reproduce**
1. Go to "My Addons"
2. Click on dropdown arrow in box
3. Does not allow selection
4. Go to "get addons"
5. click on dropdown arrow for version (notice it is a line and not a dash line)
6. Change versions 
7. go back to "My Addons", and see that still cannot change versions of wow

**Expected behavior**
When on "My Addons" can change to a different versions and NOT have to "Get Addons", switch to another version, click on "My Addons" just to see what needs to update.

**Screenshots**
Screenshots of both My Addons and Get Addons screen

**Desktop (please complete the following information):**
 - Windows 10
 - Brave Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (64-bit)
 - WoWUP v
![wowup screen 1](https://user-images.githubusercontent.com/86888157/124361685-e9bed400-dbf5-11eb-87ac-d7465c9b1816.jpg)
![wowup screen 2](https://user-images.githubusercontent.com/86888157/124361687-ef1c1e80-dbf5-11eb-9b08-7636adb3f345.jpg)
2.4.2
 
**Additional context**

**Comment by Skyview0** [comment]
Well, since it was acting oddly. I rebooted and it is now working correctly. All I can say is, my apologies for not waiting until after rebooting my machine to report an issue.

**Comment by linaori** [comment]
Out of curiosity, did you happen to update an addon and then switch to get-addons before the addon was intalled? The screenshot of the GUI shows that everything in the bar is disabled, which happens when it's updating addons. One possibility I could think of is that when you switch to the get-addons page while this happens (or possibly news, about, or options), it fails to unlock that bar.

**Comment by Skyview0** [comment]
Lynn,

Thank you.  Here is what I recall doing. I started the update for the new version of WoWup, however, when i thought it was done, I went to the Classic era version and started adding addons. I think this happened before the client updated.  Everything was HOKEY for a while. I finished and opened up the error, then I just rebooted.

I thought I might have to uninstall and reinstall WoWup, but I'm grateful I did not. I put this up to user error.  I think I thought it was done, because nothing was disabled, or no pop-up saying.. wait while we finish the update.

Thank you so much for this quick reply,

Barb

________________________________

**Comment by linaori** [comment]
Do you know if you were updating from 2.3 or lower to 2.4? We have made some changes in the update process in 2.4, so it would be good to know if there's still something to fix. You say it's a user error, I say we should try to make it so that users can't get this to happen by accident 😄

**Comment by Skyview0** [comment]
I was updating from 2.3 or whatever was the release before this one. I try to update whenever I see the update notice.

Thank you for investigating this. I am an applications developer & enjoy hearing your take on this "I say we should try to make it so that users can't get this to happen by accident 😄". It fills me with joy! I feel like my user issue matters!

Thank you so much,
Barbara Doyle


Sent via the Samsung Galaxy S20+ 5G, an AT&T 5G smartphone


-------- Original message --------
From: Lynn ***@***.***>
Date: 7/5/21 2:44 AM (GMT-06:00)
To: WowUp/WowUp ***@***.***>
Cc: Skyview0 ***@***.***>, State change ***@***.***>
Subject: Re: [WowUp/WowUp] Drop Down List on "myaddons" not working (#978)


Do you know if you were updating from 2.3 or lower to 2.4? We have made some changes in the update process in 2.4, so it would be good to know if there's still something to fix. You say it's a user error, I say we should try to make it so that users can't get this to happen by accident 😄

**Comment by linaori** [comment]
Alright, I'll leave this issue closed for now and we can start digging if this happens again. Hopefully the 2.4 update flow fixed this issue

**Comment by Skyview0** [comment]
Thank you so much for looking into this.

Sincerely,
Barb

________________________________
