### ISSUE TITLE
 The keyboard navigation doesn't resize the lightbox causing images to stretch

### ISSUE THREAD

**Issue by linaori** [WowUp/WowUp#979]
**Describe the bug**
Recording: https://user-images.githubusercontent.com/1754678/124387456-139ff580-dcdf-11eb-91aa-c726521a2d9b.mp4

**To Reproduce**
1. Open an addon with screenshots of different sizes (example uses "Easymail From Cosmos")
2. Click on the addon and go to the screenshots tab
3. Open a small image
4. Use the keyboard arrows to navigate, back and forth, and see that the images become stretched

**Expected behavior**
Arrow keys should work the same as pressing the arrows in the lightbox with your mouse

**Desktop (please complete the following information):**
Present in v2.4.2

**Additional context**
Original bug reported on Discord by Derpo

**Comment by jliddev** [comment]
Replaced the existing lightbox with a different one, should perform slightly better.

**Comment by linaori** [comment]
Fixed
