### ISSUE TITLE
Suppress Warnings

### ISSUE THREAD

**Issue by karai17** [WowUp/WowUp#980]
The sudden flood of warnings for addons that work completely fine but don't have the correct client version listed is obnoxious, to say the least. These warnings are unnecessary. It also doesn't help that many of these warnings are false positives so it would seem the feature doesn't exactly work as intended to begin with. Please add an option to suppress these warnings.

**Comment by karai17** [comment]
....so then you have no intention of providing a quality of life improvement?

**Comment by jliddev** [comment]
Sure lets make it more constructive though.

Can we get an example of a false positive?

**Comment by karai17** [comment]
![image](https://user-images.githubusercontent.com/590332/125003444-9dc4c280-e02d-11eb-963c-a710d2b26b48.png)

This one in particular is listed as being a 2.5.1 addon but is flagged as being out of date. The other handful of warnings I get certainly are out of date as far as packaging goes, but work without throwing any errors and probably don't need to be warning me of much.

![image](https://user-images.githubusercontent.com/590332/125003557-d95f8c80-e02d-11eb-80ed-23d470d67b7e.png)

**Comment by jliddev** [comment]
All these warnings are valid as they are unpdatable. Improved Loot Frame warning is also valid as the author used multi toc on CF which is not supported by them.

**Comment by karai17** [comment]
I know they are valid, I just don't want to see them. I don't care if the
add-on is out of date if it's still working. Default behaviour to show a
warning is perfectly fine but an option to suppress warnings would be
greatly appreciated. The entire top fold of my add-on list is showing
warnings which is about as useful as not showing warnings in the first
place, just far more annoying.

**Comment by jliddev** [comment]
Well you're always going to see them. Even if it didnt say "warning" it would have to say something.

**Comment by karai17** [comment]
It didn't say anything a few releases ago, it doesn't need to say anything
now.
