### ISSUE TITLE
Hope to add support for plug-in custom sources

### ISSUE THREAD

**Issue by jokerping** [WowUp/WowUp#985]
**Is your feature request related to a problem? Please describe.**
I have used some plug-ins, hoping to add custom remote warehouse functions to some local plug-ins

**Describe the solution you'd like**
Right-click the plug-in -> add source/replace source

**Comment by jliddev** [comment]
I dont know what this means.

**Comment by Nils89** [comment]
I think, to possibility to add customs provides via right click.
So right click an add-on - > Provider -> Add custom

Maybe in some cases there are only CF and WI but you know the Github link or something else and you want to switch to GitHub as Provider

**Comment by jliddev** [comment]
Eh we offer a feature like that already, allowing the user to manually change it will cause much confusion i would think.
