### ISSUE TITLE
use a trashcan icon to remove addons from my addons instead

### ISSUE THREAD

**Issue by Raina1007** [WowUp/WowUp#995]
**Is your feature request related to a problem? Please describe.**
No, more a QoL improvement. 

**Describe the solution you'd like**
Would like to have a trashcan icon be next to the name of the addon or underneath it to delete/remove addon instead of the right click addon and click remove functionality

**Describe alternatives you've considered**
Placement of trashcan be adjusted so addons are not accidentally deleted by a misclick as well as a pop up after clicking the trashcan to confirm removal of the addon 

**Additional context**
Would like to simplify the removal of addons if possible, This was requested on discord by gingerbread - I have screenshoted the request for any missing details
![Screen Shot 2021-08-02 at 11 37 22 AM](https://user-images.githubusercontent.com/72997449/127887263-15ce2d33-88d3-434e-91a0-392a08b321cc.png)

**Comment by linaori** [comment]
It could be possible to add a hover per row to show more icons in the row somewhere, as the context menu is also hidden. Same could be done with a select box.
