### ISSUE TITLE
Addons are ignored after moving my install location

### ISSUE THREAD

**Issue by MonthOLDpickle** [WowUp/WowUp#996]
**Describe the bug**
I basically can't un-ignore these addons that have become ignored for some reason. No option to un-ignore in right click for some odd reason.

**To Reproduce**
Move install folder and made sure wowup was pointing to correct folder location

**Expected behavior**
Not many addons being ignored.

**Screenshots**
https://abload.de/img/ignoredh1jol.png

**Desktop (please complete the following information):**
W10 64 bit
I7 37770k
GTX 1070
16GM

**Comment by Raina1007** [comment]
Hey, I'm a mod for WowUp. Did you move WoW to an external drive or portitioned your hard drive and moved WoW there? Have you tried removing them and reinstalling the addons that are stuck on ignore. Once addons are in ignore status, WowUp no longer has the ability to know where the addons came from so it can't connect to any of the providers for those specific addons. Only option in that situation (provided it was not intentionally done) is to remove them and reinstall them. Your settings in WTF aren't affect as WowUp does not touch that folder so you should be able to reinstall without any issues. I would keep an eye on your addons if you moved where WoW is located in case other addons start having issues. If you run into problems or have questions you can respond here or hop into WowUp's discord.
